// The engine calls that take long, handed to a thread of the engine's own so
// the page is not held up: see tools/gen_engine_bridge.py and jniweb::runAsync
// in web_bridge.cpp. Each is the phone's own JNI function, called unchanged.
// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.

#include <jni.h>
#include <emscripten/emscripten.h>
#include <cstdint>

extern "C" JNIEnv *acid_jni_env();

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadNexusPatch(JNIEnv *, jobject, jint, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadNexusPatch(jniweb::Arena *arena, jint rack, jstring spec) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadNexusPatch(acid_jni_env(), nullptr, rack, spec))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeCompCell(JNIEnv *, jobject, jint, jlong, jint, jfloat, jstring, jfloatArray);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeCompCell(jniweb::Arena *arena, jint rack, jlong sceneId, jint frames, jfloat bpm, jstring path, jfloatArray peakOut) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeCompCell(acid_jni_env(), nullptr, rack, sceneId, frames, bpm, path, peakOut))); });
}

extern "C" jint Java_com_rm_acidulous_engine_EngineNative_nativeFileShape(JNIEnv *, jobject, jstring, jfloatArray, jint, jint);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeFileShape(jniweb::Arena *arena, jstring path, jfloatArray out, jint fromFrame, jint toFrame) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = Java_com_rm_acidulous_engine_EngineNative_nativeFileShape(acid_jni_env(), nullptr, path, out, fromFrame, toFrame); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeFileInfo(JNIEnv *, jobject, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeFileInfo(jniweb::Arena *arena, jstring path) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeFileInfo(acid_jni_env(), nullptr, path))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeFileSurvey(JNIEnv *, jobject, jstring, jfloatArray);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeFileSurvey(jniweb::Arena *arena, jstring path, jfloatArray out) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeFileSurvey(acid_jni_env(), nullptr, path, out))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeCutTake(JNIEnv *, jobject, jstring, jint, jfloat, jfloat);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeCutTake(jniweb::Arena *arena, jstring path, jint kind, jfloat noteHz, jfloat consonantNear) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeCutTake(acid_jni_env(), nullptr, path, kind, noteHz, consonantNear))); });
}

extern "C" jint Java_com_rm_acidulous_engine_EngineNative_nativeEditPreview(JNIEnv *, jobject, jstring, jfloatArray, jfloatArray, jint, jint);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeEditPreview(jniweb::Arena *arena, jstring src, jfloatArray ops, jfloatArray out, jint fromFrame, jint toFrame) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = Java_com_rm_acidulous_engine_EngineNative_nativeEditPreview(acid_jni_env(), nullptr, src, ops, out, fromFrame, toFrame); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadUtterance(JNIEnv *, jobject, jint, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadUtterance(jniweb::Arena *arena, jint rack, jstring path) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadUtterance(acid_jni_env(), nullptr, rack, path))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadVoice(JNIEnv *, jobject, jint, jint, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadVoice(jniweb::Arena *arena, jint rack, jint slot, jstring spec) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadVoice(acid_jni_env(), nullptr, rack, slot, spec))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeRenderSong(JNIEnv *, jobject, jstring, jfloat, jint, jint, jint, jfloat);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeRenderSong(jniweb::Arena *arena, jstring path, jfloat tailSeconds, jint format, jint bits, jint startScene, jfloat maxSeconds) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeRenderSong(acid_jni_env(), nullptr, path, tailSeconds, format, bits, startScene, maxSeconds))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeRenderStems(JNIEnv *, jobject, jobjectArray, jintArray, jfloat, jint, jint, jint, jfloat);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeRenderStems(jniweb::Arena *arena, jobjectArray paths, jintArray racks, jfloat tailSeconds, jint format, jint bits, jint startScene, jfloat maxSeconds) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeRenderStems(acid_jni_env(), nullptr, paths, racks, tailSeconds, format, bits, startScene, maxSeconds))); });
}

extern "C" jfloatArray Java_com_rm_acidulous_engine_EngineNative_nativeMeasureLoudness(JNIEnv *, jobject, jfloat, jint, jfloat);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeMeasureLoudness(jniweb::Arena *arena, jfloat tailSeconds, jint startScene, jfloat maxSeconds) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeMeasureLoudness(acid_jni_env(), nullptr, tailSeconds, startScene, maxSeconds))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeSoundFontPresets(JNIEnv *, jobject, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeSoundFontPresets(jniweb::Arena *arena, jstring path) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeSoundFontPresets(acid_jni_env(), nullptr, path))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadSoundFont(JNIEnv *, jobject, jint, jstring, jint);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadSoundFont(jniweb::Arena *arena, jint rackId, jstring path, jint presetIndex) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadSoundFont(acid_jni_env(), nullptr, rackId, path, presetIndex))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadZoneMap(JNIEnv *, jobject, jint, jstring, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadZoneMap(jniweb::Arena *arena, jint rackId, jstring spec, jstring name) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadZoneMap(acid_jni_env(), nullptr, rackId, spec, name))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeSlicePoints(JNIEnv *, jobject, jstring, jint, jint);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeSlicePoints(jniweb::Arena *arena, jstring path, jint mode, jint count) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeSlicePoints(acid_jni_env(), nullptr, path, mode, count))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoopShape(JNIEnv *, jobject, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoopShape(jniweb::Arena *arena, jstring path) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoopShape(acid_jni_env(), nullptr, path))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeImportAudio(JNIEnv *, jobject, jstring, jint);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeImportAudio(jniweb::Arena *arena, jstring path, jint maxSeconds) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeImportAudio(acid_jni_env(), nullptr, path, maxSeconds))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadTake(JNIEnv *, jobject, jint, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadTake(jniweb::Arena *arena, jint rack, jstring path) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadTake(acid_jni_env(), nullptr, rack, path))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadReel(JNIEnv *, jobject, jint, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadReel(jniweb::Arena *arena, jint rack, jstring spec) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadReel(acid_jni_env(), nullptr, rack, spec))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadFormula(JNIEnv *, jobject, jint, jstring, jstring, jstring, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadFormula(jniweb::Arena *arena, jint rack, jstring formula, jstring arp, jstring duty, jstring vol) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadFormula(acid_jni_env(), nullptr, rack, formula, arp, duty, vol))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadEffectFormula(JNIEnv *, jobject, jint, jstring, jstring);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadEffectFormula(jniweb::Arena *arena, jint rack, jstring unit, jstring formula) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadEffectFormula(acid_jni_env(), nullptr, rack, unit, formula))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeBuildCloud(JNIEnv *, jobject, jint, jfloatArray);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeBuildCloud(jniweb::Arena *arena, jint rack, jfloatArray spectrum01) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeBuildCloud(acid_jni_env(), nullptr, rack, spectrum01))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeFreezeClip(JNIEnv *, jobject, jint, jlong, jstring, jfloat);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeFreezeClip(jniweb::Arena *arena, jint rack, jlong sceneId, jstring path, jfloat tailSeconds) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeFreezeClip(acid_jni_env(), nullptr, rack, sceneId, path, tailSeconds))); });
}

extern "C" jstring Java_com_rm_acidulous_engine_EngineNative_nativeLoadFrozen(JNIEnv *, jobject, jint, jlongArray, jobjectArray, jfloatArray, jintArray, jintArray);
extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_nativeLoadFrozen(jniweb::Arena *arena, jint rack, jlongArray sceneIds, jobjectArray paths, jfloatArray bpms, jintArray ticks, jintArray tails) {
    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) { t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>(Java_com_rm_acidulous_engine_EngineNative_nativeLoadFrozen(acid_jni_env(), nullptr, rack, sceneIds, paths, bpms, ticks, tails))); });
}
