package com.rm.acidulous.engine

// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.

/** The engine through JNI: Java_com_rm_acidulous_engine_EngineNative_* in jni_bridge.cpp. */
internal actual object EngineNative {
    init {
        System.loadLibrary("acidulous")
    }

    actual external fun nativePanic()
    @JvmName("nativeLoadNexusPatch")
    private external fun blocking_nativeLoadNexusPatch(rack: Int, spec: String): String
    actual suspend fun nativeLoadNexusPatch(rack: Int, spec: String): String = blocking_nativeLoadNexusPatch(rack, spec)
    actual external fun nativeNexusPalette(): String
    actual external fun nativeNexusScope(rack: Int, out: FloatArray): Int
    actual external fun nativeNexusActivity(rack: Int, out: FloatArray): Int
    actual external fun nativeStartInput(deviceId: Int): Boolean
    actual external fun nativeSetInputClean(on: Boolean)
    actual external fun nativeInputSession(): Int
    actual external fun nativeStopInput(): Boolean
    actual external fun nativeInputChannels(): Int
    actual external fun nativeInputRate(): Int
    actual external fun nativeInputDevice(): Int
    actual external fun nativeInputRunning(): Boolean
    actual external fun nativeInputPeak(): Float
    actual external fun nativeSetInputGain(gain: Float)
    actual external fun nativeSetSwingUnit(unit: Int)
    actual external fun nativeSetTunerOn(on: Boolean)
    actual external fun nativeTunerHz(): Float
    actual external fun nativeSetMonitorLevel(level: Float)
    actual external fun nativeStartCapture(path: String, source: Int): String
    actual external fun nativeStopCapture()
    actual external fun nativeCapturing(): Boolean
    actual external fun nativeCapturedSeconds(): Float
    actual external fun nativeCapturedPeak(): Float
    actual external fun nativeCaptureOverflowed(): Boolean
    actual external fun nativeCaptureDeaf(): Boolean
    actual external fun nativeCapturedFrames(): Long
    @JvmName("nativeCompCell")
    private external fun blocking_nativeCompCell(rack: Int, sceneId: Long, frames: Int, bpm: Float, path: String, peakOut: FloatArray): String
    actual suspend fun nativeCompCell(rack: Int, sceneId: Long, frames: Int, bpm: Float, path: String, peakOut: FloatArray): String = blocking_nativeCompCell(rack, sceneId, frames, bpm, path, peakOut)
    actual external fun nativeArmCapture(rack: Int)
    actual external fun nativeCaptureMarks(out: LongArray): Int
    @JvmName("nativeFileShape")
    private external fun blocking_nativeFileShape(path: String, out: FloatArray, fromFrame: Int, toFrame: Int): Int
    actual suspend fun nativeFileShape(path: String, out: FloatArray, fromFrame: Int, toFrame: Int): Int = blocking_nativeFileShape(path, out, fromFrame, toFrame)
    @JvmName("nativeFileInfo")
    private external fun blocking_nativeFileInfo(path: String): String
    actual suspend fun nativeFileInfo(path: String): String = blocking_nativeFileInfo(path)
    @JvmName("nativeFileSurvey")
    private external fun blocking_nativeFileSurvey(path: String, out: FloatArray): String
    actual suspend fun nativeFileSurvey(path: String, out: FloatArray): String = blocking_nativeFileSurvey(path, out)
    actual external fun nativeAuditionFile(path: String): String
    actual external fun nativeAuditioning(): Boolean
    actual external fun nativeAuditionProgress(): Float
    actual external fun nativeEditSample(src: String, dst: String, ops: FloatArray): String
    @JvmName("nativeEditPreview")
    private external fun blocking_nativeEditPreview(src: String, ops: FloatArray, out: FloatArray, fromFrame: Int, toFrame: Int): Int
    actual suspend fun nativeEditPreview(src: String, ops: FloatArray, out: FloatArray, fromFrame: Int, toFrame: Int): Int = blocking_nativeEditPreview(src, ops, out, fromFrame, toFrame)
    actual external fun nativeAuditionPreview(): String
    actual external fun nativeMidiEvent(rackId: Int, status: Int, data1: Int, data2: Int, channel: Int)
    actual external fun nativeSetMpeZone(kind: Int, members: Int, bendSemis: Float)
    actual external fun nativeMpeHeldMask(): Int
    actual external fun nativeStart(): Boolean
    actual external fun nativeStop()
    actual external fun nativeIsRunning(): Boolean
    @JvmName("nativeLoadUtterance")
    private external fun blocking_nativeLoadUtterance(rack: Int, path: String): String
    actual suspend fun nativeLoadUtterance(rack: Int, path: String): String = blocking_nativeLoadUtterance(rack, path)
    actual external fun nativeMountMachine(rackId: Int, typeName: String): Boolean
    actual external fun nativeUnmountMachine(rackId: Int)
    @JvmName("nativeRenderSong")
    private external fun blocking_nativeRenderSong(path: String, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String
    actual suspend fun nativeRenderSong(path: String, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String = blocking_nativeRenderSong(path, tailSeconds, format, bits, startScene, maxSeconds)
    @JvmName("nativeRenderStems")
    private external fun blocking_nativeRenderStems(paths: Array<String>, racks: IntArray, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String
    actual suspend fun nativeRenderStems(paths: Array<String>, racks: IntArray, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String = blocking_nativeRenderStems(paths, racks, tailSeconds, format, bits, startScene, maxSeconds)
    actual external fun nativeSetCountInBars(bars: Int)
    actual external fun nativeCountInRemaining(): Long
    actual external fun nativeCancelRender()
    actual external fun nativeIsRendering(): Boolean
    actual external fun nativeRenderedSeconds(): Float
    actual external fun nativeRenderedPeak(): Float
    actual external fun nativePrewarm()
    actual external fun nativeMountInputMod(rackId: Int, slot: Int, typeName: String): Boolean
    actual external fun nativeInputModTypes(): Array<String>
    actual external fun nativeInputModParamInfo(type: String): Array<String>
    actual external fun nativeMountEffect(rackId: Int, slot: Int, typeName: String): Boolean
    actual external fun nativeMountSend(slot: Int, typeName: String): Boolean
    @JvmName("nativeMeasureLoudness")
    private external fun blocking_nativeMeasureLoudness(tailSeconds: Float, startScene: Int, maxSeconds: Float): FloatArray?
    actual suspend fun nativeMeasureLoudness(tailSeconds: Float, startScene: Int, maxSeconds: Float): FloatArray? = blocking_nativeMeasureLoudness(tailSeconds, startScene, maxSeconds)
    actual external fun nativeSetRenderGain(db: Float)
    actual external fun nativeLoudness(): FloatArray
    actual external fun nativeResetLoudness()
    actual external fun nativeMountMasterInsert(slot: Int, typeName: String): Boolean
    actual external fun nativeMountGroupInsert(group: Int, slot: Int, typeName: String): Boolean
    actual external fun nativeGroupPeak(group: Int): Float
    actual external fun nativeMountInputEffect(slot: Int, typeName: String): Boolean
    actual external fun nativeEffectTypes(): Array<String>
    actual external fun nativeEffectParamInfo(type: String): Array<String>
    actual external fun nativeLoadSample(rackId: Int, slot: Int, path: String, maxSeconds: Int): String
    @JvmName("nativeSoundFontPresets")
    private external fun blocking_nativeSoundFontPresets(path: String): String
    actual suspend fun nativeSoundFontPresets(path: String): String = blocking_nativeSoundFontPresets(path)
    @JvmName("nativeLoadSoundFont")
    private external fun blocking_nativeLoadSoundFont(rackId: Int, path: String, presetIndex: Int): String
    actual suspend fun nativeLoadSoundFont(rackId: Int, path: String, presetIndex: Int): String = blocking_nativeLoadSoundFont(rackId, path, presetIndex)
    @JvmName("nativeLoadZoneMap")
    private external fun blocking_nativeLoadZoneMap(rackId: Int, spec: String, name: String): String
    actual suspend fun nativeLoadZoneMap(rackId: Int, spec: String, name: String): String = blocking_nativeLoadZoneMap(rackId, spec, name)
    actual external fun nativeSampleMapInfo(rackId: Int): String
    actual external fun nativeSampleInfo(rackId: Int, slot: Int): String
    @JvmName("nativeSlicePoints")
    private external fun blocking_nativeSlicePoints(path: String, mode: Int, count: Int): String
    actual suspend fun nativeSlicePoints(path: String, mode: Int, count: Int): String = blocking_nativeSlicePoints(path, mode, count)
    @JvmName("nativeLoopShape")
    private external fun blocking_nativeLoopShape(path: String): String
    actual suspend fun nativeLoopShape(path: String): String = blocking_nativeLoopShape(path)
    @JvmName("nativeImportAudio")
    private external fun blocking_nativeImportAudio(path: String, maxSeconds: Int): String
    actual suspend fun nativeImportAudio(path: String, maxSeconds: Int): String = blocking_nativeImportAudio(path, maxSeconds)
    actual external fun nativeSampleShape(rack: Int, pad: Int, out: FloatArray, fromFrame: Int, toFrame: Int): Int
    actual external fun nativeMachineTypes(): Array<String>
    actual external fun nativeNoteOn(rackId: Int, note: Int, velocity: Int)
    actual external fun nativeNoteOff(rackId: Int, note: Int)
    actual external fun nativeControlChange(rackId: Int, cc: Int, value: Int, record: Boolean)
    actual external fun nativeChannelPressure(rackId: Int, value: Int, record: Boolean)
    actual external fun nativeSetParam(rackId: Int, unit: String, name: String, value: Float, record: Boolean, quantise: Int): Boolean
    @JvmName("nativeLoadTake")
    private external fun blocking_nativeLoadTake(rack: Int, path: String): String
    actual suspend fun nativeLoadTake(rack: Int, path: String): String = blocking_nativeLoadTake(rack, path)
    @JvmName("nativeLoadReel")
    private external fun blocking_nativeLoadReel(rack: Int, spec: String): String
    actual suspend fun nativeLoadReel(rack: Int, spec: String): String = blocking_nativeLoadReel(rack, spec)
    actual external fun nativeSetCacheRoot(path: String)
    @JvmName("nativeLoadFormula")
    private external fun blocking_nativeLoadFormula(rack: Int, formula: String, arp: String, duty: String, vol: String): String
    actual suspend fun nativeLoadFormula(rack: Int, formula: String, arp: String, duty: String, vol: String): String = blocking_nativeLoadFormula(rack, formula, arp, duty, vol)
    @JvmName("nativeBuildCloud")
    private external fun blocking_nativeBuildCloud(rack: Int, spectrum01: FloatArray): String
    actual suspend fun nativeBuildCloud(rack: Int, spectrum01: FloatArray): String = blocking_nativeBuildCloud(rack, spectrum01)
    @JvmName("nativeFreezeClip")
    private external fun blocking_nativeFreezeClip(rack: Int, sceneId: Long, path: String, tailSeconds: Float): String
    actual suspend fun nativeFreezeClip(rack: Int, sceneId: Long, path: String, tailSeconds: Float): String = blocking_nativeFreezeClip(rack, sceneId, path, tailSeconds)
    @JvmName("nativeLoadFrozen")
    private external fun blocking_nativeLoadFrozen(rack: Int, sceneIds: LongArray, paths: Array<String>, bpms: FloatArray, ticks: IntArray, tails: IntArray): String
    actual suspend fun nativeLoadFrozen(rack: Int, sceneIds: LongArray, paths: Array<String>, bpms: FloatArray, ticks: IntArray, tails: IntArray): String = blocking_nativeLoadFrozen(rack, sceneIds, paths, bpms, ticks, tails)
    actual external fun nativeSetBufferBursts(bursts: Int)
    actual external fun nativeBufferFrames(): Int
    actual external fun nativeSetVoiceLimit(notes: Int)
    actual external fun nativeSetQuality(level: Int)
    actual external fun nativeSetRecordBits(bits: Int)
    actual external fun nativeGetSampleRate(): Int
    actual external fun nativeGetFramesPerBurst(): Int
    actual external fun nativeIsLowLatency(): Boolean
    actual external fun nativeGetXRunCount(): Long
    actual external fun nativeGetLoadAvg(): Float
    actual external fun nativeWorstBlockUs(): Int
    actual external fun nativeWorstCallbackUs(): Int
    actual external fun nativeWorstPhaseUs(phase: Int): Int
    actual external fun nativeWorstRackUs(rack: Int): Int
    actual external fun nativeRackPercentileUs(rack: Int): Int
    actual external fun nativeResetRackCosts()
    actual external fun nativeWorstRackWasFrozen(rack: Int): Boolean
    actual external fun nativeInterruptedPercent(): Float
    actual external fun nativeHintRunning(): Boolean
    actual external fun nativeHintAvailable(): Boolean
    actual external fun nativeHintState(): Int
    actual external fun nativeRackCostUs(rack: Int): Int
    actual external fun nativeRecentCallbackUs(): Int
    actual external fun nativeWorstCallbackCpuUs(): Int
    actual external fun nativeLateCallbacks(): Long
    actual external fun nativeStalledCallbacks(): Long
    actual external fun nativeCallbackBudgetUs(): Int
    actual external fun nativeReadPeakLevel(): Float
    actual external fun nativeReadRackPeak(rackId: Int): Float
    actual external fun nativeGetMasterFade(): Float
    actual external fun nativeTransportPlay(sceneIdx: Int)
    actual external fun nativeTransportStop()
    actual external fun nativeTransportRewind()
    actual external fun nativeSetStopAtEnd(on: Boolean)
    actual external fun nativeIsStopAtEndArmed(): Boolean
    actual external fun nativeQueueScene(idx: Int)
    actual external fun nativeQueuedScene(): Int
    actual external fun nativeSetLauncher(on: Boolean)
    actual external fun nativeSetFill(on: Boolean)
    actual external fun nativeSetLaunchQuantise(ticks: Int)
    actual external fun nativeLaunchClip(rack: Int, sceneId: Long)
    actual external fun nativeLaunchScene(sceneId: Long)
    actual external fun nativeStopAllClips()
    actual external fun nativeCancelLaunch(rack: Int)
    actual external fun nativeSetClockOut(on: Boolean)
    actual external fun nativeDrainMidiOut(out: LongArray): Int
    actual external fun nativeAudioAnchor(out: LongArray)
    actual external fun nativeSetExternalSync(on: Boolean)
    actual external fun nativeSetTuning(rack: Int, ratios: FloatArray?)
    actual external fun nativeSetLink(on: Boolean)
    actual external fun nativeLinkEnabled(): Boolean
    actual external fun nativeSetLinkStartStop(on: Boolean)
    actual external fun nativeLinkStatus(): Long
    actual external fun nativeMidiClockIn(frame: Long, status: Int, d1: Int, d2: Int)
    actual external fun nativeSyncState(): Long
    actual external fun nativeLaunchStates(out: LongArray)
    actual external fun nativeIsPlaying(): Boolean
    actual external fun nativeSetLoopScene(on: Boolean)
    actual external fun nativeSetLoopSong(on: Boolean)
    actual external fun nativeSetRecordArmed(on: Boolean)
    actual external fun nativeIsRecordArmed(): Boolean
    actual external fun nativeDrainRecorded(out: LongArray): Int
    actual external fun nativeGetRecordedDropped(): Int
    actual external fun nativeSetTempo(bpm: Float)
    actual external fun nativeGetTempo(): Float
    actual external fun nativeGetPositionPacked(): Long
    actual external fun nativeGetNotesOn(rackId: Int): Int
    actual external fun nativeDebugParam(rackId: Int, name: String): Float
    actual external fun nativeGetNotesOff(rackId: Int): Int
    actual external fun nativeSnapshotBegin(): Long
    actual external fun nativeSnapshotAddScene(handle: Long, sceneId: Long, ticksPerBar: Int, repeat: Int, bpmOverride: Float, rampToBpm: Float, rampBars: Int, smooth: Boolean, fadeIn: Boolean, fadeOut: Boolean): Boolean
    actual external fun nativeSnapshotSetClipCached(handle: Long, rack: Int, scene: Int, rev: Long): Boolean
    actual external fun nativeSnapshotSetClip(handle: Long, rack: Int, scene: Int, rev: Long, bars: Int, playMode: Int, mute: Boolean, seed: Int, notes: IntArray, expr: FloatArray, lyrics: String?): Boolean
    actual external fun nativeSnapshotSetLane(handle: Long, rack: Int, scene: Int, machineType: String, unit: String, name: String, linear: Boolean, points: FloatArray): Boolean
    actual external fun nativeSnapshotCommit(handle: Long): Boolean
    actual external fun nativeMachineParamNames(type: String): Array<String>
    actual external fun nativeMachineParamInfo(type: String): Array<String>
    actual external fun nativeParamNormalized(rackId: Int, unit: String, name: String): Float
    actual external fun nativeSnapshotAbandon(handle: Long)
}
