#!/usr/bin/env python3
"""Generates engine/machine/hammer/Dispersion.h: the stiffness allpass for any note.

    dispersion.py [--report]

A stiff string puts partial k at k·f0·sqrt(1 + B·k²). Hammer's string loop
gets that from M identical first-order allpasses; with the loop tuned so the
fundamental is exact, one coefficient sets where every other partial lands.
No one coefficient puts them all right, and partial k's place isn't monotonic
in the coefficient, so it can't be solved for at a note-on. Here, offline,
for each note (as f0 at 48 kHz), each B and each M, the coefficient that puts
the partials the hammer puts energy into closest to where they belong, in
cents, each counting as 1/k (the low ones carry the pitch and the beating):
the first 30, up to 3.5 kHz or 3.5 f0, whichever is higher. --report prints the error left by register.

Why only 30: a first-order stage's whole delay drop is about 2/corner samples
and comes at its corner, so a long bass string, whose partials need hundreds
of samples less delay by the 60th, would want 32 stages or more to follow all
of them. Fitting all 60 with fewer spends the error where the hammer puts its
energy; fitting the first 30 keeps that right (A0: within 25 cents to the
24th with 16 stages) and lets the faint ones above go flat.
"""
import multiprocessing
import os
import sys

import numpy as np

SR = 48000.0
KEYS = np.arange(12, 122, 2)                      # f0 axis: notes at 48 kHz, every other one
LOG_B = np.round(np.arange(-6.0, -1.19, 0.15), 3)  # B axis: log10
STAGES = [1, 2, 4, 8, 16]
TOP_HZ = 3500.0
MAX_PARTIALS = 30
OUT = os.path.join(os.path.dirname(__file__), '..', '..', 'app', 'src', 'main', 'cpp', 'engine', 'machine',
                   'hammer', 'Dispersion.h')


def lag(c, w):
    """Phase lag of (c + z^-1) / (1 + c z^-1) at w, radians."""
    return -(np.arctan2(-np.sin(w), c + np.cos(w)) - np.arctan2(-c * np.sin(w), 1 + c * np.cos(w)))


def delay(c, w):
    """Its group delay, samples."""
    return (1 - c * c) / (1 + 2 * c * np.cos(w) + c * c)


def partials(f0, c, m, ks):
    """Where partials [ks] of the loop tuned to f0 land, Hz: one row per coefficient in [c]."""
    w0 = 2 * np.pi * f0 / SR
    c = c[:, None]
    line = (2 * np.pi - m * lag(c, w0)) / w0          # the rest of the loop, a plain delay
    w = np.broadcast_to(ks[None, :] * w0, (c.shape[0], len(ks))).copy()
    for _ in range(30):
        f = w * line + m * lag(c, w) - 2 * np.pi * ks[None, :]
        w = np.clip(w - f / (line + m * delay(c, w)), 1e-5, np.pi - 1e-4)
    return w * SR / (2 * np.pi)


def best(f0, B, m):
    ks = np.arange(2, MAX_PARTIALS + 1, dtype=float)
    ks = ks[ks * f0 * np.sqrt(1 + B * ks * ks) < min(max(TOP_HZ, 3.5 * f0), 0.42 * SR)]
    if len(ks) == 0:
        return 0.0, 0.0
    want = ks * f0 * np.sqrt(1 + B * ks * ks)
    weight = 1.0 / ks

    def cost(c):
        got = partials(f0, c, m, ks)
        cents = 1200 * np.log2(got / want[None, :])
        return (weight[None, :] * cents ** 2).sum(1) / weight.sum()

    grid = -(1 - np.geomspace(0.01, 1, 160))
    e = cost(grid)
    i = int(np.argmin(e))
    lo, hi = grid[min(i + 1, len(grid) - 1)], grid[max(i - 1, 0)]
    fine = np.linspace(lo, hi, 61)
    e2 = cost(fine)
    j = int(np.argmin(e2))
    return float(fine[j]), float(np.sqrt(e2[j]))


def row(job):
    s, k = job
    f0 = 440.0 * 2 ** ((KEYS[k] - 69) / 12)
    return s, k, [best(f0, 10 ** lb, STAGES[s]) for lb in LOG_B]


def main():
    report = '--report' in sys.argv
    table = np.zeros((len(STAGES), len(KEYS), len(LOG_B)))
    error = np.zeros_like(table)
    jobs = [(s, k) for s in range(len(STAGES)) for k in range(len(KEYS))]
    with multiprocessing.Pool(max(1, multiprocessing.cpu_count() // 2)) as pool:
        for s, k, cells in pool.imap_unordered(row, jobs):
            for b, (c, e) in enumerate(cells):
                table[s, k, b], error[s, k, b] = c, e
    if report:
        print('rms cents left, by key (rows) and log10 B (columns), per stage count')
        cols = [i for i, lb in enumerate(LOG_B) if abs(lb * 2 - round(lb * 2)) < 1e-6]
        for s, m in enumerate(STAGES):
            print(f'\n  {m} stages   ' + ' '.join(f'{LOG_B[i]:6.1f}' for i in cols))
            for k in range(0, len(KEYS), 4):
                print(f'  key {KEYS[k]:3d}    ' + ' '.join(f'{error[s, k, i]:6.1f}' for i in cols))
    with open(OUT, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Generated by tools/hammer_reference/dispersion.py. Do not edit.\n')
        f.write('//\n')
        f.write('// The stiffness allpass coefficient for a string loop: by stage count, by\n')
        f.write('// note (f0 as a key at 48 kHz) and by log10 of B. Course.h reads between.\n')
        f.write('namespace acidulous::machine::hammer::dispersion {\n\n')
        f.write(f'constexpr int kStageCounts = {len(STAGES)};\n')
        f.write('constexpr int kStages[kStageCounts] = {' + ', '.join(map(str, STAGES)) + '};\n')
        f.write(f'constexpr int kKeys = {len(KEYS)};\n')
        f.write(f'constexpr float kFirstKey = {KEYS[0]:.1f}f, kKeyStep = {KEYS[1] - KEYS[0]:.1f}f;\n')
        f.write(f'constexpr int kBs = {len(LOG_B)};\n')
        f.write(f'constexpr float kFirstLogB = {LOG_B[0]:.2f}f, kLogBStep = {LOG_B[1] - LOG_B[0]:.2f}f;\n\n')
        f.write('constexpr float kCoefficient[kStageCounts][kKeys][kBs] = {\n')
        for s in range(len(STAGES)):
            f.write('    {\n')
            for k in range(len(KEYS)):
                f.write('        {' + ', '.join(f'{v:.4f}f' for v in table[s, k]) + '},\n')
            f.write('    },\n')
        f.write('};\n\n} // namespace acidulous::machine::hammer::dispersion\n')
    print(f'wrote {os.path.normpath(OUT)}')


if __name__ == '__main__':
    main()
