// GENERATED by tools/gen_patches.sh from tools/banks/*.bank - do not edit.
//
// Edit the bank file and run the script. A value there is written in the
// parameter's own units and converted here by the engine's own ParamDef, so
// what the audition harness played is what the app plays.
package com.rm.acidulous.model

internal object FactoryBanks {
    fun of(unit: String): List<Patch> = when (unit) {
        "Subvert" -> subvert
        "Trinity" -> trinity
        "Ratio" -> ratio
        "Manual" -> manual
        "Cumulus" -> cumulus
        "Formulate" -> formulate
        "Pollen" -> pollen
        "Brazen" -> brazen
        "Timber" -> timber
        "Cipher" -> cipher
        "Filament" -> filament
        "Hexbeat" -> hexbeat
        "Genesis" -> genesis
        "Resonance" -> resonance
        "Dice" -> dice
        "Mosaic" -> mosaic
        "fx.Delay" -> fx_delay
        else -> emptyList()
    }

    private fun subvert0() = Patch("Subvert", "Init", emptyMap())

    private fun subvert1() = Patch("Subvert", "Classic",
        mapOf("cutoff" to 0.408023566f, "resonance" to 0.72f, "envmod" to 0.64f, "decay" to 0.4850184f, "accent" to 0.75f, "slide" to 0.5f, "drive" to 0.16f))

    private fun subvert2() = Patch("Subvert", "Squelch",
        mapOf("cutoff" to 0.369967341f, "resonance" to 0.9f, "envmod" to 0.85f, "decay" to 0.318411052f, "accent" to 0.92f, "slide" to 0.451545f, "drive" to 0.22f, "volume" to 0.72f))

    private fun subvert3() = Patch("Subvert", "Rubber",
        mapOf("wave" to 1f, "cutoff" to 0.350310653f, "resonance" to 0.75f, "envmod" to 0.7f, "decay" to 0.349485f, "accent" to 0.8f, "slide" to 0.7074866f, "drive" to 0.25f, "volume" to 0.6f, "pw" to 0.4111111f))

    private fun subvert4() = Patch("Subvert", "Long Sweep",
        mapOf("cutoff" to 0.26369825f, "resonance" to 0.72f, "envmod" to 0.95f, "decay" to 0.863499343f, "accent" to 0.45f, "drive" to 0.15f, "volume" to 0.72f))

    private fun subvert5() = Patch("Subvert", "Sub Hollow",
        mapOf("wave" to 1f, "cutoff" to 0.298880249f, "resonance" to 0.38f, "envmod" to 0.3f, "decay" to 0.60205996f, "accent" to 0.5f, "drive" to 0.08f, "volume" to 0.7f, "pw" to 0.211111113f, "sub" to 0.65f))

    private fun subvert6() = Patch("Subvert", "Band Squelch",
        mapOf("cutoff" to 0.499284834f, "resonance" to 0.85f, "envmod" to 0.8f, "decay" to 0.30102998f, "accent" to 0.9f, "drive" to 0.55f, "volume" to 1f, "mode" to 1f))

    private fun subvert7() = Patch("Subvert", "Buzzsaw",
        mapOf("cutoff" to 0.7682668f, "resonance" to 0.25f, "envmod" to 0.25f, "decay" to 0.562469363f, "accent" to 0.55f, "drive" to 0.85f, "volume" to 0.92f))

    private fun subvert8() = Patch("Subvert", "Thin Ice",
        mapOf("cutoff" to 0.623331666f, "resonance" to 0.97f, "envmod" to 0.15f, "decay" to 0.432650715f, "accent" to 0.4f, "drive" to 0.05f, "volume" to 0.85f))

    private fun subvert9() = Patch("Subvert", "Doorstop",
        mapOf("cutoff" to 0.14217411f, "envmod" to 1f, "decay" to 0.238560632f, "accent" to 0.85f, "slide" to 0.349485f, "drive" to 0.3f, "volume" to 0.85f))

    private val subvert: List<Patch> by lazy { listOf(subvert0(), subvert1(), subvert2(), subvert3(), subvert4(), subvert5(), subvert6(), subvert7(), subvert8(), subvert9()) }

    private fun trinity0() = Patch("Trinity", "Init", emptyMap())

    private fun trinity1() = Patch("Trinity", "Wide Saws",
        mapOf("o1_level" to 0.7f, "o1_density" to 0.714285731f, "o1_detune" to 0.45f, "o1_drift" to 0.3f, "o2_fine" to 0.41f, "o2_level" to 0.6f, "o2_density" to 0.428571433f, "o2_detune" to 0.6f, "o2_drift" to 0.3f, "o3_coarse" to 0.25f, "o3_level" to 0.4f, "o3_density" to 0.142857149f, "o3_drift" to 0.2f, "f1_freq" to 0.8257071f, "f1_res" to 0.1f, "f1_env" to 0.625f, "a_attack" to 0.32525748f, "a_decay" to 0.716931f, "a_sustain" to 0.8f, "a_release" to 0.618813455f, "m01_src" to 0.13333334f, "m01_dest" to 0.6969697f, "m01_depth" to 0.7f, "m02_src" to 0.2f, "m02_dest" to 0.5151515f, "m02_depth" to 0.7f))

    private fun trinity2() = Patch("Trinity", "Glass Pad",
        mapOf("o1_wave" to 0.454545468f, "o1_pos" to 0.2f, "o1_level" to 0.75f, "o2_wave" to 0.363636374f, "o2_pos" to 0.6f, "o2_fine" to 0.56f, "f1_type" to 0.09090909f, "f1_freq" to 0.76701f, "f1_res" to 0.2f, "a_attack" to 0.7257725f, "a_decay" to 0.774181366f, "a_sustain" to 0.75f, "a_release" to 0.79919f, "l1_rate" to 0.3265052f, "l2_rate" to 0.2346152f, "m01_src" to 0.8666667f, "m01_dest" to 0.151515156f, "m01_depth" to 0.7f, "m02_src" to 0.933333337f, "m02_dest" to 0.6969697f, "m02_depth" to 0.575f, "m03_src" to 0.13333334f, "m03_dest" to 0.151515156f, "m03_depth" to 0.75f, "m04_src" to 0.2f, "m04_dest" to 0.6969697f, "m04_depth" to 0.725f))

    private fun trinity3() = Patch("Trinity", "Bell Keys",
        mapOf("o1_wave" to 0.6363636f, "o1_pos" to 0.7f, "o2_wave" to 0.272727281f, "o2_coarse" to 0.75f, "o2_level" to 0.35f, "ring12" to 0.35f, "f1_freq" to 0.8844042f, "f1_env" to 0.75f, "a_attack" to 0.075257495f, "a_decay" to 0.7491727f, "a_sustain" to 0.05f, "a_release" to 0.716931f, "f_sustain" to 0f))

    private fun trinity4() = Patch("Trinity", "FM Bass",
        mapOf("o1_wave" to 0.272727281f, "o1_level" to 0.9f, "o2_wave" to 0.272727281f, "o2_coarse" to 0.75f, "o2_level" to 0f, "fm21" to 0.55f, "f1_freq" to 0.551070869f, "f1_res" to 0.25f, "f1_env" to 0.775f, "a_attack" to 0.075257495f, "a_decay" to 0.578839362f, "a_sustain" to 0.35f, "a_release" to 0.483879149f, "f_decay" to 0.5161209f, "f_sustain" to 0f, "e3_decay" to 0.5411295f, "e3_sustain" to 0f, "m01_src" to 0.6f, "m01_dest" to 0.6363636f, "m01_depth" to 0.65f, "voicemode" to 0.333333343f, "glide" to 0.04f))

    private fun trinity5() = Patch("Trinity", "Sync Lead",
        mapOf("o1_level" to 0.85f, "o1_sync" to 0.25f, "o2_wave" to 0.09090909f, "o2_fine" to 0.55f, "o2_level" to 0.3f, "f1_freq" to 0.84802264f, "a_attack" to 0.24999997f, "a_decay" to 0.618813455f, "a_sustain" to 0.85f, "a_release" to 0.5161209f, "m01_src" to 0.13333334f, "m01_dest" to 0.424242437f, "m01_depth" to 0.85f, "m02_src" to 0.266666681f, "m02_dest" to 0.6969697f, "m02_depth" to 0.65f, "voicemode" to 0.6666667f, "glide" to 0.06f))

    private fun trinity6() = Patch("Trinity", "Drift Strings",
        mapOf("o1_level" to 0.6f, "o1_density" to 0.2857143f, "o1_detune" to 0.3f, "o1_drift" to 0.8f, "o2_fine" to 0.43f, "o2_level" to 0.55f, "o2_drift" to 0.9f, "o3_wave" to 0.181818187f, "o3_coarse" to 0.75f, "o3_level" to 0.35f, "o3_drift" to 0.7f, "f1_type" to 0.181818187f, "f1_freq" to 0.747679353f, "f1_res" to 0.05f, "a_attack" to 0.636016965f, "a_decay" to 0.774181366f, "a_sustain" to 0.85f, "a_release" to 0.7342073f, "l1_rate" to 0.736582041f, "l1_delay" to 0.4f, "m01_src" to 0.8666667f, "m01_src2" to 0.13333334f, "m01_dest" to 0.0303030312f, "m01_depth" to 0.51f))

    private val trinity: List<Patch> by lazy { listOf(trinity0(), trinity1(), trinity2(), trinity3(), trinity4(), trinity5(), trinity6()) }

    private fun ratio0() = Patch("Ratio", "Init", emptyMap())

    private fun ratio1() = Patch("Ratio", "Tine",
        mapOf("o1_decay" to 0.79919f, "o1_sustain" to 0.25f, "o2_ratio" to 0.7259193f, "o2_level" to 0.55f, "o2_decay" to 0.578839362f, "o2_sustain" to 0f, "o2_vel" to 0.9f, "o3_level" to 0.5f, "o3_decay" to 0.774181366f, "o3_sustain" to 0.2f, "o4_ratio" to 0.448120326f, "o4_level" to 0.35f, "o4_sustain" to 0f, "algoa" to 0.193548381f))

    private fun ratio2() = Patch("Ratio", "Bell",
        mapOf("o1_decay" to 0.897307456f, "o1_sustain" to 0f, "o1_release" to 0.897307456f, "o2_ratio" to 0.433083534f, "o2_level" to 0.6f, "o2_decay" to 0.81962353f, "o2_sustain" to 0f, "o2_release" to 0.81962353f, "o3_ratio" to 0.554119945f, "o3_level" to 0.45f, "o3_decay" to 0.8518653f, "o3_sustain" to 0f, "o3_release" to 0.8518653f, "algoa" to 0.193548381f, "snap" to 1f))

    private fun ratio3() = Patch("Ratio", "Grit Bass",
        mapOf("o1_level" to 0.9f, "o1_decay" to 0.618813455f, "o1_sustain" to 0.6f, "o2_level" to 0.65f, "o2_fb" to 0.55f, "o2_decay" to 0.5411295f, "o2_sustain" to 0.15f, "o3_mode" to 1f, "o3_level" to 0.4f, "o3_fb" to 0.4f, "f_freq" to 0.6804642f, "f_res" to 0.2f, "m01_src" to 0.307692319f, "m01_dest" to 0.2173913f, "m01_depth" to 0.675f, "voicemode" to 0.5f))

    private fun ratio4() = Patch("Ratio", "Morph Sweep",
        mapOf("o1_level" to 0.7f, "o1_attack" to 0.650515f, "o1_sustain" to 0.8f, "o1_release" to 0.7419396f, "o2_ratio" to 0.375f, "o2_level" to 0.6f, "o2_sustain" to 0.7f, "o3_ratio" to 0.448120326f, "o3_level" to 0.5f, "o3_sustain" to 0.6f, "o4_ratio" to 0.5f, "o4_level" to 0.45f, "o5_ratio" to 0.5731203f, "o5_level" to 0.4f, "o6_ratio" to 0.625f, "o6_level" to 0.35f, "e1_attack" to 0.7697953f, "e1_decay" to 0.81962353f, "e1_sustain" to 0.4f, "m01_src" to 0.538461566f, "m01_dest" to 0.08695652f, "m01_depth" to 0.85f, "m02_src" to 0.15384616f, "m02_dest" to 0.08695652f, "m02_depth" to 0.8f))

    private fun ratio5() = Patch("Ratio", "Fold Lead",
        mapOf("o1_mode" to 0.5714286f, "o1_level" to 0.85f, "o1_fb" to 0.45f, "o1_sustain" to 0.9f, "o2_wave" to 0.466666669f, "o2_level" to 0.8f, "o2_sustain" to 0.9f, "algoa" to 0.09677419f, "m01_src" to 0.230769232f, "m01_dest" to 0.130434781f, "m01_depth" to 0.65f, "voicemode" to 1f, "glide" to 0.05f))

    private fun ratio6() = Patch("Ratio", "Sync Stab",
        mapOf("o1_mode" to 0.714285731f, "o1_ratio" to 0.521240652f, "o1_level" to 0.85f, "o1_decay" to 0.639247f, "o1_sustain" to 0.3f, "o2_wave" to 0.466666669f, "o2_level" to 0.9f, "o2_sustain" to 1f, "algoa" to 0.09677419f, "snap" to 0f, "l1_rate" to 0.4447622f, "m01_src" to 0.846153855f, "m01_dest" to 0.4347826f, "m01_depth" to 0.625f))

    private fun ratio7() = Patch("Ratio", "Stretched",
        mapOf("o1_level" to 0.75f, "o1_decay" to 0.81962353f, "o1_sustain" to 0.3f, "o1_release" to 0.774181366f, "o2_ratio" to 0.448120326f, "o2_level" to 0.55f, "o3_ratio" to 0.600919366f, "o3_level" to 0.4f, "algoa" to 0.193548381f, "skew" to 0.72f, "m01_src" to 0.15384616f, "m01_dest" to 0.130434781f, "m01_depth" to 0.75f))

    private val ratio: List<Patch> by lazy { listOf(ratio0(), ratio1(), ratio2(), ratio3(), ratio4(), ratio5(), ratio6(), ratio7()) }

    private fun manual0() = Patch("Manual", "Init", emptyMap())

    private fun manual1() = Patch("Manual", "Gospel",
        mapOf("ua_513" to 1f, "ua_4" to 0f, "la_8" to 1f, "la_4" to 1f, "perclvl" to 0.7f, "vibtype" to 0.6f, "vibdepth" to 0.5f, "rotspeed" to 1f, "drive" to 0.3f))

    private fun manual2() = Patch("Manual", "Smoke",
        mapOf("age" to 0.4f, "leakage" to 0.3f, "click" to 0.5f, "ua_513" to 1f, "ua_4" to 1f, "la_16" to 1f, "la_513" to 1f, "la_8" to 1f, "la_4" to 0f, "perc" to 0f, "rotspeed" to 0.5f, "drive" to 0.45f))

    private fun manual3() = Patch("Manual", "Booker",
        mapOf("ua_513" to 0.75f, "ua_4" to 1f, "ua_223" to 0.75f, "ua_2" to 1f, "ua_135" to 1f, "ua_113" to 0.75f, "ua_1" to 1f, "la_16" to 1f, "la_513" to 0.5f, "la_8" to 1f, "la_4" to 0f, "percharm" to 0f, "perclvl" to 0.5f, "percfast" to 0f, "rotspeed" to 1f, "drive" to 0.35f))

    private fun manual4() = Patch("Manual", "Full Draw",
        mapOf("click" to 0.6f, "ua_513" to 1f, "ua_4" to 1f, "ua_223" to 1f, "ua_2" to 1f, "ua_135" to 1f, "ua_113" to 1f, "ua_1" to 1f, "la_16" to 1f, "la_513" to 1f, "la_8" to 1f, "la_4" to 1f, "la_223" to 1f, "la_2" to 1f, "la_135" to 1f, "la_113" to 1f, "la_1" to 1f, "perc" to 0f, "vibtype" to 1f, "vibdepth" to 0.8f, "rotspeed" to 1f, "drive" to 0.55f))

    private fun manual5() = Patch("Manual", "Combo",
        mapOf("model" to 0.333333343f, "ua_8" to 0f, "ua_4" to 0f, "la_8" to 0f, "la_4" to 0f, "vibtype" to 0.2f, "vibrate" to 0.7500002f, "vibdepth" to 0.7f, "tab2r" to 0.5f, "reedy" to 0.6f, "rotary" to 0f))

    private fun manual6() = Patch("Manual", "Cathedral",
        mapOf("model" to 0.6666667f, "ua_513" to 1f, "ua_4" to 0f, "la_16" to 1f, "la_8" to 1f, "la_4" to 0f, "perc" to 0f, "windsag" to 0.35f, "windnoise" to 0.15f, "flute" to 0.7f, "string" to 0.45f, "reed" to 0.3f, "mixture" to 0.6f, "chiff" to 0.45f, "tracker" to 0.3f, "rotary" to 0f, "attack" to 0.349999934f, "release" to 0.3000003f))

    private fun manual7() = Patch("Manual", "Harmonium",
        mapOf("model" to 1f, "ua_513" to 1f, "ua_8" to 0f, "ua_4" to 0f, "la_16" to 1f, "la_8" to 0f, "la_4" to 0f, "perc" to 0f, "windsag" to 0.5f, "tremrate" to 0.4000006f, "pressure" to 0.75f, "buzz" to 0.45f, "reedtrem" to 0.35f, "rotary" to 0f))

    private fun manual8() = Patch("Manual", "Drift",
        mapOf("ua_513" to 1f, "ua_4" to 0f, "ub_16" to 0f, "ub_513" to 0f, "ub_8" to 0.5f, "ub_4" to 0.625f, "ub_223" to 0.75f, "ub_2" to 1f, "ub_135" to 1f, "ub_113" to 1f, "ub_1" to 1f, "la_16" to 1f, "la_8" to 1f, "la_4" to 0f, "morphsrc" to 0.642857134f, "spray" to 0.45f, "sprayrate" to 0.2999996f, "spraywide" to 0.8f, "rotspeed" to 0.5f, "drive" to 0.25f, "lfo1rate" to 0.199999973f, "m1_src" to 0.642857134f, "m1_dst" to 0.0416666679f, "m1_amt" to 0.75f, "m2_src" to 0.785714269f, "m2_dst" to 0.416666657f, "m2_amt" to 0.3f))

    private val manual: List<Patch> by lazy { listOf(manual0(), manual1(), manual2(), manual3(), manual4(), manual5(), manual6(), manual7(), manual8()) }

    private fun cumulus0() = Patch("Cumulus", "Init", emptyMap())

    private fun cumulus1() = Patch("Cumulus", "Cirrus",
        mapOf("partials" to 0.433100015f, "tilt" to 0.466700017f, "bandwidth" to 0.5018f, "bwscale" to 0.24000001f, "bbandwidth" to 0.48330003f, "width" to 0.7f, "detune" to 0.14f, "cutoff" to 0.9229994f, "ampattack" to 0.7437999f, "amprelease" to 0.7819997f))

    private fun cumulus2() = Patch("Cumulus", "Choir",
        mapOf("partials" to 0.3386f, "tilt" to 0.5333f, "vowel" to 0.25f, "vowelamount" to 0.85f, "bandwidth" to 0.4203996f, "bbandwidth" to 0.4f, "bvowel" to 0.775f, "morphkey" to 0.65f, "width" to 0.8f, "drift" to 0.18f, "driftrate" to 0.384300023f, "spread" to 1f, "detune" to 0.18f, "cutoff" to 0.8732f, "ampattack" to 0.6914999f, "amprelease" to 0.7697998f))

    private fun cumulus3() = Patch("Cumulus", "Bell Cloud",
        mapOf("partials" to 0.212600008f, "tilt" to 0.6f, "comb" to 0.35f, "combperiod" to 0.2727f, "bandwidth" to 0.2822001f, "stretch" to 0.650000036f, "bbandwidth" to 0.533300042f, "bstretch" to 0.75f, "shimmer" to 0.2f, "spread" to 0f, "cutoff" to 0.9606998f, "filterenv" to 0.65f, "ampattack" to 0.15429996f, "ampdecay" to 0.905999959f, "ampsustain" to 0.25f, "amprelease" to 0.8875f))

    private fun cumulus4() = Patch("Cumulus", "Deep Wash",
        mapOf("partials" to 0.4961f, "tilt" to 0.2667f, "bandwidth" to 0.7889002f, "bwscale" to 0.359999985f, "btilt" to 0.3333f, "bbandwidth" to 0.1333f, "width" to 1f, "drift" to 0.28f, "driftrate" to 0.324799955f, "spread" to 1f, "detune" to 0.28f, "cutoff" to 0.828300059f, "ampattack" to 0.870600045f, "amprelease" to 0.8875f))

    private fun cumulus5() = Patch("Cumulus", "Glass Rain",
        mapOf("tilt" to 0.4f, "odd" to 0.75f, "bandwidth" to 0.46269986f, "btilt" to 0.7222f, "bbandwidth" to 0.5833f, "bodd" to 0.25f, "shimmer" to 0.55f, "shimmerint" to 1f, "width" to 0.9f, "detune" to 0.12f, "cutoff" to 0.9816002f, "ampattack" to 0.6346998f, "amprelease" to 0.8219002f, "lfo1rate" to 0.273599952f, "lfo1morph" to 0.8f))

    private fun cumulus6() = Patch("Cumulus", "Hollow",
        mapOf("partials" to 0.3071f, "tilt" to 0.4333f, "odd" to 1f, "comb" to 0.55f, "bandwidth" to 0.47480014f, "bbandwidth" to 0.45f, "bcomb" to 0.25f, "bodd" to 0.199999988f, "detune" to 0.1f, "cutoff" to 0.8523999f, "ampattack" to 0.756899953f, "amprelease" to 0.7931999f))

    private val cumulus: List<Patch> by lazy { listOf(cumulus0(), cumulus1(), cumulus2(), cumulus3(), cumulus4(), cumulus5(), cumulus6()) }

    private fun formulate0() = Patch("Formulate", "Init", emptyMap())

    private fun formulate1() = Patch("Formulate", "Pulse Lead",
        mapOf("duty" to 0.25f, "ampattack" to 0.07710003f, "ampdecay" to 0.594000041f, "ampsustain" to 0.7f, "mono" to 1f, "volume" to 0.4667f),
        mapOf("arp" to "0 4 7", "duty" to "", "formula" to "", "vol" to ""))

    private fun formulate2() = Patch("Formulate", "Arcade Bass",
        mapOf("sub" to 0.6f, "framerate" to 0.7704999f, "ampattack" to 0.07710003f, "ampdecay" to 0.5301999f, "ampsustain" to 0.5f, "amprelease" to 0.336800128f, "mono" to 1f, "volume" to 0.599999964f),
        mapOf("arp" to "0 0 0 12", "duty" to "", "formula" to "", "vol" to "255 200 | 160"))

    private fun formulate3() = Patch("Formulate", "Noise Hit",
        mapOf("wave" to 0.75f, "noiseshort" to 1f, "framerate" to 0.8552f, "ampattack" to 0f, "ampdecay" to 0.555000246f, "ampsustain" to 0f, "amprelease" to 0.312100083f),
        mapOf("arp" to "", "duty" to "", "formula" to "", "vol" to "255 190 120 70 40 20 8 0 |"))

    private fun formulate4() = Patch("Formulate", "Buzzsaw",
        mapOf("wave" to 0.5f, "bits" to 0.2857143f, "crush" to 0.430799842f, "cutoff" to 0.878500044f, "ampdecay" to 0.718099952f, "amprelease" to 0.5f, "volume" to 0.4667f),
        mapOf("arp" to "", "duty" to "", "formula" to "", "vol" to ""))

    private fun formulate5() = Patch("Formulate", "Formula Buzz",
        mapOf("wave" to 1f, "formula" to 1f, "a" to 0.627498031f, "cutoff" to 0.9288998f, "ampdecay" to 0.6488999f, "amprelease" to 0.4609996f, "volume" to 0.4f),
        mapOf("arp" to "", "duty" to "", "formula" to "t * (t >> 5 & a >> 4)", "vol" to ""))

    private fun formulate6() = Patch("Formulate", "Ring Chip",
        mapOf("formula" to 1f, "formulamode" to 0.5f, "timescale" to 0.6667003f, "framerate" to 0.663800061f, "ampdecay" to 0.687899947f, "ampsustain" to 0.6f, "amprelease" to 0.5f, "volume" to 0.4667f),
        mapOf("arp" to "0 7", "duty" to "", "formula" to "x * sin(t) >> 7", "vol" to ""))

    private fun formulate7() = Patch("Formulate", "Gated Grit",
        mapOf("duty" to 0.125f, "bits" to 0.714285731f, "formula" to 1f, "formulamode" to 0.75f, "framerate" to 0.9534001f, "ampattack" to 0.07710003f, "ampdecay" to 0.624199867f, "ampsustain" to 0.7f, "amprelease" to 0.406f, "volume" to 0.4667f),
        mapOf("arp" to "0 0 12 7", "duty" to "", "formula" to "t >> 9 & 1 ? 255 : 0", "vol" to ""))

    private val formulate: List<Patch> by lazy { listOf(formulate0(), formulate1(), formulate2(), formulate3(), formulate4(), formulate5(), formulate6(), formulate7()) }

    private fun pollen0() = Patch("Pollen", "Init", emptyMap())

    private fun pollen1() = Patch("Pollen", "Drift",
        mapOf("scan" to 0.505f, "spray" to 0.25f, "size" to 0.79520005f, "density" to 0.598100245f, "jitter" to 0.35f, "panspread" to 0.7f, "ampattack" to 0.7117999f, "amprelease" to 0.7985f))

    private fun pollen2() = Patch("Pollen", "Pollinate",
        mapOf("density" to 0.462800026f, "bloom" to 1f, "drift" to 0.35f, "mutate" to 0.35f, "panspread" to 0.9f, "ampattack" to 0.6346998f, "amprelease" to 0.8219002f))

    private fun pollen3() = Patch("Pollen", "Chord Dust",
        mapOf("spray" to 0.4f, "size" to 0.658800066f, "density" to 0.7509999f, "spread" to 0.5f, "scatter" to 0.5f, "panspread" to 0.8f, "amprelease" to 0.7328003f, "volume" to 0.4667f))

    private fun pollen4() = Patch("Pollen", "Slicer",
        mapOf("spray" to 0.8f, "snap" to 1f, "size" to 0.7563994f, "density" to 0.5562003f, "jitter" to 0.2f, "window" to 0.6666667f, "keytrack" to 0f, "ampattack" to 0.07709992f, "ampdecay" to 0.718099952f, "amprelease" to 0.525999844f, "volume" to 0.599999964f))

    private fun pollen5() = Patch("Pollen", "Live Hold",
        mapOf("source" to 1f, "position" to 0.1f, "spray" to 0.15f, "size" to 0.835600436f, "density" to 0.6315998f, "keytrack" to 0f, "ampattack" to 0.58949995f, "amprelease" to 0.7042001f, "dry" to 0.3f))

    private fun pollen6() = Patch("Pollen", "Eat Itself",
        mapOf("source" to 1f, "buffer" to 0.6f, "feedback" to 0.7368f, "scan" to 0.625f, "spray" to 0.5f, "size" to 0.8679002f, "density" to 0.683400154f, "keytrack" to 0f, "bloom" to 0.5f, "mutate" to 0.5f, "generations" to 0.2f, "bits" to 0.6f, "wobble" to 0.24f, "ampattack" to 0.6914999f, "amprelease" to 0.8219002f, "volume" to 0.4667f))

    private val pollen: List<Patch> by lazy { listOf(pollen0(), pollen1(), pollen2(), pollen3(), pollen4(), pollen5(), pollen6()) }

    private fun brazen0() = Patch("Brazen", "Init", emptyMap())

    private fun brazen1() = Patch("Brazen", "Tuba",
        mapOf("size" to 0.03f, "bell" to 0.922222257f, "lipdamp" to 0.444444418f, "pressure" to 0.75f, "breath" to 0f, "bite" to 0.15f, "brass" to 0.25f, "attack" to 0.551070869f, "release" to 0.622157753f, "vibrato" to 0.0333333351f, "volume" to 1f))

    private fun brazen2() = Patch("Brazen", "Bass Trombone",
        mapOf("size" to 0.16f, "bell" to 0.7888889f, "lipdamp" to 0.5f, "pressure" to 0.72f, "breath" to 0.03f, "bite" to 0.3f, "attack" to 0.479777545f, "vibrato" to 0.06666667f, "glide" to 0.09f, "volume" to 0.9666667f))

    private fun brazen3() = Patch("Brazen", "Trombone",
        mapOf("size" to 0.3f, "bell" to 0.6777778f, "lipdamp" to 0.5555556f, "pressure" to 0.78f, "breath" to 0.04f, "brass" to 0.58f, "attack" to 0.43367663f, "vibrato" to 0.0833333358f, "glide" to 0.12f, "volume" to 0.8666666f))

    private fun brazen4() = Patch("Brazen", "Horn",
        mapOf("size" to 0.34f, "bell" to 0.8333334f, "lipdamp" to 0.4111111f, "breath" to 0.05f, "bite" to 0.12f, "brass" to 0.28f, "players" to 0.333333343f, "spread" to 0.1f, "lock" to 0.75f, "width" to 0.5f, "attack" to 0.6043044f, "release" to 0.655539453f, "vibrato" to 0.1f, "volume" to 0.6666667f))

    private fun brazen5() = Patch("Brazen", "Flugel",
        mapOf("size" to 0.55f, "bell" to 0.7444445f, "lipdamp" to 0.444444418f, "pressure" to 0.66f, "breath" to 0.05f, "bite" to 0.2f, "brass" to 0.32f, "vibrato" to 0.0833333358f, "volume" to 0.900000036f))

    private fun brazen6() = Patch("Brazen", "Cornet",
        mapOf("size" to 0.72f, "bell" to 0.6333333f, "pressure" to 0.76f, "breath" to 0.06f, "brass" to 0.5f, "attack" to 0.392030418f, "vibrato" to 0.116666667f, "volume" to 0.8333333f))

    private fun brazen7() = Patch("Brazen", "Trumpet",
        mapOf("size" to 0.95f, "bell" to 0.5888889f, "lipdamp" to 0.6333333f, "pressure" to 0.9f, "breath" to 0.08f, "bite" to 0.6f, "brass" to 0.78f, "attack" to 0.28169933f, "vibrato" to 0.13333334f, "vibratodelay" to 0.25f, "volume" to 0.8f))

    private fun brazen8() = Patch("Brazen", "Piccolo",
        mapOf("size" to 1f, "bell" to 0.655555546f, "lipdamp" to 0.7222222f, "pressure" to 0.98f, "breath" to 0.1f, "bite" to 0.75f, "brass" to 0.9f, "attack" to 0.200686663f, "vibrato" to 0.1f, "volume" to 0.8333333f))

    private fun brazen9() = Patch("Brazen", "Straight Mute",
        mapOf("size" to 0.9f, "bell" to 0.544444442f, "mute" to 0.333333343f, "mutetone" to 0.7f, "pressure" to 0.85f, "breath" to 0.09f, "bite" to 0.6f, "brass" to 0.7f, "attack" to 0.30102998f, "volume" to 1f))

    private fun brazen10() = Patch("Brazen", "Cup Mute",
        mapOf("size" to 0.82f, "bell" to 0.7666667f, "mute" to 0.6666667f, "mutetone" to 0.3f, "pressure" to 0.7f, "breath" to 0.06f, "bite" to 0.3f, "brass" to 0.42f, "attack" to 0.382042676f, "volume" to 0.766666651f))

    private fun brazen11() = Patch("Brazen", "Harmon",
        mapOf("size" to 0.95f, "bell" to 0.5f, "mute" to 1f, "mutetone" to 0.65f, "pressure" to 0.86f, "breath" to 0.12f, "bite" to 0.55f, "brass" to 0.62f, "attack" to 0.3333333f, "volume" to 1f))

    private fun brazen12() = Patch("Brazen", "Section",
        mapOf("size" to 0.55f, "bell" to 0.611111164f, "pressure" to 0.8f, "breath" to 0.05f, "brass" to 0.6f, "players" to 1f, "spread" to 0.233333334f, "scatter" to 0.183333337f, "lock" to 0.88f, "drift" to 0.16f, "width" to 0.85f, "attack" to 0.450727522f, "volume" to 0.413333327f))

    private fun brazen13() = Patch("Brazen", "Shambles",
        mapOf("size" to 0.55f, "bell" to 0.611111164f, "pressure" to 0.8f, "breath" to 0.06f, "brass" to 0.6f, "players" to 1f, "spread" to 0.8f, "scatter" to 0.7083333f, "lock" to 0.03f, "drift" to 0.76f, "width" to 1f, "attack" to 0.5146893f, "volume" to 0.4f))

    private fun brazen14() = Patch("Brazen", "Growl",
        mapOf("size" to 0.86f, "bell" to 0.566666663f, "lipdamp" to 0.7f, "pressure" to 0.92f, "breath" to 0.07f, "bite" to 0.65f, "brass" to 0.85f, "growl" to 0.75f, "growlrate" to 0.5775205f, "attack" to 0.3180808f, "drive" to 0.28f, "volume" to 0.6666667f))

    private fun brazen15() = Patch("Brazen", "Fanfare",
        mapOf("size" to 1f, "bell" to 0.6333333f, "lipdamp" to 0.7f, "pressure" to 0.93f, "breath" to 0.07f, "bite" to 0.8f, "brass" to 1f, "players" to 0.333333343f, "spread" to 0.15f, "lock" to 0.9f, "attack" to 0.232989982f, "vibrato" to 0.06666667f, "volume" to 0.733333349f))

    private val brazen: List<Patch> by lazy { listOf(brazen0(), brazen1(), brazen2(), brazen3(), brazen4(), brazen5(), brazen6(), brazen7(), brazen8(), brazen9(), brazen10(), brazen11(), brazen12(), brazen13(), brazen14(), brazen15()) }

    private fun timber0() = Patch("Timber", "Init", emptyMap())

    private fun timber1() = Patch("Timber", "Clarinet",
        mapOf("breath" to 0.1f, "keys" to 0.2f, "attack" to 0.3333333f))

    private fun timber2() = Patch("Timber", "Bass Clarinet",
        mapOf("body" to 0.318022f, "lattice" to 0.401896f, "embouchure" to 0.3846154f, "pressure" to 0.6923077f, "breath" to 0.16f, "tongue" to 0.6f, "keys" to 0.35f))

    private fun timber3() = Patch("Timber", "Alto Sax",
        mapOf("bore" to 1f, "body" to 0.5439642f, "lattice" to 0.3667258f, "embouchure" to 0.3846154f, "pressure" to 0.7307693f, "breath" to 0.2f, "tongue" to 0.75f, "keys" to 0.3f, "attack" to 0.2916871f, "vibrato" to 0.15f))

    private fun timber4() = Patch("Timber", "Oboe",
        mapOf("family" to 0.5f, "bore" to 1f, "body" to 0.7287489f, "lattice" to 0.558787048f, "embouchure" to 0.6923077f, "pressure" to 0.7307693f, "breath" to 0.08f, "tongue" to 0.8f, "keys" to 0.2f, "attack" to 0.259383738f, "vibrato" to 0.2f))

    private fun timber5() = Patch("Timber", "Bassoon",
        mapOf("family" to 0.5f, "bore" to 1f, "body" to 0.2361563f, "lattice" to 0.282834977f, "embouchure" to 0.538461566f, "pressure" to 0.6923077f, "keys" to 0.4f, "attack" to 0.365636677f))

    private fun timber6() = Patch("Timber", "Flute",
        mapOf("family" to 1f, "bore" to 1f, "body" to 0.769748747f, "lattice" to 0.514213145f, "pressure" to 0.615384638f, "breath" to 0.45f, "tongue" to 0.35f, "keys" to 0.15f, "attack" to 0.43367663f, "vibrato" to 0.18f))

    private fun timber7() = Patch("Timber", "Pan Pipe",
        mapOf("family" to 1f, "body" to 0.6671323f, "lattice" to 0.665089548f, "pressure" to 0.538461566f, "breath" to 0.6f, "jet" to 0.350000024f, "aim" to 0.5625f, "tongue" to 0.2f, "attack" to 0.492373765f))

    private fun timber8() = Patch("Timber", "Stopped Wood",
        mapOf("body" to 0.461817741f, "lattice" to 0.112317182f, "holes" to 0.9f, "answer" to 0.7f, "embouchure" to 0.3076923f, "pressure" to 0.7692308f, "breath" to 0.3f, "tongue" to 0.5f, "attack" to 0.46598f, "drive" to 0.2f))

    private fun timber9() = Patch("Timber", "Forked",
        mapOf("family" to 0.5f, "bore" to 1f, "lattice" to 0.462756425f, "fingering" to 0.8f, "below" to 0.55f, "answer" to 0.849999964f, "embouchure" to 0.3846154f, "pressure" to 0.7692308f, "breath" to 0.25f, "tongue" to 0.6f, "flutter" to 0.35f, "attack" to 0.43367663f))

    private val timber: List<Patch> by lazy { listOf(timber0(), timber1(), timber2(), timber3(), timber4(), timber5(), timber6(), timber7(), timber8(), timber9()) }

    private fun cipher0() = Patch("Cipher", "Init", emptyMap())

    private fun cipher1() = Patch("Cipher", "Classic",
        mapOf("sibilance" to 0.5f, "mix" to 0.4f, "detune" to 0.25f, "sub" to 0.25f))

    private fun cipher2() = Patch("Cipher", "Choir",
        mapOf("bands" to 0.6666667f, "attack" to 0.350000173f, "release" to 0.5f, "smear" to 0.62f, "wave a" to 0.5f, "mix" to 0.5f, "detune" to 0.5f))

    private fun cipher3() = Patch("Cipher", "Backwards",
        mapOf("bands" to 0.5555556f, "remap" to 0.2f, "sibilance" to 0.2f, "wave b" to 0.25f, "mix" to 0.5f))

    private fun cipher4() = Patch("Cipher", "Shuffled",
        mapOf("bands" to 0.444444448f, "release" to 0.399999946f, "smear" to 0.7f, "remap" to 0.8f, "remapamt" to 0.8f, "seed" to 0.225806445f))

    private fun cipher5() = Patch("Cipher", "Held Vowel",
        mapOf("bands" to 0.6666667f, "freeze" to 1f, "frzdecay" to 0.8999997f, "wave a" to 0.5f, "mix" to 0.3f, "detune" to 0.4f))

    private fun cipher6() = Patch("Cipher", "Talkbox",
        mapOf("bands" to 0.444444448f, "sibilance" to 0.45f, "track" to 1f, "trackglide" to 0.25000006f, "wave a" to 0.25f, "pw" to 0.299999982f, "sub" to 0.35f))

    private fun cipher7() = Patch("Cipher", "Inverted",
        mapOf("bands" to 0.5555556f, "role" to 1f, "attack" to 0.09999997f, "release" to 0.120000809f, "wave a" to 0.25f, "mix" to 0f))

    private fun cipher8() = Patch("Cipher", "Runaway",
        mapOf("smear" to 0.25f, "gate" to 0.15f, "feedback" to 0.62f, "fbtone" to 0.35f, "drive" to 0.35f))

    private val cipher: List<Patch> by lazy { listOf(cipher0(), cipher1(), cipher2(), cipher3(), cipher4(), cipher5(), cipher6(), cipher7(), cipher8()) }

    private fun filament0() = Patch("Filament", "Init", emptyMap())

    private fun filament1() = Patch("Filament", "Nylon",
        mapOf("position" to 0.35f, "grit" to 0.6f, "length" to 0.120000787f, "sustain" to 0.78f, "tone" to 0.4f, "detune" to 0.1f, "couple" to 0.3f, "size" to 0.55f, "bodymix" to 0.45f))

    private fun filament2() = Patch("Filament", "Steel",
        mapOf("exciter" to 0.2f, "position" to 0.120000005f, "sustain" to 0.88f, "tone" to 0.62f, "stiffness" to 0.18f, "detune" to 0.12f, "couple" to 0.4f, "size" to 0.4f, "bodymix" to 0.4f, "drive" to 0.12f))

    private fun filament3() = Patch("Filament", "Hammered",
        mapOf("exciter" to 0.4f, "hardness" to 0.55f, "length" to 0.04999988f, "sustain" to 0.93f, "tone" to 0.5f, "stiffness" to 0.55f, "stages" to 1f, "tension" to 0.3f, "couple" to 0.5f, "sympathy" to 1f, "symtune" to 1f, "symlevel" to 0.25f, "size" to 0.3f, "bodymix" to 0.3f))

    private fun filament4() = Patch("Filament", "Bowed",
        mapOf("exciter" to 0.6f, "position" to 0.18f, "pressure" to 0.55f, "speed" to 0.45f, "grit" to 0.35f, "sustain" to 0.9f, "tone" to 0.4f, "bodymix" to 0.4f, "velocity" to 0.4f))

    private fun filament5() = Patch("Filament", "Blown",
        mapOf("exciter" to 0.8f, "pressure" to 0.6f, "grit" to 0.7f, "sustain" to 0.86f, "tone" to 0.3f, "stiffness" to 0.1f, "size" to 0.7f, "bodymix" to 0.5f))

    private fun filament6() = Patch("Filament", "Sympathy",
        mapOf("tone" to 0.5f, "sympathy" to 1f, "symtune" to 0.8f, "symlevel" to 0.7f, "symsustain" to 0.97f, "symwide" to 0.8f, "on release" to 0f))

    private fun filament7() = Patch("Filament", "Prepared",
        mapOf("exciter" to 0.4f, "sustain" to 0.9f, "tone" to 0.6f, "stiffness" to 0.3f, "stages" to 0.75f, "damper at" to 0.33f, "damper" to 0.4f, "rattle" to 0.55f, "rattle at" to 0.2f, "drive" to 0.2f))

    private fun filament8() = Patch("Filament", "Spoken To",
        mapOf("exciter" to 1f, "in gain" to 0.5f, "sustain" to 0.92f, "tone" to 0.55f, "sympathy" to 1f, "symtune" to 0.4f, "symlevel" to 0.4f, "bodymix" to 0.3f))

    private fun filament9() = Patch("Filament", "Wire",
        mapOf("exciter" to 0.2f, "position" to 0.05f, "sustain" to 0.99f, "tone" to 0.85f, "stiffness" to 0.85f, "stages" to 1f, "tension" to 0.8f, "rattle" to 0.3f, "detune" to 0.6f, "couple" to 0.8f, "drive" to 0.3f))

    private val filament: List<Patch> by lazy { listOf(filament0(), filament1(), filament2(), filament3(), filament4(), filament5(), filament6(), filament7(), filament8(), filament9()) }

    private fun hexbeat0() = Patch("Hexbeat", "Init", emptyMap())

    private fun hexbeat1() = Patch("Hexbeat", "Tight",
        mapOf("kick_tune" to 0.409931868f, "kick_decay" to 0.3317472f, "kick_punch" to 0.72f, "snare_decay" to 0.292238653f, "snare_snappy" to 0.72f, "tom_decay" to 0.3766126f, "hat_closed_decay" to 0.25292173f, "hat_open_decay" to 0.3436954f, "cym_decay" to 0.502073348f, "ride_decay" to 0.405683875f, "clap_decay" to 0.396240622f, "bell_decay" to 0.462756425f, "accent" to 0.7f))

    private fun hexbeat2() = Patch("Hexbeat", "Boomy",
        mapOf("kick_tune" to 0.203965187f, "kick_decay" to 0.798193336f, "kick_punch" to 0.35f, "kick_level" to 0.95f, "snare_decay" to 0.598104f, "snare_snappy" to 0.4f, "tom_lo_tune" to 0.151433319f, "tom_mid_tune" to 0.181639671f, "tom_hi_tune" to 0.238944024f, "tom_decay" to 0.7495728f, "hat_open_decay" to 0.598104f))

    private fun hexbeat3() = Patch("Hexbeat", "Trashy",
        mapOf("snare_snappy" to 0.9f, "snare_tone" to 0.7987669f, "hat_tune" to 0.792481244f, "hat_closed_decay" to 0.5372436f, "hat_open_decay" to 0.7334516f, "hat_tone" to 0.8784545f, "hat_level" to 0.7f, "cym_decay" to 0.8562011f, "cym_tone" to 0.8516409f, "clap_tone" to 0.7039877f, "accent" to 0.9f))

    private fun hexbeat4() = Patch("Hexbeat", "Cardboard",
        mapOf("kick_tune" to 0.5625539f, "kick_decay" to 0.259024829f, "kick_punch" to 0.85f, "snare_tune" to 0.6421988f, "snare_decay" to 0.196207985f, "snare_snappy" to 0.25f, "snare_tone" to 0.277738333f, "tom_decay" to 0.257400155f, "hat_closed_decay" to 0.0960306451f, "hat_open_decay" to 0.08757933f, "hat_tone" to 0.127216786f, "hat_level" to 0.42f, "cym_decay" to 0.231378213f, "cym_level" to 0.3f, "ride_decay" to 0.206648976f, "ride_level" to 0.35f, "rim_tune" to 0.341763f, "clave_tune" to 0.185339361f))

    private fun hexbeat5() = Patch("Hexbeat", "Deep",
        mapOf("kick_tune" to 0.06674396f, "kick_decay" to 0.634828448f, "snare_tune" to 0.128035f, "snare_decay" to 0.550335765f, "snare_tone" to 0.344010174f, "tom_lo_tune" to 0.0272346623f, "tom_mid_tune" to 0.044907365f, "tom_hi_tune" to 0.06648219f, "tom_decay" to 0.6885239f, "hat_tune" to 0.263034433f, "hat_tone" to 0.3062702f, "cym_tone" to 0.174435332f, "bell_tune" to 0.170518458f, "clave_tune" to 0.238944024f))

    private fun hexbeat6() = Patch("Hexbeat", "Glassy",
        mapOf("kick_decay" to 0.446926683f, "hat_tune" to 0.9437626f, "hat_closed_decay" to 0.32740885f, "hat_tone" to 0.738140464f, "hat_level" to 0.34f, "cym_decay" to 0.8294822f, "cym_tone" to 0.7304227f, "cym_level" to 0.28f, "ride_decay" to 0.8854693f, "ride_level" to 0.34f, "rim_tune" to 0.9571323f, "rim_level" to 0.85f, "bell_tune" to 0.969299734f, "bell_decay" to 0.9522318f, "bell_level" to 1f, "clave_tune" to 0.9573967f, "clave_level" to 0.95f))

    private fun hexbeat7() = Patch("Hexbeat", "Clatter",
        mapOf("kick_decay" to 0.279114425f, "kick_punch" to 0.9f, "snare_decay" to 0.156891063f, "snare_snappy" to 0.85f, "tom_decay" to 0.231817588f, "hat_closed_decay" to 0.0608604439f, "hat_open_decay" to 0.156891063f, "cym_decay" to 0.186804339f, "cym_level" to 0.35f, "ride_decay" to 0.149725839f, "clap_decay" to 0.211999208f, "rim_tune" to 0.8349093f, "rim_level" to 0.9f, "bell_tune" to 0.7762705f, "bell_decay" to 0.3667258f, "bell_level" to 0.8f, "clave_tune" to 0.7882907f, "clave_level" to 0.85f, "accent" to 0.85f))

    private fun hexbeat8() = Patch("Hexbeat", "Handclap",
        mapOf("kick_tune" to 0.289475143f, "kick_decay" to 0.5032146f, "kick_level" to 1f, "snare_decay" to 0.3436954f, "snare_snappy" to 0.3f, "snare_level" to 0.28f, "hat_closed_decay" to 0.2731587f, "hat_open_decay" to 0.292238653f, "hat_level" to 0.38f, "cym_level" to 0.25f, "ride_level" to 0.3f, "clap_decay" to 0.981499851f, "clap_tone" to 0.108723558f, "clap_level" to 1f, "rim_level" to 0.4f, "bell_level" to 0.35f))

    private fun hexbeat9() = Patch("Hexbeat", "Wooden",
        mapOf("kick_tune" to 0.489825249f, "kick_decay" to 0.3618988f, "kick_punch" to 0.8f, "snare_tune" to 0.5403673f, "snare_decay" to 0.263193548f, "snare_snappy" to 0.3f, "snare_tone" to 0.402466118f, "tom_decay" to 0.3230075f, "hat_closed_decay" to 0.183609977f, "hat_open_decay" to 0.196207985f, "hat_tone" to 0.398916781f, "cym_level" to 0.18f, "ride_level" to 0.28f, "rim_tune" to 0.52645576f, "rim_level" to 0.85f, "bell_level" to 0.3f, "clave_tune" to 0.464807659f, "clave_level" to 0.8f))

    private fun hexbeat10() = Patch("Hexbeat", "Enormous",
        mapOf("kick_tune" to 0.147971049f, "kick_decay" to 0.9395091f, "kick_punch" to 0.25f, "kick_level" to 1f, "snare_decay" to 0.8404277f, "snare_snappy" to 0.5f, "snare_level" to 0.95f, "tom_decay" to 0.934392631f, "tom_level" to 0.95f, "hat_open_decay" to 0.92551285f, "cym_decay" to 0.982877851f, "cym_level" to 0.7f, "ride_decay" to 0.9471572f, "ride_level" to 0.7f, "clap_decay" to 0.951838732f, "accent" to 0.5f))

    private val hexbeat: List<Patch> by lazy { listOf(hexbeat0(), hexbeat1(), hexbeat2(), hexbeat3(), hexbeat4(), hexbeat5(), hexbeat6(), hexbeat7(), hexbeat8(), hexbeat9(), hexbeat10()) }

    private fun genesis0() = Patch("Genesis", "Init", emptyMap())

    private fun genesis1() = Patch("Genesis", "Boom",
        mapOf("kicktune" to 0.165956259f, "kickdecay" to 0.846469045f, "kickpunch" to 0.4f, "kicksweep" to 0.7835365f, "kickclick" to 0.2f, "kicklevel" to 0.766666651f, "snaredecay" to 0.403056055f, "hatclosed" to 0.436294526f, "comp" to 0.15f, "duck" to 0.1f))

    private fun genesis2() = Patch("Genesis", "Pump",
        mapOf("kicktune" to 0.348614573f, "kickdecay" to 0.644561648f, "kickpunch" to 0.7f, "hatopen" to 0.7154089f, "crashdecay" to 0.796205f, "comp" to 0.9f, "compattack" to 0.261648029f, "comprelease" to 0.458013535f, "duck" to 0.9f, "drive" to 0.3f))

    private fun genesis3() = Patch("Genesis", "Tight",
        mapOf("kickdecay" to 0.420767367f, "kickpunch" to 0.85f, "kicksweep" to 0.375803649f, "kickclick" to 0.6f, "snaredecay" to 0.218104288f, "snaresnap" to 0.75f, "clapdecay" to 0.341982722f, "tomdecay" to 0.375803649f, "hatclosed" to 0.2483927f, "hatopen" to 0.401640832f, "crashdecay" to 0.442219973f, "ridedecay" to 0.368329972f, "accent" to 0.7f, "comp" to 0.5f, "compattack" to 0.130824015f, "comprelease" to 0.2808297f))

    private fun genesis4() = Patch("Genesis", "Clicky",
        mapOf("kicktune" to 0.6000712f, "kickdecay" to 0.312854439f, "kickpunch" to 0.95f, "kicksweep" to 0.0912126f, "kickclick" to 1f, "kickdrive" to 0.45f, "snaretune" to 0.5757166f, "snaredecay" to 0.184951782f, "snaresnap" to 0.85f, "rimdecay" to 0.203795046f, "hatclosed" to 0.187901825f, "drive" to 0.3f))

    private fun genesis5() = Patch("Genesis", "Dirty",
        mapOf("kickdecay" to 0.606911957f, "kickdrive" to 0.75f, "snaresnap" to 0.7f, "snaretone" to 0.7f, "hattone" to 0.8394416f, "crashtone" to 0.7737056f, "comp" to 0.65f, "drive" to 0.7f, "volume" to 0.900000036f))

    private fun genesis6() = Patch("Genesis", "Deep",
        mapOf("kicktune" to 0.0298465546f, "kickdecay" to 0.754954159f, "kicksweep" to 0.8615228f, "snaretune" to 0.09782865f, "snaredecay" to 0.5637914f, "snaretone" to 0.3f, "tomlotune" to 0.07916309f, "tommidtune" to 0.105739586f, "tomhitune" to 0.155170068f, "tomdecay" to 0.7835365f, "tombend" to 0.6f, "hattune" to 0.296149284f, "hattone" to 0.414083064f, "crashtone" to 0.262314022f, "belltune" to 0.203114f, "comp" to 0.45f, "comprelease" to 0.8228162f, "duck" to 0.55f))

    private fun genesis7() = Patch("Genesis", "Cymbals",
        mapOf("kicklevel" to 0.5f, "snarelevel" to 0.4f, "hatopen" to 0.9033108f, "hattone" to 0.8982444f, "hatlevel" to 0.6333333f, "crashdecay" to 0.974417448f, "crashtone" to 0.8982444f, "crashlevel" to 0.6666667f, "ridedecay" to 0.9463949f, "ridetone" to 0.8394416f, "ridebell" to 0.85f, "ridelevel" to 0.6666667f, "comp" to 0.1f, "duck" to 0f))

    private fun genesis8() = Patch("Genesis", "Rimshot",
        mapOf("kickdecay" to 0.5366487f, "snaredecay" to 0.2754732f, "snaresnap" to 0.9f, "snarelevel" to 0.466666669f, "rimtune" to 0.9268219f, "rimdecay" to 0.646015f, "rimlevel" to 0.8666666f, "hatlevel" to 0.333333343f, "crashlevel" to 0.233333334f, "belltune" to 0.8784545f, "belldecay" to 0.8004371f, "belllevel" to 0.733333349f, "comp" to 0.75f, "compattack" to 0.207351163f, "comprelease" to 0.384475648f, "duck" to 0.12f))

    private fun genesis9() = Patch("Genesis", "Toms",
        mapOf("kickdecay" to 0.562381864f, "snarelevel" to 0.4f, "tomlotune" to 0.128035f, "tommidtune" to 0.205736712f, "tomhitune" to 0.292481244f, "tomdecay" to 0.9220137f, "tombend" to 1f, "tomlevel" to 0.8333333f, "hatlevel" to 0.299999982f, "crashlevel" to 0.266666681f, "ridelevel" to 0.266666681f, "duck" to 0.15f))

    private fun genesis10() = Patch("Genesis", "Drifting",
        mapOf("kickdecay" to 0.6614124f, "snaredecay" to 0.5187636f, "tomdecay" to 0.7154089f, "hatclosed" to 0.563705444f, "drift" to 1f, "accent" to 0.8f, "comp" to 0.15f, "compattack" to 0.7727632f, "comprelease" to 0.8228162f))

    private fun genesis11() = Patch("Genesis", "Handclap",
        mapOf("kickdecay" to 0.562381864f, "snaredecay" to 0.323977977f, "snarelevel" to 0.233333334f, "clapspread" to 0.9242793f, "clapdecay" to 0.9088101f, "claptone" to 0.331444919f, "claplevel" to 0.8666666f, "hatlevel" to 0.333333343f, "crashlevel" to 0.233333334f, "ridelevel" to 0.233333334f, "comp" to 0.3f, "comprelease" to 0.6456324f, "duck" to 0.65f))

    private fun genesis12() = Patch("Genesis", "Flattened",
        mapOf("kickdecay" to 0.5078814f, "kickpunch" to 0.8f, "snaredecay" to 0.365994662f, "hatclosed" to 0.375803649f, "comp" to 1f, "compattack" to 0.0344112255f, "comprelease" to 0.103645884f, "duck" to 0f, "drive" to 0.45f, "volume" to 0.8666666f))

    private val genesis: List<Patch> by lazy { listOf(genesis0(), genesis1(), genesis2(), genesis3(), genesis4(), genesis5(), genesis6(), genesis7(), genesis8(), genesis9(), genesis10(), genesis11(), genesis12()) }

    private fun resonance0() = Patch("Resonance", "Init", emptyMap())

    private fun resonance1() = Patch("Resonance", "Skins",
        mapOf("p00_tune" to 0.172899976f, "p00_decay" to 0.5197f, "p00_damp" to 0.55f, "p00_hit" to 0.2f, "p00_hard" to 0.35f, "p00_noise" to 0.35f, "p00_bend" to 0.3333f, "p00_level" to 0.666699946f, "p00_couple" to 0.2f, "p01_tune" to 0.439499617f, "p01_decay" to 0.477700174f, "p01_damp" to 0.6f, "p01_hit" to 0.45f, "p01_hard" to 0.6f, "p01_noise" to 0.6f, "p01_level" to 0.599999964f, "p01_pan" to 0.45f, "p02_damp" to 0.45f, "p02_hit" to 0.3f, "p02_pan" to 0.325f, "p03_tune" to 0.398599774f, "p03_decay" to 0.553200066f, "p03_damp" to 0.45f, "p03_hit" to 0.3f, "p04_tune" to 0.463300258f, "p04_decay" to 0.537199855f, "p04_damp" to 0.45f, "p04_hit" to 0.3f, "p04_pan" to 0.675f, "p05_kind" to 1f, "p05_tune" to 0.809899867f, "p05_decay" to 0.299100667f, "p05_damp" to 0.85f, "p05_hit" to 0.6f, "p05_hard" to 0.9f, "p05_noise" to 0.5f, "p05_level" to 0.4f, "p05_pan" to 0.625f, "p05_couple" to 0.6f, "p06_kind" to 1f, "p06_tune" to 0.7877001f, "p06_decay" to 0.7314001f, "p06_damp" to 0.5f, "p06_hit" to 0.6f, "p06_hard" to 0.85f, "p06_noise" to 0.4f, "p06_level" to 0.3333f, "p06_pan" to 0.375f, "p06_couple" to 0.7f, "p07_kind" to 0.4f, "p07_tune" to 0.6791999f, "p07_decay" to 0.8620001f, "p07_damp" to 0.35f, "p07_hit" to 0.5f, "p07_hard" to 0.7f, "p07_noise" to 0.3f, "p07_level" to 0.299999982f, "p07_pan" to 0.7f, "p07_couple" to 0.8f, "coupling" to 0.35f, "humanise" to 0.2f))

    private fun resonance2() = Patch("Resonance", "Woodshop",
        mapOf("p00_kind" to 0.2f, "p00_tune" to 0.261599869f, "p00_decay" to 0.683400452f, "p00_damp" to 0.25f, "p00_hit" to 0.28f, "p00_hard" to 0.6f, "p00_noise" to 0.05f, "p00_level" to 0.666699946f, "p01_kind" to 0.2f, "p01_tune" to 0.426599681f, "p01_decay" to 0.6352999f, "p01_damp" to 0.3f, "p01_hit" to 0.28f, "p01_hard" to 0.7f, "p01_noise" to 0.05f, "p01_pan" to 0.4f, "p02_kind" to 0.2f, "p02_tune" to 0.523199558f, "p02_decay" to 0.5934f, "p02_damp" to 0.35f, "p02_hit" to 0.28f, "p02_hard" to 0.75f, "p02_noise" to 0.05f, "p02_pan" to 0.6f, "p03_kind" to 0.6f, "p03_tune" to 0.628400147f, "p03_decay" to 0.421599865f, "p03_damp" to 0.5f, "p03_hit" to 0.5f, "p03_hard" to 0.9f, "p03_noise" to 0.1f, "p03_level" to 0.599999964f, "p04_kind" to 0.2f, "p04_tune" to 0.74999994f, "p04_decay" to 0.452000231f, "p04_hit" to 0.3f, "p04_hard" to 0.95f, "p04_noise" to 0.05f, "p04_pan" to 0.325f, "p05_kind" to 0.2f, "p05_tune" to 0.846600354f, "p05_decay" to 0.421599865f, "p05_damp" to 0.45f, "p05_hit" to 0.3f, "p05_hard" to 0.95f, "p05_noise" to 0.05f, "p05_pan" to 0.675f, "p06_tune" to 0.383199424f, "p06_decay" to 0.452000231f, "p06_damp" to 0.7f, "p06_hit" to 0.4f, "p06_noise" to 0.5f, "p06_level" to 0.4667f, "p07_kind" to 0.6f, "p07_tune" to 0.5483f, "p07_damp" to 0.3f, "p07_hit" to 0.5f, "p07_hard" to 0.8f, "p07_noise" to 0.05f, "p07_level" to 0.4667f, "p07_couple" to 0.5f, "modes" to 0.2f, "coupling" to 0.2f, "humanise" to 0.25f))

    private fun resonance3() = Patch("Resonance", "Foundry",
        mapOf("p00_kind" to 1f, "p00_tune" to 0.3668001f, "p00_decay" to 0.805900037f, "p00_damp" to 0.25f, "p00_hit" to 0.33f, "p00_hard" to 0.85f, "p00_noise" to 0.15f, "p00_drive" to 0.25f, "p00_level" to 0.666699946f, "p01_kind" to 1f, "p01_tune" to 0.563600242f, "p01_decay" to 0.8363f, "p01_damp" to 0.2f, "p01_hit" to 0.4f, "p01_hard" to 0.9f, "p01_noise" to 0.1f, "p01_pan" to 0.35f, "p01_couple" to 0.8f, "p02_kind" to 0.4f, "p02_tune" to 0.5142f, "p02_decay" to 0.904000163f, "p02_damp" to 0.15f, "p02_hit" to 0.45f, "p02_hard" to 0.8f, "p02_pan" to 0.65f, "p02_couple" to 0.9f, "p03_kind" to 0.8f, "p03_tune" to 0.426599681f, "p03_decay" to 0.951999962f, "p03_damp" to 0.1f, "p03_hit" to 0.5f, "p03_hard" to 0.7f, "p03_noise" to 0.1f, "p03_level" to 0.4667f, "p03_couple" to 0.9f, "p04_kind" to 0.6f, "p04_tune" to 0.4951002f, "p04_decay" to 0.768600047f, "p04_damp" to 0.3f, "p04_hit" to 0.5f, "p04_hard" to 0.9f, "p04_noise" to 0.1f, "p04_pan" to 0.425f, "p05_kind" to 1f, "p05_tune" to 0.728700042f, "p05_decay" to 0.683400452f, "p05_damp" to 0.35f, "p05_hard" to 0.95f, "p05_pan" to 0.575f, "p06_kind" to 0.4f, "p06_tune" to 0.809899867f, "p06_decay" to 0.7844998f, "p06_damp" to 0.3f, "p06_hit" to 0.5f, "p06_hard" to 0.9f, "p06_noise" to 0.25f, "p06_level" to 0.4f, "p06_pan" to 0.725f, "p07_kind" to 0.8f, "p07_tune" to 0.628400147f, "p07_decay" to 0.9776999f, "p07_damp" to 0.08f, "p07_hit" to 0.55f, "p07_hard" to 0.6f, "p07_noise" to 0.05f, "p07_level" to 0.3333f, "p07_couple" to 1f, "modes" to 0.8f, "coupling" to 0.75f, "volume" to 0.5333f))

    private fun resonance4() = Patch("Resonance", "Glassware",
        mapOf("p00_kind" to 0.8f, "p00_tune" to 0.4743998f, "p00_decay" to 0.921599865f, "p00_damp" to 0.1f, "p00_hit" to 0.5f, "p00_hard" to 0.6f, "p00_noise" to 0.05f, "p00_level" to 0.599999964f, "p00_couple" to 0.8f, "p01_kind" to 0.8f, "p01_tune" to 0.57100004f, "p01_decay" to 0.904000163f, "p01_damp" to 0.12f, "p01_hit" to 0.5f, "p01_hard" to 0.65f, "p01_noise" to 0.05f, "p01_pan" to 0.375f, "p01_couple" to 0.8f, "p02_kind" to 0.8f, "p02_tune" to 0.639499962f, "p02_decay" to 0.884300053f, "p02_damp" to 0.14f, "p02_hit" to 0.5f, "p02_hard" to 0.7f, "p02_noise" to 0.05f, "p02_pan" to 0.625f, "p02_couple" to 0.8f, "p03_kind" to 0.6f, "p03_tune" to 0.7092999f, "p03_decay" to 0.805900037f, "p03_damp" to 0.2f, "p03_hit" to 0.5f, "p03_hard" to 0.8f, "p03_noise" to 0.1f, "p03_pan" to 0.3f, "p03_couple" to 0.7f, "p04_kind" to 0.6f, "p04_tune" to 0.7788f, "p04_decay" to 0.7844998f, "p04_damp" to 0.22f, "p04_hit" to 0.5f, "p04_hard" to 0.85f, "p04_noise" to 0.1f, "p04_pan" to 0.7f, "p04_couple" to 0.7f, "p05_kind" to 0.4f, "p05_tune" to 0.8576002f, "p05_decay" to 0.7509996f, "p05_damp" to 0.3f, "p05_hit" to 0.45f, "p05_hard" to 0.9f, "p05_noise" to 0.15f, "p05_level" to 0.4f, "p05_couple" to 0.6f, "p06_tune" to 0.2745001f, "p06_decay" to 0.537199855f, "p06_damp" to 0.6f, "p06_hit" to 0.25f, "p06_hard" to 0.4f, "p06_noise" to 0.4f, "p07_kind" to 1f, "p07_tune" to 0.9314995f, "p07_decay" to 0.6529f, "p07_hit" to 0.4f, "p07_hard" to 0.95f, "p07_level" to 0.3333f, "p07_couple" to 0.9f, "modes" to 1f, "coupling" to 0.9f, "humanise" to 0.1f, "volume" to 0.5f))

    private val resonance: List<Patch> by lazy { listOf(resonance0(), resonance1(), resonance2(), resonance3(), resonance4()) }

    private fun dice0() = Patch("Dice", "Init", emptyMap())

    private fun dice1() = Patch("Dice", "Straight", emptyMap())

    private fun dice2() = Patch("Dice", "Nudge",
        mapOf("gate" to 0.9f, "swap" to 0.1f, "reverse" to 0.08f))

    private fun dice3() = Patch("Dice", "Broken",
        mapOf("slices" to 0.714285731f, "gate" to 0.7f, "swap" to 0.5f, "reverse" to 0.3f, "stutter" to 0.15f, "drop" to 0.08f))

    private fun dice4() = Patch("Dice", "Fill",
        mapOf("cut" to 1f, "slices" to 1f, "gate" to 0.5f, "swap" to 0.3f, "stutter" to 0.6f, "stutterdiv" to 0.6666667f, "jump" to 0.35f, "drive" to 0.2f, "volume" to 0.5667f))

    private fun dice5() = Patch("Dice", "Held",
        mapOf("gate" to 0.85f, "swap" to 0.4f, "reverse" to 0.25f, "stutter" to 0.2f, "hold" to 1f, "seed" to 0.174603179f))

    private fun dice6() = Patch("Dice", "Dust",
        mapOf("cut" to 1f, "slices" to 1f, "gate" to 0.25f, "swap" to 0.35f, "reverse" to 0.2f, "drop" to 0.3f, "cutoff" to 0.655900061f, "resonance" to 0.15f, "volume" to 0.5333f))

    private val dice: List<Patch> by lazy { listOf(dice0(), dice1(), dice2(), dice3(), dice4(), dice5(), dice6()) }

    private fun mosaic0() = Patch("Mosaic", "Init", emptyMap())

    private fun mosaic1() = Patch("Mosaic", "Soft Pad",
        mapOf("keyfade" to 0.25f, "velfade" to 0.3125f, "loop" to 1f, "a_attack" to 0.6945378f, "a_decay" to 0.81962353f, "a_sustain" to 0.9f, "a_release" to 0.762373149f, "f_freq" to 0.747679353f, "f_env" to 0.6f))

    private fun mosaic2() = Patch("Mosaic", "Cloud",
        mapOf("grain" to 1f, "grate" to 0.5375f, "gsize" to 0.7781513f, "gdensity" to 0.6037341f, "gspray" to 0.25f, "gpitch" to 0.008333334f, "a_attack" to 0.636016965f, "a_release" to 0.79919f, "m01_src" to 0.166666672f, "m01_dest" to 0.266666681f, "m01_depth" to 0.8f))

    private fun mosaic3() = Patch("Mosaic", "Shimmer",
        mapOf("grain" to 1f, "grate" to 0.5125f, "gsize" to 0.422549f, "gdensity" to 0.887415648f, "gspray" to 0.5f, "gpitch" to 0.5f, "a_attack" to 0.5752575f, "a_release" to 0.81962353f, "l1_rate" to 0.361190557f, "m01_src" to 0.9166667f, "m01_dest" to 0.266666681f, "m01_depth" to 0.625f, "m02_src" to 0.25f, "m02_dest" to 0.6f, "m02_depth" to 0.75f))

    private fun mosaic4() = Patch("Mosaic", "Scan Layers",
        mapOf("scan" to 0.2f, "scanamt" to 1f, "velfade" to 0.46875f, "a_release" to 0.618813455f, "m01_src" to 0.166666672f, "m01_dest" to 0.13333334f, "m01_depth" to 0.9f))

    private fun mosaic5() = Patch("Mosaic", "Backwards",
        mapOf("start" to 0.99f, "reverse" to 1f, "a_attack" to 0.5440228f))

    private val mosaic: List<Patch> by lazy { listOf(mosaic0(), mosaic1(), mosaic2(), mosaic3(), mosaic4(), mosaic5()) }

    private fun fx_delay0() = Patch("fx.Delay", "Init", emptyMap())

    private fun fx_delay1() = Patch("fx.Delay", "Slapback",
        mapOf("time" to 0f, "feedback" to 0.126315787f, "tone" to 0.6614124f, "pingpong" to 0f, "mix" to 0.28f))

    private fun fx_delay2() = Patch("fx.Delay", "Eighth Sync",
        mapOf("time" to 0.2857143f, "feedback" to 0.4f, "tone" to 0.7693253f, "pingpong" to 0f, "mix" to 0.32f))

    private fun fx_delay3() = Patch("fx.Delay", "Ping Pong",
        mapOf("feedback" to 0.5263158f, "tone" to 0.801938951f, "mix" to 0.38f))

    private fun fx_delay4() = Patch("fx.Delay", "Dub",
        mapOf("time" to 0.714285731f, "feedback" to 0.863157868f, "tone" to 0.4866298f, "mix" to 0.45f))

    private fun fx_delay5() = Patch("fx.Delay", "Ducked",
        mapOf("time" to 0.5714286f, "feedback" to 0.578947365f, "tone" to 0.696724832f, "mix" to 0.5f, "duck" to 0.8f))

    private fun fx_delay6() = Patch("fx.Delay", "Tape",
        mapOf("time" to 0.5714286f, "feedback" to 0.578947365f, "tone" to 0.57814467f, "pingpong" to 0f, "mix" to 0.36f, "wobble" to 0.35f))

    private fun fx_delay7() = Patch("fx.Delay", "Seasick",
        mapOf("time" to 0.857142866f, "feedback" to 0.7368421f, "tone" to 0.5455311f, "mix" to 0.5f, "duck" to 0.3f, "wobble" to 0.85f))

    private val fx_delay: List<Patch> by lazy { listOf(fx_delay0(), fx_delay1(), fx_delay2(), fx_delay3(), fx_delay4(), fx_delay5(), fx_delay6(), fx_delay7()) }
}
