@file:Suppress("FunctionName")

package com.rm.acidulous.engine

// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.

private fun raw_nativePanic(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativePanic(env, 0)")

private fun async_nativeLoadNexusPatch(arena: Int, rack: Int, spec: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadNexusPatch(arena, rack, spec)")

private fun raw_nativeNexusPalette(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeNexusPalette(env, 0)")

private fun raw_nativeNexusScope(env: Int, rack: Int, out: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeNexusScope(env, 0, rack, out)")

private fun raw_nativeNexusActivity(env: Int, rack: Int, out: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeNexusActivity(env, 0, rack, out)")

private fun raw_nativeStartInput(env: Int, deviceId: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStartInput(env, 0, deviceId)")

private fun raw_nativeStopInput(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStopInput(env, 0)")

private fun raw_nativeInputChannels(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputChannels(env, 0)")

private fun raw_nativeInputRate(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputRate(env, 0)")

private fun raw_nativeInputDevice(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputDevice(env, 0)")

private fun raw_nativeInputRunning(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputRunning(env, 0)")

private fun raw_nativeInputPeak(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputPeak(env, 0)")

private fun raw_nativeSetInputGain(env: Int, gain: Float): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetInputGain(env, 0, gain)")

private fun raw_nativeSetSwingUnit(env: Int, unit: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetSwingUnit(env, 0, unit)")

private fun raw_nativeSetTunerOn(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetTunerOn(env, 0, on)")

private fun raw_nativeTunerHz(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeTunerHz(env, 0)")

private fun raw_nativeSetMonitorLevel(env: Int, level: Float): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetMonitorLevel(env, 0, level)")

private fun raw_nativeStartCapture(env: Int, path: Int, source: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStartCapture(env, 0, path, source)")

private fun raw_nativeStopCapture(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStopCapture(env, 0)")

private fun raw_nativeCapturing(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCapturing(env, 0)")

private fun raw_nativeCapturedSeconds(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCapturedSeconds(env, 0)")

private fun raw_nativeCapturedPeak(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCapturedPeak(env, 0)")

private fun raw_nativeCaptureOverflowed(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCaptureOverflowed(env, 0)")

private fun raw_nativeCaptureDeaf(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCaptureDeaf(env, 0)")

private fun raw_nativeCapturedFrames(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCapturedFrames(env, 0)")

private fun async_nativeCompCell(arena: Int, rack: Int, sceneId: Long, frames: Int, bpm: Float, path: Int, peakOut: Int): Int =
    js("globalThis.acid._acid_async_nativeCompCell(arena, rack, sceneId, frames, bpm, path, peakOut)")

private fun raw_nativeArmCapture(env: Int, rack: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeArmCapture(env, 0, rack)")

private fun raw_nativeCaptureMarks(env: Int, out: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCaptureMarks(env, 0, out)")

private fun async_nativeFileShape(arena: Int, path: Int, out: Int, fromFrame: Int, toFrame: Int): Int =
    js("globalThis.acid._acid_async_nativeFileShape(arena, path, out, fromFrame, toFrame)")

private fun async_nativeFileInfo(arena: Int, path: Int): Int =
    js("globalThis.acid._acid_async_nativeFileInfo(arena, path)")

private fun async_nativeFileSurvey(arena: Int, path: Int, out: Int): Int =
    js("globalThis.acid._acid_async_nativeFileSurvey(arena, path, out)")

private fun raw_nativeAuditionFile(env: Int, path: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeAuditionFile(env, 0, path)")

private fun raw_nativeAuditioning(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeAuditioning(env, 0)")

private fun raw_nativeAuditionProgress(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeAuditionProgress(env, 0)")

private fun raw_nativeEditSample(env: Int, src: Int, dst: Int, ops: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeEditSample(env, 0, src, dst, ops)")

private fun async_nativeEditPreview(arena: Int, src: Int, ops: Int, out: Int, fromFrame: Int, toFrame: Int): Int =
    js("globalThis.acid._acid_async_nativeEditPreview(arena, src, ops, out, fromFrame, toFrame)")

private fun raw_nativeAuditionPreview(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeAuditionPreview(env, 0)")

private fun raw_nativeMidiEvent(env: Int, rackId: Int, status: Int, data1: Int, data2: Int, channel: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMidiEvent(env, 0, rackId, status, data1, data2, channel)")

private fun raw_nativeSetMpeZone(env: Int, kind: Int, members: Int, bendSemis: Float): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetMpeZone(env, 0, kind, members, bendSemis)")

private fun raw_nativeMpeHeldMask(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMpeHeldMask(env, 0)")

private fun raw_nativeStart(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStart(env, 0)")

private fun raw_nativeStop(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStop(env, 0)")

private fun raw_nativeIsRunning(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsRunning(env, 0)")

private fun async_nativeLoadUtterance(arena: Int, rack: Int, path: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadUtterance(arena, rack, path)")

private fun raw_nativeMountMachine(env: Int, rackId: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountMachine(env, 0, rackId, typeName)")

private fun raw_nativeUnmountMachine(env: Int, rackId: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeUnmountMachine(env, 0, rackId)")

private fun async_nativeRenderSong(arena: Int, path: Int, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): Int =
    js("globalThis.acid._acid_async_nativeRenderSong(arena, path, tailSeconds, format, bits, startScene, maxSeconds)")

private fun async_nativeRenderStems(arena: Int, paths: Int, racks: Int, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): Int =
    js("globalThis.acid._acid_async_nativeRenderStems(arena, paths, racks, tailSeconds, format, bits, startScene, maxSeconds)")

private fun raw_nativeSetCountInBars(env: Int, bars: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetCountInBars(env, 0, bars)")

private fun raw_nativeCountInRemaining(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCountInRemaining(env, 0)")

private fun raw_nativeCancelRender(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCancelRender(env, 0)")

private fun raw_nativeIsRendering(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsRendering(env, 0)")

private fun raw_nativeRenderedSeconds(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeRenderedSeconds(env, 0)")

private fun raw_nativeRenderedPeak(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeRenderedPeak(env, 0)")

private fun raw_nativePrewarm(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativePrewarm(env, 0)")

private fun raw_nativeMountInputMod(env: Int, rackId: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountInputMod(env, 0, rackId, slot, typeName)")

private fun raw_nativeInputModTypes(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputModTypes(env, 0)")

private fun raw_nativeInputModParamInfo(env: Int, type: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInputModParamInfo(env, 0, type)")

private fun raw_nativeMountEffect(env: Int, rackId: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountEffect(env, 0, rackId, slot, typeName)")

private fun raw_nativeMountSend(env: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountSend(env, 0, slot, typeName)")

private fun async_nativeMeasureLoudness(arena: Int, tailSeconds: Float, startScene: Int, maxSeconds: Float): Int =
    js("globalThis.acid._acid_async_nativeMeasureLoudness(arena, tailSeconds, startScene, maxSeconds)")

private fun raw_nativeSetRenderGain(env: Int, db: Float): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetRenderGain(env, 0, db)")

private fun raw_nativeLoudness(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLoudness(env, 0)")

private fun raw_nativeResetLoudness(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeResetLoudness(env, 0)")

private fun raw_nativeMountMasterInsert(env: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountMasterInsert(env, 0, slot, typeName)")

private fun raw_nativeMountGroupInsert(env: Int, group: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountGroupInsert(env, 0, group, slot, typeName)")

private fun raw_nativeGroupPeak(env: Int, group: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGroupPeak(env, 0, group)")

private fun raw_nativeMountInputEffect(env: Int, slot: Int, typeName: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMountInputEffect(env, 0, slot, typeName)")

private fun raw_nativeEffectTypes(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeEffectTypes(env, 0)")

private fun raw_nativeEffectParamInfo(env: Int, type: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeEffectParamInfo(env, 0, type)")

private fun raw_nativeLoadSample(env: Int, rackId: Int, slot: Int, path: Int, maxSeconds: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLoadSample(env, 0, rackId, slot, path, maxSeconds)")

private fun async_nativeSoundFontPresets(arena: Int, path: Int): Int =
    js("globalThis.acid._acid_async_nativeSoundFontPresets(arena, path)")

private fun async_nativeLoadSoundFont(arena: Int, rackId: Int, path: Int, presetIndex: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadSoundFont(arena, rackId, path, presetIndex)")

private fun async_nativeLoadZoneMap(arena: Int, rackId: Int, spec: Int, name: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadZoneMap(arena, rackId, spec, name)")

private fun raw_nativeSampleMapInfo(env: Int, rackId: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSampleMapInfo(env, 0, rackId)")

private fun raw_nativeSampleInfo(env: Int, rackId: Int, slot: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSampleInfo(env, 0, rackId, slot)")

private fun async_nativeSlicePoints(arena: Int, path: Int, mode: Int, count: Int): Int =
    js("globalThis.acid._acid_async_nativeSlicePoints(arena, path, mode, count)")

private fun async_nativeLoopShape(arena: Int, path: Int): Int =
    js("globalThis.acid._acid_async_nativeLoopShape(arena, path)")

private fun async_nativeImportAudio(arena: Int, path: Int, maxSeconds: Int): Int =
    js("globalThis.acid._acid_async_nativeImportAudio(arena, path, maxSeconds)")

private fun raw_nativeSampleShape(env: Int, rack: Int, pad: Int, out: Int, fromFrame: Int, toFrame: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSampleShape(env, 0, rack, pad, out, fromFrame, toFrame)")

private fun raw_nativeMachineTypes(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMachineTypes(env, 0)")

private fun raw_nativeNoteOn(env: Int, rackId: Int, note: Int, velocity: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeNoteOn(env, 0, rackId, note, velocity)")

private fun raw_nativeNoteOff(env: Int, rackId: Int, note: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeNoteOff(env, 0, rackId, note)")

private fun raw_nativeControlChange(env: Int, rackId: Int, cc: Int, value: Int, record: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeControlChange(env, 0, rackId, cc, value, record)")

private fun raw_nativeChannelPressure(env: Int, rackId: Int, value: Int, record: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeChannelPressure(env, 0, rackId, value, record)")

private fun raw_nativeSetParam(env: Int, rackId: Int, unit: Int, name: Int, value: Float, record: Int, quantise: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetParam(env, 0, rackId, unit, name, value, record, quantise)")

private fun async_nativeLoadTake(arena: Int, rack: Int, path: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadTake(arena, rack, path)")

private fun async_nativeLoadReel(arena: Int, rack: Int, spec: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadReel(arena, rack, spec)")

private fun raw_nativeSetCacheRoot(env: Int, path: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetCacheRoot(env, 0, path)")

private fun async_nativeLoadFormula(arena: Int, rack: Int, formula: Int, arp: Int, duty: Int, vol: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadFormula(arena, rack, formula, arp, duty, vol)")

private fun async_nativeBuildCloud(arena: Int, rack: Int, spectrum01: Int): Int =
    js("globalThis.acid._acid_async_nativeBuildCloud(arena, rack, spectrum01)")

private fun async_nativeFreezeClip(arena: Int, rack: Int, sceneId: Long, path: Int, tailSeconds: Float): Int =
    js("globalThis.acid._acid_async_nativeFreezeClip(arena, rack, sceneId, path, tailSeconds)")

private fun async_nativeLoadFrozen(arena: Int, rack: Int, sceneIds: Int, paths: Int, bpms: Int, ticks: Int, tails: Int): Int =
    js("globalThis.acid._acid_async_nativeLoadFrozen(arena, rack, sceneIds, paths, bpms, ticks, tails)")

private fun raw_nativeSetBufferBursts(env: Int, bursts: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetBufferBursts(env, 0, bursts)")

private fun raw_nativeBufferFrames(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeBufferFrames(env, 0)")

private fun raw_nativeSetVoiceLimit(env: Int, notes: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetVoiceLimit(env, 0, notes)")

private fun raw_nativeSetQuality(env: Int, level: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetQuality(env, 0, level)")

private fun raw_nativeSetRecordBits(env: Int, bits: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetRecordBits(env, 0, bits)")

private fun raw_nativeGetSampleRate(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetSampleRate(env, 0)")

private fun raw_nativeGetFramesPerBurst(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetFramesPerBurst(env, 0)")

private fun raw_nativeIsLowLatency(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsLowLatency(env, 0)")

private fun raw_nativeGetXRunCount(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetXRunCount(env, 0)")

private fun raw_nativeGetLoadAvg(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetLoadAvg(env, 0)")

private fun raw_nativeWorstBlockUs(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstBlockUs(env, 0)")

private fun raw_nativeWorstCallbackUs(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstCallbackUs(env, 0)")

private fun raw_nativeWorstPhaseUs(env: Int, phase: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstPhaseUs(env, 0, phase)")

private fun raw_nativeWorstRackUs(env: Int, rack: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstRackUs(env, 0, rack)")

private fun raw_nativeRackPercentileUs(env: Int, rack: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeRackPercentileUs(env, 0, rack)")

private fun raw_nativeResetRackCosts(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeResetRackCosts(env, 0)")

private fun raw_nativeWorstRackWasFrozen(env: Int, rack: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstRackWasFrozen(env, 0, rack)")

private fun raw_nativeInterruptedPercent(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeInterruptedPercent(env, 0)")

private fun raw_nativeHintRunning(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeHintRunning(env, 0)")

private fun raw_nativeHintAvailable(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeHintAvailable(env, 0)")

private fun raw_nativeHintState(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeHintState(env, 0)")

private fun raw_nativeRackCostUs(env: Int, rack: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeRackCostUs(env, 0, rack)")

private fun raw_nativeRecentCallbackUs(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeRecentCallbackUs(env, 0)")

private fun raw_nativeWorstCallbackCpuUs(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeWorstCallbackCpuUs(env, 0)")

private fun raw_nativeLateCallbacks(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLateCallbacks(env, 0)")

private fun raw_nativeStalledCallbacks(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStalledCallbacks(env, 0)")

private fun raw_nativeCallbackBudgetUs(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCallbackBudgetUs(env, 0)")

private fun raw_nativeReadPeakLevel(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeReadPeakLevel(env, 0)")

private fun raw_nativeReadRackPeak(env: Int, rackId: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeReadRackPeak(env, 0, rackId)")

private fun raw_nativeGetMasterFade(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetMasterFade(env, 0)")

private fun raw_nativeTransportPlay(env: Int, sceneIdx: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeTransportPlay(env, 0, sceneIdx)")

private fun raw_nativeTransportStop(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeTransportStop(env, 0)")

private fun raw_nativeTransportRewind(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeTransportRewind(env, 0)")

private fun raw_nativeSetStopAtEnd(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetStopAtEnd(env, 0, on)")

private fun raw_nativeIsStopAtEndArmed(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsStopAtEndArmed(env, 0)")

private fun raw_nativeQueueScene(env: Int, idx: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeQueueScene(env, 0, idx)")

private fun raw_nativeQueuedScene(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeQueuedScene(env, 0)")

private fun raw_nativeSetLauncher(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLauncher(env, 0, on)")

private fun raw_nativeSetFill(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetFill(env, 0, on)")

private fun raw_nativeSetLaunchQuantise(env: Int, ticks: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLaunchQuantise(env, 0, ticks)")

private fun raw_nativeLaunchClip(env: Int, rack: Int, sceneId: Long): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLaunchClip(env, 0, rack, sceneId)")

private fun raw_nativeLaunchScene(env: Int, sceneId: Long): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLaunchScene(env, 0, sceneId)")

private fun raw_nativeStopAllClips(env: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeStopAllClips(env, 0)")

private fun raw_nativeCancelLaunch(env: Int, rack: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeCancelLaunch(env, 0, rack)")

private fun raw_nativeSetClockOut(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetClockOut(env, 0, on)")

private fun raw_nativeDrainMidiOut(env: Int, out: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeDrainMidiOut(env, 0, out)")

private fun raw_nativeAudioAnchor(env: Int, out: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeAudioAnchor(env, 0, out)")

private fun raw_nativeSetExternalSync(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetExternalSync(env, 0, on)")

private fun raw_nativeSetTuning(env: Int, rack: Int, ratios: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetTuning(env, 0, rack, ratios)")

private fun raw_nativeSetLink(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLink(env, 0, on)")

private fun raw_nativeLinkEnabled(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLinkEnabled(env, 0)")

private fun raw_nativeSetLinkStartStop(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLinkStartStop(env, 0, on)")

private fun raw_nativeLinkStatus(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLinkStatus(env, 0)")

private fun raw_nativeMidiClockIn(env: Int, frame: Long, status: Int, d1: Int, d2: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMidiClockIn(env, 0, frame, status, d1, d2)")

private fun raw_nativeSyncState(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSyncState(env, 0)")

private fun raw_nativeLaunchStates(env: Int, out: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeLaunchStates(env, 0, out)")

private fun raw_nativeIsPlaying(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsPlaying(env, 0)")

private fun raw_nativeSetLoopScene(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLoopScene(env, 0, on)")

private fun raw_nativeSetLoopSong(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetLoopSong(env, 0, on)")

private fun raw_nativeSetRecordArmed(env: Int, on: Int): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetRecordArmed(env, 0, on)")

private fun raw_nativeIsRecordArmed(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeIsRecordArmed(env, 0)")

private fun raw_nativeDrainRecorded(env: Int, out: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeDrainRecorded(env, 0, out)")

private fun raw_nativeGetRecordedDropped(env: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetRecordedDropped(env, 0)")

private fun raw_nativeSetTempo(env: Int, bpm: Float): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSetTempo(env, 0, bpm)")

private fun raw_nativeGetTempo(env: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetTempo(env, 0)")

private fun raw_nativeGetPositionPacked(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetPositionPacked(env, 0)")

private fun raw_nativeGetNotesOn(env: Int, rackId: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetNotesOn(env, 0, rackId)")

private fun raw_nativeDebugParam(env: Int, rackId: Int, name: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeDebugParam(env, 0, rackId, name)")

private fun raw_nativeGetNotesOff(env: Int, rackId: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeGetNotesOff(env, 0, rackId)")

private fun raw_nativeSnapshotBegin(env: Int): Long =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotBegin(env, 0)")

private fun raw_nativeSnapshotAddScene(env: Int, handle: Long, sceneId: Long, ticksPerBar: Int, repeat: Int, bpmOverride: Float, rampToBpm: Float, rampBars: Int, smooth: Int, fadeIn: Int, fadeOut: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotAddScene(env, 0, handle, sceneId, ticksPerBar, repeat, bpmOverride, rampToBpm, rampBars, smooth, fadeIn, fadeOut)")

private fun raw_nativeSnapshotSetClipCached(env: Int, handle: Long, rack: Int, scene: Int, rev: Long): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotSetClipCached(env, 0, handle, rack, scene, rev)")

private fun raw_nativeSnapshotSetClip(env: Int, handle: Long, rack: Int, scene: Int, rev: Long, bars: Int, playMode: Int, mute: Int, seed: Int, notes: Int, expr: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotSetClip(env, 0, handle, rack, scene, rev, bars, playMode, mute, seed, notes, expr)")

private fun raw_nativeSnapshotSetLane(env: Int, handle: Long, rack: Int, scene: Int, machineType: Int, unit: Int, name: Int, linear: Int, points: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotSetLane(env, 0, handle, rack, scene, machineType, unit, name, linear, points)")

private fun raw_nativeSnapshotCommit(env: Int, handle: Long): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotCommit(env, 0, handle)")

private fun raw_nativeMachineParamNames(env: Int, type: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMachineParamNames(env, 0, type)")

private fun raw_nativeMachineParamInfo(env: Int, type: Int): Int =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeMachineParamInfo(env, 0, type)")

private fun raw_nativeParamNormalized(env: Int, rackId: Int, unit: Int, name: Int): Float =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeParamNormalized(env, 0, rackId, unit, name)")

private fun raw_nativeSnapshotAbandon(env: Int, handle: Long): Unit =
    js("globalThis.acid._Java_com_rm_acidulous_engine_EngineNative_nativeSnapshotAbandon(env, 0, handle)")

/** The engine through its bridge compiled to WebAssembly: see Jni and platform/web/jni.h. */
internal actual object EngineNative {
    actual fun nativePanic() {
        raw_nativePanic(Jni.env)
        Jni.release()
    }

    actual suspend fun nativeLoadNexusPatch(rack: Int, spec: String): String {
        val arena_ = Jni.openArena()
        val jspec = Jni.string(spec)
        val ticket_ = async_nativeLoadNexusPatch(arena_, rack, jspec)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeNexusPalette(): String {
        val raw_ = raw_nativeNexusPalette(Jni.env)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeNexusScope(rack: Int, out: FloatArray): Int {
        val jout = Jni.floats(out)
        val raw_ = raw_nativeNexusScope(Jni.env, rack, jout)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeNexusActivity(rack: Int, out: FloatArray): Int {
        val jout = Jni.floats(out)
        val raw_ = raw_nativeNexusActivity(Jni.env, rack, jout)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeStartInput(deviceId: Int): Boolean {
        val raw_ = raw_nativeStartInput(Jni.env, deviceId)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeStopInput(): Boolean {
        val raw_ = raw_nativeStopInput(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeInputChannels(): Int {
        val raw_ = raw_nativeInputChannels(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeInputRate(): Int {
        val raw_ = raw_nativeInputRate(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeInputDevice(): Int {
        val raw_ = raw_nativeInputDevice(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeInputRunning(): Boolean {
        val raw_ = raw_nativeInputRunning(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeInputPeak(): Float {
        val raw_ = raw_nativeInputPeak(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSetInputGain(gain: Float) {
        raw_nativeSetInputGain(Jni.env, gain)
        Jni.release()
    }

    actual fun nativeSetSwingUnit(unit: Int) {
        raw_nativeSetSwingUnit(Jni.env, unit)
        Jni.release()
    }

    actual fun nativeSetTunerOn(on: Boolean) {
        raw_nativeSetTunerOn(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeTunerHz(): Float {
        val raw_ = raw_nativeTunerHz(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSetMonitorLevel(level: Float) {
        raw_nativeSetMonitorLevel(Jni.env, level)
        Jni.release()
    }

    actual fun nativeStartCapture(path: String, source: Int): String {
        val jpath = Jni.string(path)
        val raw_ = raw_nativeStartCapture(Jni.env, jpath, source)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeStopCapture() {
        raw_nativeStopCapture(Jni.env)
        Jni.release()
    }

    actual fun nativeCapturing(): Boolean {
        val raw_ = raw_nativeCapturing(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeCapturedSeconds(): Float {
        val raw_ = raw_nativeCapturedSeconds(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeCapturedPeak(): Float {
        val raw_ = raw_nativeCapturedPeak(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeCaptureOverflowed(): Boolean {
        val raw_ = raw_nativeCaptureOverflowed(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeCaptureDeaf(): Boolean {
        val raw_ = raw_nativeCaptureDeaf(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeCapturedFrames(): Long {
        val raw_ = raw_nativeCapturedFrames(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual suspend fun nativeCompCell(rack: Int, sceneId: Long, frames: Int, bpm: Float, path: String, peakOut: FloatArray): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val jpeakOut = Jni.floats(peakOut)
        val ticket_ = async_nativeCompCell(arena_, rack, sceneId, frames, bpm, jpath, jpeakOut)
        Jni.await(ticket_)
        Jni.copyBack(jpeakOut, peakOut)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeArmCapture(rack: Int) {
        raw_nativeArmCapture(Jni.env, rack)
        Jni.release()
    }

    actual fun nativeCaptureMarks(out: LongArray): Int {
        val jout = Jni.longs(out)
        val raw_ = raw_nativeCaptureMarks(Jni.env, jout)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual suspend fun nativeFileShape(path: String, out: FloatArray, fromFrame: Int, toFrame: Int): Int {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val jout = Jni.floats(out)
        val ticket_ = async_nativeFileShape(arena_, jpath, jout, fromFrame, toFrame)
        Jni.await(ticket_)
        Jni.copyBack(jout, out)
        val result_ = Jni.resultInt(ticket_)
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeFileInfo(path: String): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeFileInfo(arena_, jpath)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeFileSurvey(path: String, out: FloatArray): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val jout = Jni.floats(out)
        val ticket_ = async_nativeFileSurvey(arena_, jpath, jout)
        Jni.await(ticket_)
        Jni.copyBack(jout, out)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeAuditionFile(path: String): String {
        val jpath = Jni.string(path)
        val raw_ = raw_nativeAuditionFile(Jni.env, jpath)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeAuditioning(): Boolean {
        val raw_ = raw_nativeAuditioning(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeAuditionProgress(): Float {
        val raw_ = raw_nativeAuditionProgress(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeEditSample(src: String, dst: String, ops: FloatArray): String {
        val jsrc = Jni.string(src)
        val jdst = Jni.string(dst)
        val jops = Jni.floats(ops)
        val raw_ = raw_nativeEditSample(Jni.env, jsrc, jdst, jops)
        Jni.copyBack(jops, ops)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual suspend fun nativeEditPreview(src: String, ops: FloatArray, out: FloatArray, fromFrame: Int, toFrame: Int): Int {
        val arena_ = Jni.openArena()
        val jsrc = Jni.string(src)
        val jops = Jni.floats(ops)
        val jout = Jni.floats(out)
        val ticket_ = async_nativeEditPreview(arena_, jsrc, jops, jout, fromFrame, toFrame)
        Jni.await(ticket_)
        Jni.copyBack(jops, ops)
        Jni.copyBack(jout, out)
        val result_ = Jni.resultInt(ticket_)
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeAuditionPreview(): String {
        val raw_ = raw_nativeAuditionPreview(Jni.env)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeMidiEvent(rackId: Int, status: Int, data1: Int, data2: Int, channel: Int) {
        raw_nativeMidiEvent(Jni.env, rackId, status, data1, data2, channel)
        Jni.release()
    }

    actual fun nativeSetMpeZone(kind: Int, members: Int, bendSemis: Float) {
        raw_nativeSetMpeZone(Jni.env, kind, members, bendSemis)
        Jni.release()
    }

    actual fun nativeMpeHeldMask(): Int {
        val raw_ = raw_nativeMpeHeldMask(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeStart(): Boolean {
        val raw_ = raw_nativeStart(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeStop() {
        raw_nativeStop(Jni.env)
        Jni.release()
    }

    actual fun nativeIsRunning(): Boolean {
        val raw_ = raw_nativeIsRunning(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual suspend fun nativeLoadUtterance(rack: Int, path: String): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeLoadUtterance(arena_, rack, jpath)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeMountMachine(rackId: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountMachine(Jni.env, rackId, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeUnmountMachine(rackId: Int) {
        raw_nativeUnmountMachine(Jni.env, rackId)
        Jni.release()
    }

    actual suspend fun nativeRenderSong(path: String, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeRenderSong(arena_, jpath, tailSeconds, format, bits, startScene, maxSeconds)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeRenderStems(paths: Array<String>, racks: IntArray, tailSeconds: Float, format: Int, bits: Int, startScene: Int, maxSeconds: Float): String {
        val arena_ = Jni.openArena()
        val jpaths = Jni.strings(paths)
        val jracks = Jni.ints(racks)
        val ticket_ = async_nativeRenderStems(arena_, jpaths, jracks, tailSeconds, format, bits, startScene, maxSeconds)
        Jni.await(ticket_)
        Jni.copyBack(jracks, racks)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSetCountInBars(bars: Int) {
        raw_nativeSetCountInBars(Jni.env, bars)
        Jni.release()
    }

    actual fun nativeCountInRemaining(): Long {
        val raw_ = raw_nativeCountInRemaining(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeCancelRender() {
        raw_nativeCancelRender(Jni.env)
        Jni.release()
    }

    actual fun nativeIsRendering(): Boolean {
        val raw_ = raw_nativeIsRendering(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeRenderedSeconds(): Float {
        val raw_ = raw_nativeRenderedSeconds(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeRenderedPeak(): Float {
        val raw_ = raw_nativeRenderedPeak(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativePrewarm() {
        raw_nativePrewarm(Jni.env)
        Jni.release()
    }

    actual fun nativeMountInputMod(rackId: Int, slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountInputMod(Jni.env, rackId, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeInputModTypes(): Array<String> {
        val raw_ = raw_nativeInputModTypes(Jni.env)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeInputModParamInfo(type: String): Array<String> {
        val jtype = Jni.string(type)
        val raw_ = raw_nativeInputModParamInfo(Jni.env, jtype)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeMountEffect(rackId: Int, slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountEffect(Jni.env, rackId, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeMountSend(slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountSend(Jni.env, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual suspend fun nativeMeasureLoudness(tailSeconds: Float, startScene: Int, maxSeconds: Float): FloatArray? {
        val arena_ = Jni.openArena()
        val ticket_ = async_nativeMeasureLoudness(arena_, tailSeconds, startScene, maxSeconds)
        Jni.await(ticket_)
        val result_ = Jni.readFloats(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSetRenderGain(db: Float) {
        raw_nativeSetRenderGain(Jni.env, db)
        Jni.release()
    }

    actual fun nativeLoudness(): FloatArray {
        val raw_ = raw_nativeLoudness(Jni.env)
        val result_ = Jni.readFloats(raw_) ?: FloatArray(0)
        Jni.release()
        return result_
    }

    actual fun nativeResetLoudness() {
        raw_nativeResetLoudness(Jni.env)
        Jni.release()
    }

    actual fun nativeMountMasterInsert(slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountMasterInsert(Jni.env, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeMountGroupInsert(group: Int, slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountGroupInsert(Jni.env, group, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeGroupPeak(group: Int): Float {
        val raw_ = raw_nativeGroupPeak(Jni.env, group)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeMountInputEffect(slot: Int, typeName: String): Boolean {
        val jtypeName = Jni.string(typeName)
        val raw_ = raw_nativeMountInputEffect(Jni.env, slot, jtypeName)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeEffectTypes(): Array<String> {
        val raw_ = raw_nativeEffectTypes(Jni.env)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeEffectParamInfo(type: String): Array<String> {
        val jtype = Jni.string(type)
        val raw_ = raw_nativeEffectParamInfo(Jni.env, jtype)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeLoadSample(rackId: Int, slot: Int, path: String, maxSeconds: Int): String {
        val jpath = Jni.string(path)
        val raw_ = raw_nativeLoadSample(Jni.env, rackId, slot, jpath, maxSeconds)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual suspend fun nativeSoundFontPresets(path: String): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeSoundFontPresets(arena_, jpath)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeLoadSoundFont(rackId: Int, path: String, presetIndex: Int): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeLoadSoundFont(arena_, rackId, jpath, presetIndex)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeLoadZoneMap(rackId: Int, spec: String, name: String): String {
        val arena_ = Jni.openArena()
        val jspec = Jni.string(spec)
        val jname = Jni.string(name)
        val ticket_ = async_nativeLoadZoneMap(arena_, rackId, jspec, jname)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSampleMapInfo(rackId: Int): String {
        val raw_ = raw_nativeSampleMapInfo(Jni.env, rackId)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeSampleInfo(rackId: Int, slot: Int): String {
        val raw_ = raw_nativeSampleInfo(Jni.env, rackId, slot)
        val result_ = Jni.readString(raw_)
        Jni.release()
        return result_
    }

    actual suspend fun nativeSlicePoints(path: String, mode: Int, count: Int): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeSlicePoints(arena_, jpath, mode, count)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeLoopShape(path: String): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeLoopShape(arena_, jpath)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeImportAudio(path: String, maxSeconds: Int): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeImportAudio(arena_, jpath, maxSeconds)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSampleShape(rack: Int, pad: Int, out: FloatArray, fromFrame: Int, toFrame: Int): Int {
        val jout = Jni.floats(out)
        val raw_ = raw_nativeSampleShape(Jni.env, rack, pad, jout, fromFrame, toFrame)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeMachineTypes(): Array<String> {
        val raw_ = raw_nativeMachineTypes(Jni.env)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeNoteOn(rackId: Int, note: Int, velocity: Int) {
        raw_nativeNoteOn(Jni.env, rackId, note, velocity)
        Jni.release()
    }

    actual fun nativeNoteOff(rackId: Int, note: Int) {
        raw_nativeNoteOff(Jni.env, rackId, note)
        Jni.release()
    }

    actual fun nativeControlChange(rackId: Int, cc: Int, value: Int, record: Boolean) {
        raw_nativeControlChange(Jni.env, rackId, cc, value, if (record) 1 else 0)
        Jni.release()
    }

    actual fun nativeChannelPressure(rackId: Int, value: Int, record: Boolean) {
        raw_nativeChannelPressure(Jni.env, rackId, value, if (record) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetParam(rackId: Int, unit: String, name: String, value: Float, record: Boolean, quantise: Int): Boolean {
        val junit = Jni.string(unit)
        val jname = Jni.string(name)
        val raw_ = raw_nativeSetParam(Jni.env, rackId, junit, jname, value, if (record) 1 else 0, quantise)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual suspend fun nativeLoadTake(rack: Int, path: String): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeLoadTake(arena_, rack, jpath)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeLoadReel(rack: Int, spec: String): String {
        val arena_ = Jni.openArena()
        val jspec = Jni.string(spec)
        val ticket_ = async_nativeLoadReel(arena_, rack, jspec)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSetCacheRoot(path: String) {
        val jpath = Jni.string(path)
        raw_nativeSetCacheRoot(Jni.env, jpath)
        Jni.release()
    }

    actual suspend fun nativeLoadFormula(rack: Int, formula: String, arp: String, duty: String, vol: String): String {
        val arena_ = Jni.openArena()
        val jformula = Jni.string(formula)
        val jarp = Jni.string(arp)
        val jduty = Jni.string(duty)
        val jvol = Jni.string(vol)
        val ticket_ = async_nativeLoadFormula(arena_, rack, jformula, jarp, jduty, jvol)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeBuildCloud(rack: Int, spectrum01: FloatArray): String {
        val arena_ = Jni.openArena()
        val jspectrum01 = Jni.floats(spectrum01)
        val ticket_ = async_nativeBuildCloud(arena_, rack, jspectrum01)
        Jni.await(ticket_)
        Jni.copyBack(jspectrum01, spectrum01)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeFreezeClip(rack: Int, sceneId: Long, path: String, tailSeconds: Float): String {
        val arena_ = Jni.openArena()
        val jpath = Jni.string(path)
        val ticket_ = async_nativeFreezeClip(arena_, rack, sceneId, jpath, tailSeconds)
        Jni.await(ticket_)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual suspend fun nativeLoadFrozen(rack: Int, sceneIds: LongArray, paths: Array<String>, bpms: FloatArray, ticks: IntArray, tails: IntArray): String {
        val arena_ = Jni.openArena()
        val jsceneIds = Jni.longs(sceneIds)
        val jpaths = Jni.strings(paths)
        val jbpms = Jni.floats(bpms)
        val jticks = Jni.ints(ticks)
        val jtails = Jni.ints(tails)
        val ticket_ = async_nativeLoadFrozen(arena_, rack, jsceneIds, jpaths, jbpms, jticks, jtails)
        Jni.await(ticket_)
        Jni.copyBack(jsceneIds, sceneIds)
        Jni.copyBack(jbpms, bpms)
        Jni.copyBack(jticks, ticks)
        Jni.copyBack(jtails, tails)
        val result_ = Jni.readString(Jni.resultInt(ticket_))
        Jni.releaseAsync(ticket_)
        return result_
    }

    actual fun nativeSetBufferBursts(bursts: Int) {
        raw_nativeSetBufferBursts(Jni.env, bursts)
        Jni.release()
    }

    actual fun nativeBufferFrames(): Int {
        val raw_ = raw_nativeBufferFrames(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSetVoiceLimit(notes: Int) {
        raw_nativeSetVoiceLimit(Jni.env, notes)
        Jni.release()
    }

    actual fun nativeSetQuality(level: Int) {
        raw_nativeSetQuality(Jni.env, level)
        Jni.release()
    }

    actual fun nativeSetRecordBits(bits: Int) {
        raw_nativeSetRecordBits(Jni.env, bits)
        Jni.release()
    }

    actual fun nativeGetSampleRate(): Int {
        val raw_ = raw_nativeGetSampleRate(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetFramesPerBurst(): Int {
        val raw_ = raw_nativeGetFramesPerBurst(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeIsLowLatency(): Boolean {
        val raw_ = raw_nativeIsLowLatency(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeGetXRunCount(): Long {
        val raw_ = raw_nativeGetXRunCount(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetLoadAvg(): Float {
        val raw_ = raw_nativeGetLoadAvg(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeWorstBlockUs(): Int {
        val raw_ = raw_nativeWorstBlockUs(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeWorstCallbackUs(): Int {
        val raw_ = raw_nativeWorstCallbackUs(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeWorstPhaseUs(phase: Int): Int {
        val raw_ = raw_nativeWorstPhaseUs(Jni.env, phase)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeWorstRackUs(rack: Int): Int {
        val raw_ = raw_nativeWorstRackUs(Jni.env, rack)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeRackPercentileUs(rack: Int): Int {
        val raw_ = raw_nativeRackPercentileUs(Jni.env, rack)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeResetRackCosts() {
        raw_nativeResetRackCosts(Jni.env)
        Jni.release()
    }

    actual fun nativeWorstRackWasFrozen(rack: Int): Boolean {
        val raw_ = raw_nativeWorstRackWasFrozen(Jni.env, rack)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeInterruptedPercent(): Float {
        val raw_ = raw_nativeInterruptedPercent(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeHintRunning(): Boolean {
        val raw_ = raw_nativeHintRunning(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeHintAvailable(): Boolean {
        val raw_ = raw_nativeHintAvailable(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeHintState(): Int {
        val raw_ = raw_nativeHintState(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeRackCostUs(rack: Int): Int {
        val raw_ = raw_nativeRackCostUs(Jni.env, rack)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeRecentCallbackUs(): Int {
        val raw_ = raw_nativeRecentCallbackUs(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeWorstCallbackCpuUs(): Int {
        val raw_ = raw_nativeWorstCallbackCpuUs(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeLateCallbacks(): Long {
        val raw_ = raw_nativeLateCallbacks(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeStalledCallbacks(): Long {
        val raw_ = raw_nativeStalledCallbacks(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeCallbackBudgetUs(): Int {
        val raw_ = raw_nativeCallbackBudgetUs(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeReadPeakLevel(): Float {
        val raw_ = raw_nativeReadPeakLevel(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeReadRackPeak(rackId: Int): Float {
        val raw_ = raw_nativeReadRackPeak(Jni.env, rackId)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetMasterFade(): Float {
        val raw_ = raw_nativeGetMasterFade(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeTransportPlay(sceneIdx: Int) {
        raw_nativeTransportPlay(Jni.env, sceneIdx)
        Jni.release()
    }

    actual fun nativeTransportStop() {
        raw_nativeTransportStop(Jni.env)
        Jni.release()
    }

    actual fun nativeTransportRewind() {
        raw_nativeTransportRewind(Jni.env)
        Jni.release()
    }

    actual fun nativeSetStopAtEnd(on: Boolean) {
        raw_nativeSetStopAtEnd(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeIsStopAtEndArmed(): Boolean {
        val raw_ = raw_nativeIsStopAtEndArmed(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeQueueScene(idx: Int) {
        raw_nativeQueueScene(Jni.env, idx)
        Jni.release()
    }

    actual fun nativeQueuedScene(): Int {
        val raw_ = raw_nativeQueuedScene(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSetLauncher(on: Boolean) {
        raw_nativeSetLauncher(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetFill(on: Boolean) {
        raw_nativeSetFill(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetLaunchQuantise(ticks: Int) {
        raw_nativeSetLaunchQuantise(Jni.env, ticks)
        Jni.release()
    }

    actual fun nativeLaunchClip(rack: Int, sceneId: Long) {
        raw_nativeLaunchClip(Jni.env, rack, sceneId)
        Jni.release()
    }

    actual fun nativeLaunchScene(sceneId: Long) {
        raw_nativeLaunchScene(Jni.env, sceneId)
        Jni.release()
    }

    actual fun nativeStopAllClips() {
        raw_nativeStopAllClips(Jni.env)
        Jni.release()
    }

    actual fun nativeCancelLaunch(rack: Int) {
        raw_nativeCancelLaunch(Jni.env, rack)
        Jni.release()
    }

    actual fun nativeSetClockOut(on: Boolean) {
        raw_nativeSetClockOut(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeDrainMidiOut(out: LongArray): Int {
        val jout = Jni.longs(out)
        val raw_ = raw_nativeDrainMidiOut(Jni.env, jout)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeAudioAnchor(out: LongArray) {
        val jout = Jni.longs(out)
        raw_nativeAudioAnchor(Jni.env, jout)
        Jni.copyBack(jout, out)
        Jni.release()
    }

    actual fun nativeSetExternalSync(on: Boolean) {
        raw_nativeSetExternalSync(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetTuning(rack: Int, ratios: FloatArray?) {
        val jratios = Jni.floats(ratios)
        raw_nativeSetTuning(Jni.env, rack, jratios)
        Jni.copyBack(jratios, ratios)
        Jni.release()
    }

    actual fun nativeSetLink(on: Boolean) {
        raw_nativeSetLink(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeLinkEnabled(): Boolean {
        val raw_ = raw_nativeLinkEnabled(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSetLinkStartStop(on: Boolean) {
        raw_nativeSetLinkStartStop(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeLinkStatus(): Long {
        val raw_ = raw_nativeLinkStatus(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeMidiClockIn(frame: Long, status: Int, d1: Int, d2: Int) {
        raw_nativeMidiClockIn(Jni.env, frame, status, d1, d2)
        Jni.release()
    }

    actual fun nativeSyncState(): Long {
        val raw_ = raw_nativeSyncState(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeLaunchStates(out: LongArray) {
        val jout = Jni.longs(out)
        raw_nativeLaunchStates(Jni.env, jout)
        Jni.copyBack(jout, out)
        Jni.release()
    }

    actual fun nativeIsPlaying(): Boolean {
        val raw_ = raw_nativeIsPlaying(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSetLoopScene(on: Boolean) {
        raw_nativeSetLoopScene(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetLoopSong(on: Boolean) {
        raw_nativeSetLoopSong(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeSetRecordArmed(on: Boolean) {
        raw_nativeSetRecordArmed(Jni.env, if (on) 1 else 0)
        Jni.release()
    }

    actual fun nativeIsRecordArmed(): Boolean {
        val raw_ = raw_nativeIsRecordArmed(Jni.env)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeDrainRecorded(out: LongArray): Int {
        val jout = Jni.longs(out)
        val raw_ = raw_nativeDrainRecorded(Jni.env, jout)
        Jni.copyBack(jout, out)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetRecordedDropped(): Int {
        val raw_ = raw_nativeGetRecordedDropped(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSetTempo(bpm: Float) {
        raw_nativeSetTempo(Jni.env, bpm)
        Jni.release()
    }

    actual fun nativeGetTempo(): Float {
        val raw_ = raw_nativeGetTempo(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetPositionPacked(): Long {
        val raw_ = raw_nativeGetPositionPacked(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetNotesOn(rackId: Int): Int {
        val raw_ = raw_nativeGetNotesOn(Jni.env, rackId)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeDebugParam(rackId: Int, name: String): Float {
        val jname = Jni.string(name)
        val raw_ = raw_nativeDebugParam(Jni.env, rackId, jname)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeGetNotesOff(rackId: Int): Int {
        val raw_ = raw_nativeGetNotesOff(Jni.env, rackId)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotBegin(): Long {
        val raw_ = raw_nativeSnapshotBegin(Jni.env)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotAddScene(handle: Long, sceneId: Long, ticksPerBar: Int, repeat: Int, bpmOverride: Float, rampToBpm: Float, rampBars: Int, smooth: Boolean, fadeIn: Boolean, fadeOut: Boolean): Boolean {
        val raw_ = raw_nativeSnapshotAddScene(Jni.env, handle, sceneId, ticksPerBar, repeat, bpmOverride, rampToBpm, rampBars, if (smooth) 1 else 0, if (fadeIn) 1 else 0, if (fadeOut) 1 else 0)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotSetClipCached(handle: Long, rack: Int, scene: Int, rev: Long): Boolean {
        val raw_ = raw_nativeSnapshotSetClipCached(Jni.env, handle, rack, scene, rev)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotSetClip(handle: Long, rack: Int, scene: Int, rev: Long, bars: Int, playMode: Int, mute: Boolean, seed: Int, notes: IntArray, expr: FloatArray): Boolean {
        val jnotes = Jni.ints(notes)
        val jexpr = Jni.floats(expr)
        val raw_ = raw_nativeSnapshotSetClip(Jni.env, handle, rack, scene, rev, bars, playMode, if (mute) 1 else 0, seed, jnotes, jexpr)
        Jni.copyBack(jnotes, notes)
        Jni.copyBack(jexpr, expr)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotSetLane(handle: Long, rack: Int, scene: Int, machineType: String, unit: String, name: String, linear: Boolean, points: FloatArray): Boolean {
        val jmachineType = Jni.string(machineType)
        val junit = Jni.string(unit)
        val jname = Jni.string(name)
        val jpoints = Jni.floats(points)
        val raw_ = raw_nativeSnapshotSetLane(Jni.env, handle, rack, scene, jmachineType, junit, jname, if (linear) 1 else 0, jpoints)
        Jni.copyBack(jpoints, points)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotCommit(handle: Long): Boolean {
        val raw_ = raw_nativeSnapshotCommit(Jni.env, handle)
        val result_ = raw_ != 0
        Jni.release()
        return result_
    }

    actual fun nativeMachineParamNames(type: String): Array<String> {
        val jtype = Jni.string(type)
        val raw_ = raw_nativeMachineParamNames(Jni.env, jtype)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeMachineParamInfo(type: String): Array<String> {
        val jtype = Jni.string(type)
        val raw_ = raw_nativeMachineParamInfo(Jni.env, jtype)
        val result_ = Jni.readStrings(raw_)
        Jni.release()
        return result_
    }

    actual fun nativeParamNormalized(rackId: Int, unit: String, name: String): Float {
        val junit = Jni.string(unit)
        val jname = Jni.string(name)
        val raw_ = raw_nativeParamNormalized(Jni.env, rackId, junit, jname)
        val result_ = raw_
        Jni.release()
        return result_
    }

    actual fun nativeSnapshotAbandon(handle: Long) {
        raw_nativeSnapshotAbandon(Jni.env, handle)
        Jni.release()
    }
}
