// Works out DrawHarp.h: for every hole of a Richter harp in every key, how far
// each reed must be tuned from its note to sound it with the mouth open, and
// where the mouth must be for each step of a bend; and for a reed on its own behind a valve, how far it's tuned at
// each note. Draw reads these to play a note the way a player would.
//
//   draw_harp.sh          writes app/src/main/cpp/engine/machine/draw/DrawHarp.h
//
// Each case plays draw::HarpHole for 1 s and measures the last 0.4 s by
// autocorrelation. Tuning takes three passes; the bend map sweeps the mouth
// down from open and, where the pitch passes each quarter semitone, halves
// the step until it lands; it ends where the pitch stops being steady.
//
// For a look at one case: HOLE=n plays only that hole, ONEKEY=1 only the C
// harp (the table it writes is then partial), VERBOSE=1 prints every step.
#include <engine/machine/draw/DrawKinds.h>
#include <engine/machine/draw/HarpHole.h>

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <vector>
#include <xmmintrin.h>

using namespace acidulous::machine::draw;

namespace {

constexpr float kRate = 48000.0f;
constexpr int kBendSteps = 13; // 0 to 3 semitones in quarters
constexpr int kSingleLow = 36, kSingleHigh = 108;
// Blown as Draw blows a harp at velocity 100 with the knobs where they start:
// bends move with the breath, so the tables must be made at the same pressure.
constexpr float kPressure = kKindVoices[Diatonic].pressure * (1.0f - 0.6f * 0.6f * (1.0f - 100.0f / 127.0f));
constexpr float kQ = 6.0f;

double hzOf(double semisFromC4) { return 261.6256 * std::pow(2.0, semisFromC4 / 12.0); }
double cents(double a, double b) { return 1200.0 * std::log2(a / b); }
bool verbose() { return getenv("VERBOSE") != nullptr; }

/** What the hole plays, Hz, or 0 when it doesn't speak. */
double play(double blowHz, double drawHz, double mouthHz, float pressure, bool valves = false) {
    HarpHole h;
    h.prepare(kRate);
    ReedMake k = kMakes_[HarpReed];
    k.turbulence = 0.0f;
    h.make(static_cast<float>(blowHz), static_cast<float>(drawHz), k);
    h.valves(valves);
    h.clear();
    h.shapeMouth(static_cast<float>(mouthHz), kQ);
    const int n = static_cast<int>(1.0f * kRate), from = static_cast<int>(0.6f * kRate);
    std::vector<float> out(n);
    for (int i = 0; i < n; ++i) out[i] = h.step(pressure * std::fmin(1.0f, static_cast<float>(i) / (0.02f * kRate)));
    const double lo = std::min(blowHz, drawHz), hi = std::max(blowHz, drawHz);
    const int lagLo = static_cast<int>(kRate / (1.3 * hi)), lagHi = static_cast<int>(kRate / (0.7 * lo));
    double e = 0;
    for (int i = from; i < n - lagHi - 1; ++i) e += out[i] * out[i];
    if (e < 1e-20) return 0;
    std::vector<double> r(lagHi + 2);
    for (int lag = lagLo; lag <= lagHi + 1; ++lag) {
        double s = 0;
        for (int i = from; i < n - lagHi - 1; ++i) s += out[i] * out[i + lag];
        r[lag] = s / e;
    }
    int best = lagLo;
    for (int lag = lagLo; lag <= lagHi; ++lag) if (r[lag] > r[best]) best = lag;
    for (int lag = lagLo + 1; lag <= lagHi; ++lag) {
        if (r[lag] > 0.85 * r[best] && r[lag] >= r[lag - 1] && r[lag] >= r[lag + 1]) { best = lag; break; }
    }
    if (r[best] < 0.3) return 0;
    double shift = 0;
    if (best > lagLo && best < lagHi) {
        const double a = r[best - 1], b = r[best], c = r[best + 1], d = a - 2 * b + c;
        if (d != 0) shift = 0.5 * (a - c) / d;
    }
    return kRate / (best + shift);
}

} // namespace

int main(int argc, char **argv) {
    _mm_setcsr(_mm_getcsr() | 0x8040);
    const std::string out = argc > 1 ? argv[1] : "DrawHarp.h";
    const int onlyHole = getenv("HOLE") ? atoi(getenv("HOLE")) : 0;
    const bool oneKey = getenv("ONEKEY") != nullptr;
    FILE *f = std::fopen(out.c_str(), "w");
    std::fprintf(f,
                 "#pragma once\n// Generated by tools/draw_harp.sh: do not edit.\nnamespace acidulous::machine::draw {\n\n"
                 "/**\n * One hole of a Richter harp: how far its blow and draw reeds are tuned from\n"
                 " * their notes to sound them with the mouth open, cents; the mouth for each\n"
                 " * quarter semitone the higher reed bends, Hz (0 past the deepest).\n */\n"
                 "struct HarpHoleMap {\n    float blowTune, drawTune;\n    float bendMouth[%d];\n};\n\n"
                 "/** Each key (kHarpKeyShift) and each hole. */\n"
                 "inline constexpr HarpHoleMap kHarpMaps[%d][%d] = {\n",
                 kBendSteps, kHarpKeys, kHarpHoles);
    for (int key = oneKey ? 5 : 0; key < (oneKey ? 6 : kHarpKeys); ++key) {
        std::fprintf(f, "    {\n");
        for (int hole = 0; hole < kHarpHoles; ++hole) {
            if (onlyHole && onlyHole != hole + 1) continue;
            const double blowHz = hzOf(kRichterBlow[hole] + kHarpKeyShift[key]), drawHz = hzOf(kRichterDraw[hole] + kHarpKeyShift[key]);
            const double open = openMouth(static_cast<float>(blowHz), static_cast<float>(drawHz));
            // Tune both reeds, each where it sounds: blown, then drawn.
            double tb = 0, td = 0;
            for (int pass = 0; pass < 3; ++pass) {
                const double b = blowHz * std::pow(2.0, tb / 1200), d = drawHz * std::pow(2.0, td / 1200);
                const double pb = play(b, d, open, kPressure), pd = play(b, d, open, -kPressure);
                if (verbose()) std::fprintf(stderr, "  pass %d: blow %.1f draw %.1f c\n", pass, pb ? cents(pb, blowHz) : 9999, pd ? cents(pd, drawHz) : 9999);
                if (pb > 0) tb -= cents(pb, blowHz);
                if (pd > 0) td -= cents(pd, drawHz);
            }
            const double b = blowHz * std::pow(2.0, tb / 1200), d = drawHz * std::pow(2.0, td / 1200);
            // The bend: the higher reed's direction, the mouth swept down from open.
            const bool drawBends = drawHz > blowHz;
            const float press = drawBends ? -kPressure : kPressure;
            const double note = drawBends ? drawHz : blowHz;
            float bend[kBendSteps] = {};
            bend[0] = static_cast<float>(open);
            int reached = 1, silent = 0;
            double lastHz = note, lastMouth = open;
            for (double mouth = open * 0.99; mouth > 0.3 * std::min(blowHz, drawHz) && reached < kBendSteps; mouth *= 0.99) {
                const double hz = play(b, d, mouth, press);
                if (verbose()) std::fprintf(stderr, "  bend mouth %.0f: %.1f c\n", mouth, hz ? cents(hz, note) : 9999);
                // A few silent steps are the reed choking on its way down; more, it has stopped.
                if (hz <= 0) {
                    if (++silent > 4) break;
                    continue;
                }
                silent = 0;
                if (std::fabs(cents(hz, lastHz)) > 150) break; // jumped to another reed's note
                while (reached < kBendSteps && cents(hz, note) <= -25.0 * reached) {
                    // Halve the step between the last mouth above it and this one.
                    double above = lastMouth, below = mouth;
                    for (int i = 0; i < 6; ++i) {
                        const double mid = std::sqrt(above * below), m = play(b, d, mid, press);
                        if (m > 0 && cents(m, note) <= -25.0 * reached) below = mid;
                        else above = mid;
                    }
                    // A step is kept only where the pitch is steady: a mouth a little
                    // either side, started afresh, plays within 30 cents of it.
                    bool steady = true;
                    for (const double nudge : {0.997, 1.003}) {
                        const double m = play(b, d, below * nudge, press);
                        if (m <= 0 || std::fabs(cents(m, note) + 25.0 * reached) > 30.0) steady = false;
                    }
                    if (!steady) break;
                    bend[reached++] = static_cast<float>(below);
                }
                if (reached < kBendSteps && bend[reached] == 0.0f && cents(hz, note) <= -25.0 * reached) break;
                lastHz = hz;
                lastMouth = mouth;
            }
            std::fprintf(f, "        {%.2ff, %.2ff, {", tb, td);
            for (int s = 0; s < kBendSteps; ++s) std::fprintf(f, "%s%.1ff", s ? ", " : "", bend[s]);
            std::fprintf(f, "}},\n");
            std::fprintf(stderr, "key %+d hole %2d: tune %+6.1f/%+6.1f c, bends %4.2f st\n", kHarpKeyShift[key], hole + 1, tb, td, (reached - 1) * 0.25);
        }
        std::fprintf(f, "    },\n");
    }
    std::fprintf(f, "};\n\n");
    // A reed alone behind a valve, blown with the mouth open: its tuning at each note.
    std::fprintf(f, "/** A reed alone behind its valve: how far it's tuned from each note, cents, from note kHarpSingleLow. */\n");
    std::fprintf(f, "inline constexpr int kHarpSingleLow = %d, kHarpSingleCount = %d;\n", kSingleLow, kSingleHigh - kSingleLow + 1);
    std::fprintf(f, "inline constexpr float kHarpSingle[%d] = {", kSingleHigh - kSingleLow + 1);
    for (int n = kSingleLow; n <= kSingleHigh; ++n) {
        const double hz = hzOf(n - 60), partner = hzOf(n - 58);
        double t = 0;
        for (int pass = 0; pass < 3; ++pass) {
            const double got = play(hz * std::pow(2.0, t / 1200), partner, openMouth(static_cast<float>(hz), static_cast<float>(partner)), kPressure, true);
            if (got > 0) t -= cents(got, hz);
        }
        std::fprintf(f, "%s%s%.2ff", n == kSingleLow ? "" : ",", (n - kSingleLow) % 8 == 0 ? "\n    " : " ", t);
        if (verbose()) std::fprintf(stderr, "single %d: %+.1f c\n", n, t);
    }
    std::fprintf(f, "\n};\n\n} // namespace acidulous::machine::draw\n");
    std::fclose(f);
    return 0;
}
