// Works out DrawTuning.h: how far each reed make plays from its own
// frequency, note by note, so Draw can tune each reed to sound its note, as
// a maker tunes a reed by filing it.
//
//   draw_tune.sh          writes app/src/main/cpp/engine/machine/draw/DrawTuning.h
//
// Each note's reed is blown at its kind's pressure for a second and the
// tip's crossings of its rest timed over the last 0.6 s, to a fraction of a
// sample; three passes, each retuning by what's left.
#include <engine/machine/draw/DrawKinds.h>
#include <engine/machine/draw/FreeReed.h>

#include <cmath>
#include <cstdio>
#include <string>
#include <xmmintrin.h>

using namespace acidulous::machine::draw;

namespace {

constexpr float kRate = 48000.0f;

/** What [hz] of reed plays at, Hz; 0 when it doesn't speak. */
double plays(float hz, const ReedMake &make, const KindVoice &kind) {
    FreeReed r;
    r.prepare(kRate);
    r.make(hz, make);
    r.clear();
    const int total = static_cast<int>(kRate), from = static_cast<int>(0.4f * kRate);
    double first = -1, last = -1;
    int crossings = 0;
    float was = 0.0f;
    for (int n = 0; n < total; ++n) {
        const float p = kind.pressure * std::fmin(1.0f, static_cast<float>(n) / (0.02f * kRate));
        r.step(p, kind.supply);
        const float d = r.tip() - r.rest();
        if (n > from && was > 0.0f && d <= 0.0f) {
            const double t = n - 1 + was / (was - d);
            if (first < 0) first = t;
            last = t;
            ++crossings;
        }
        was = d;
    }
    return crossings > 2 ? (crossings - 1) * kRate / (last - first) : 0.0;
}

} // namespace

int main(int argc, char **argv) {
    _mm_setcsr(_mm_getcsr() | 0x8040);
    const std::string out = argc > 1 ? argv[1] : "DrawTuning.h";
    const int kindOf[kMakes] = {Diatonic, Accordion, Melodica};
    const char *names[kMakes] = {"harmonica", "accordion", "melodica"};
    FILE *f = std::fopen(out.c_str(), "w");
    std::fprintf(f, "#pragma once\n// Generated by tools/draw_tune.sh: do not edit. How many cents each reed\n"
                    "// make's reed for a MIDI note must be tuned away from the note to sound it,\n"
                    "// at its kind's pressure. Notes outside 21..108 take the nearest.\n"
                    "namespace acidulous::machine::draw {\n\ninline constexpr float kReedTuning[%d][128] = {\n", kMakes);
    for (int m = 0; m < kMakes; ++m) {
        float cents[128] = {};
        double worst = 0;
        std::string silent;
        for (int note = 21; note <= 108; ++note) {
            const double want = 440.0 * std::pow(2.0, (note - 69) / 12.0);
            double tune = 0;
            for (int pass = 0; pass < 3; ++pass) {
                const double got = plays(static_cast<float>(want * std::pow(2.0, tune / 1200.0)), kMakes_[m], kKindVoices[kindOf[m]]);
                if (got <= 0) break;
                tune -= 1200.0 * std::log2(got / want);
            }
            const double got = plays(static_cast<float>(want * std::pow(2.0, tune / 1200.0)), kMakes_[m], kKindVoices[kindOf[m]]);
            if (got <= 0) {
                silent += " " + std::to_string(note);
                cents[note] = cents[note - 1];
                continue;
            }
            const double off = 1200.0 * std::log2(got / want);
            if (std::fabs(off) > std::fabs(worst)) worst = off;
            cents[note] = static_cast<float>(tune);
        }
        for (int note = 0; note < 21; ++note) cents[note] = cents[21];
        for (int note = 109; note < 128; ++note) cents[note] = cents[108];
        std::fprintf(f, "    // %s\n    {", names[m]);
        for (int note = 0; note < 128; ++note) std::fprintf(f, "%s%.2ff", note % 8 == 0 ? "\n        " : " ", cents[note]),
                                                std::fprintf(f, note < 127 ? "," : "");
        std::fprintf(f, "\n    },\n");
        std::printf("%-10s tuned 21..108; worst left %+.2f cents%s%s\n", names[m], worst,
                    silent.empty() ? "" : "; silent (the nearest's tuning):", silent.c_str());
    }
    std::fprintf(f, "};\n\n} // namespace acidulous::machine::draw\n");
    std::fclose(f);
    return 0;
}
