#!/usr/bin/env python3
"""Generates the engine's native calls for every platform from one list.

The list is EngineNative in commonMain (`internal expect object EngineNative`,
one `fun nativeX(...)` per call). The C++ behind each call is
Java_com_rm_acidulous_engine_EngineNative_* in platform/android/jni_bridge.cpp.
This writes each platform's side, which is never edited by hand:

- jvmShared (Android and the desktop): `actual external fun`, i.e. JNI.
- wasmJs (the browser): the same jni_bridge.cpp functions, compiled to
  WebAssembly against platform/web/jni.h and called through the page's
  script, with arguments and results passed as JNI objects.

A `suspend` call is a slow one, like decoding a file or rendering a song. On
the JVM it's the same JNI function, run on the caller's thread. In a browser
the caller's thread is the page's only one, so the call runs on an engine
thread (platform/web/web_async.cpp, also generated here) and the coroutine
waits without blocking the page.

Run after changing the list:   python3 tools/gen_engine_bridge.py
Check it is in step:           python3 tools/gen_engine_bridge.py --check
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = "shared/src/{}/kotlin/com/rm/acidulous/engine"
COMMON = ROOT / PKG.format("commonMain") / "EngineNative.kt"
JVM = ROOT / PKG.format("jvmShared") / "EngineNative.jvm.kt"
WASM = ROOT / PKG.format("wasmJsMain") / "EngineNative.wasmJs.kt"
ASYNC = ROOT / "app/src/main/cpp/platform/web/web_async.cpp"
SYMBOL = "Java_com_rm_acidulous_engine_EngineNative_"

# How a Kotlin type crosses to the bridge's JNI function in WebAssembly: how a
# value goes in, and after the call, what's copied back into the caller's array.
OBJECT_IN = {
    "String": "Jni.string({})", "String?": "Jni.string({})",
    "FloatArray": "Jni.floats({})", "FloatArray?": "Jni.floats({})",
    "IntArray": "Jni.ints({})", "IntArray?": "Jni.ints({})",
    "LongArray": "Jni.longs({})", "LongArray?": "Jni.longs({})",
    "Array<String>": "Jni.strings({})",
}
DIRECT = {"Int", "Float", "Long", "Double"}
# How a result comes back: the raw call's type, and what makes the Kotlin value.
RESULT = {
    None: ("Unit", None),
    "Unit": ("Unit", None),
    "Boolean": ("Int", "{} != 0"),
    "Int": ("Int", "{}"), "Float": ("Float", "{}"), "Long": ("Long", "{}"), "Double": ("Double", "{}"),
    "String": ("Int", "Jni.readString({})"), "String?": ("Int", "Jni.readStringOrNull({})"),
    "FloatArray": ("Int", "Jni.readFloats({}) ?: FloatArray(0)"), "FloatArray?": ("Int", "Jni.readFloats({})"),
    "IntArray": ("Int", "Jni.readInts({}) ?: IntArray(0)"), "IntArray?": ("Int", "Jni.readInts({})"),
    "LongArray": ("Int", "Jni.readLongs({}) ?: LongArray(0)"), "LongArray?": ("Int", "Jni.readLongs({})"),
    "Array<String>": ("Int", "Jni.readStrings({})"),
}
# A Kotlin type as its JNI function takes or returns it.
C_TYPE = {
    None: "void", "Unit": "void", "Int": "jint", "Float": "jfloat", "Long": "jlong", "Double": "jdouble",
    "Boolean": "jboolean", "String": "jstring", "String?": "jstring",
    "FloatArray": "jfloatArray", "FloatArray?": "jfloatArray", "IntArray": "jintArray", "IntArray?": "jintArray",
    "LongArray": "jlongArray", "LongArray?": "jlongArray", "Array<String>": "jobjectArray",
}
# Where a handed-over call's result is stored for the page (jniweb::Ticket),
# by the raw call's type.
TICKET_FIELD = {"Int": "i", "Float": "f", "Long": "j", "Double": "d"}
HEADER = "// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.\n"

DECL = re.compile(r"^    (suspend )?fun (native\w+)\((.*)\)(?:: ([A-Za-z<>?]+))?$")


def calls():
    out = []
    for line in COMMON.read_text().splitlines():
        m = DECL.match(line)
        if m:
            params = [p.strip() for p in m.group(3).split(",") if p.strip()]
            out.append((m.group(2), [tuple(x.strip() for x in p.split(":")) for p in params], m.group(4), bool(m.group(1))))
    return out


def signature(name, params, ret, suspend=False):
    return ("suspend " if suspend else "") + f"fun {name}({', '.join(f'{n}: {t}' for n, t in params)})" + (f": {ret}" if ret else "")


def jvm(decls):
    lines = []
    for name, params, ret, suspend in decls:
        if not suspend:
            lines.append(f"    actual external {signature(name, params, ret)}\n")
            continue
        # @JvmName keeps the JNI function's name, so jni_bridge.cpp's symbol
        # doesn't change. The suspend function next to it just calls it.
        args = ", ".join(n for n, _ in params)
        lines.append(f"    @JvmName(\"{name}\")\n    private external {signature('blocking_' + name, params, ret)}\n")
        lines.append(f"    actual {signature(name, params, ret, True)} = blocking_{name}({args})\n")
    body = "".join(lines)
    return (
        "package com.rm.acidulous.engine\n\n" + HEADER + "\n"
        "/** The engine through JNI: Java_com_rm_acidulous_engine_EngineNative_* in jni_bridge.cpp. */\n"
        "internal actual object EngineNative {\n"
        "    init {\n"
        "        System.loadLibrary(\"acidulous\")\n"
        "    }\n\n" + body + "}\n"
    )


def wasm(decls):
    raw, actual = [], []
    for name, params, ret, suspend in decls:
        raw_params, args, prep, after = ["env: Int"], ["Jni.env"], [], []
        for pname, ptype in params:
            if ptype in DIRECT:
                raw_params.append(f"{pname}: {ptype}")
                args.append(pname)
            elif ptype == "Boolean":
                raw_params.append(f"{pname}: Int")
                args.append(f"if ({pname}) 1 else 0")
            elif ptype in OBJECT_IN:
                raw_params.append(f"{pname}: Int")
                prep.append(f"val j{pname} = {OBJECT_IN[ptype].format(pname)}")
                args.append(f"j{pname}")
                if "Array" in ptype and ptype != "Array<String>":
                    after.append(f"Jni.copyBack(j{pname}, {pname})")
            else:
                raise SystemExit(f"gen_engine_bridge: {name} takes a {ptype}, which has no way across")
        if ret not in RESULT:
            raise SystemExit(f"gen_engine_bridge: {name} returns a {ret}, which has no way back")
        rtype, convert = RESULT[ret]
        if suspend:
            # Arguments go in an arena of the call's own, passed to an engine
            # thread with it, and read and freed when the page hears it's done.
            names = [p.split(":")[0] for p in raw_params[1:]]
            raw.append(f"private fun async_{name}({', '.join(['arena: Int'] + raw_params[1:])}): Int =\n"
                       f"    js(\"globalThis.acid._acid_async_{name}({', '.join(['arena'] + names)})\")\n")
            body = ["        val arena_ = Jni.openArena()"] + [f"        {p}" for p in prep]
            body.append(f"        val ticket_ = async_{name}({', '.join(['arena_'] + args[1:])})")
            body.append("        Jni.await(ticket_)")
            body += [f"        {a}" for a in after]
            if convert is not None:
                body.append(f"        val result_ = {convert.format(f'Jni.result{rtype}(ticket_)')}")
            body.append("        Jni.releaseAsync(ticket_)")
            if convert is not None:
                body.append("        return result_")
            actual.append(f"    actual {signature(name, params, ret, True)} {{\n" + "\n".join(body) + "\n    }\n")
            continue
        call_args = ", ".join(["env", "0"] + [p.split(":")[0] for p in raw_params[1:]])
        raw.append(f"private fun raw_{name}({', '.join(raw_params)}): {rtype} =\n"
                   f"    js(\"globalThis.acid._{SYMBOL}{name}({call_args})\")\n")
        body = [f"        {p}" for p in prep]
        call = f"raw_{name}({', '.join(args)})"
        if convert is None:
            body.append(f"        {call}")
            body += [f"        {a}" for a in after]
            body.append("        Jni.release()")
        else:
            # Local names no parameter uses (one parameter is called `out`).
            body.append(f"        val raw_ = {call}")
            body += [f"        {a}" for a in after]
            body.append(f"        val result_ = {convert.format('raw_')}")
            body.append("        Jni.release()")
            body.append("        return result_")
        actual.append(f"    actual {signature(name, params, ret)} {{\n" + "\n".join(body) + "\n    }\n")
    return (
        "@file:Suppress(\"FunctionName\")\n\npackage com.rm.acidulous.engine\n\n" + HEADER + "\n"
        + "\n".join(raw) + "\n"
        "/** The engine through its bridge compiled to WebAssembly: see Jni and platform/web/jni.h. */\n"
        "internal actual object EngineNative {\n" + "\n".join(actual) + "}\n"
    )


def web_async(decls):
    out = [
        "// The engine calls that take long, handed to a thread of the engine's own so\n"
        "// the page is not held up: see tools/gen_engine_bridge.py and jniweb::runAsync\n"
        "// in web_bridge.cpp. Each is the phone's own JNI function, called unchanged.\n",
        HEADER + "\n",
        "#include <jni.h>\n#include <emscripten/emscripten.h>\n#include <cstdint>\n\n",
        'extern "C" JNIEnv *acid_jni_env();\n\n',
    ]
    for name, params, ret, suspend in decls:
        if not suspend:
            continue
        ctypes = [C_TYPE[t] for _, t in params]
        out.append(f'extern "C" {C_TYPE[ret]} {SYMBOL}{name}({", ".join(["JNIEnv *", "jobject"] + ctypes)});\n')
        cparams = ", ".join(["jniweb::Arena *arena"] + [f"{c} {n}" for c, (n, _) in zip(ctypes, params)])
        call = f"{SYMBOL}{name}({', '.join(['acid_jni_env()', 'nullptr'] + [n for n, _ in params])})"
        rtype = RESULT[ret][0]
        if C_TYPE[ret] == "void":
            store = f"{call};"
        elif C_TYPE[ret] in ("jint", "jboolean"):
            store = f"t.i = {call};"
        elif rtype == "Int":
            store = f"t.i = static_cast<int32_t>(reinterpret_cast<intptr_t>({call}));"
        else:
            store = f"t.{TICKET_FIELD[rtype]} = {call};"
        out.append(f'extern "C" EMSCRIPTEN_KEEPALIVE int acid_async_{name}({cparams}) {{\n'
                   f"    return jniweb::runAsync(arena, [=](jniweb::Ticket &t) {{ {store} }});\n}}\n\n")
    return "".join(out).rstrip("\n") + "\n"


def main():
    decls = calls()
    outputs = {JVM: jvm(decls), WASM: wasm(decls), ASYNC: web_async(decls)}
    if "--check" in sys.argv:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            for p in stale:
                print(f"  FAIL engine bridge: {p.relative_to(ROOT)} is not what EngineNative would produce")
            print("       run: python3 tools/gen_engine_bridge.py")
            sys.exit(1)
        print(f"  ok   engine bridge: {len(decls)} calls, in step")
        return
    for p, text in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"gen_engine_bridge: {len(decls)} calls")


main()
