#!/usr/bin/env python3
"""The engine's native calls, for every platform, from one list.

The list is EngineNative in commonMain - `internal expect object EngineNative`,
one `fun nativeX(...)` per call - and the C++ behind each call is
platform/android/jni_bridge.cpp's Java_com_rm_acidulous_engine_EngineNative_*.
From the list this writes the platforms' halves, which are never edited by hand:

- jvmShared (Android and the desktop): `actual external fun`, i.e. JNI.
- wasmJs (the browser): the same functions of jni_bridge.cpp, compiled to
  WebAssembly against platform/web/jni.h and called through the page's
  script, with arguments and results carried across as JNI objects.

Run after changing the list:   python3 tools/gen_engine_bridge.py
Check it is in step:           python3 tools/gen_engine_bridge.py --check
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = "shared/src/{}/kotlin/com/rm/acidulous/engine"
COMMON = ROOT / PKG.format("commonMain") / "EngineNative.kt"
JVM = ROOT / PKG.format("jvmShared") / "EngineNative.jvm.kt"
HEADER = "// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.\n"

DECL = re.compile(r"^    fun (native\w+)\((.*)\)(?:: ([A-Za-z<>?]+))?$")


def calls():
    out = []
    for line in COMMON.read_text().splitlines():
        m = DECL.match(line)
        if m:
            params = [p.strip() for p in m.group(2).split(",") if p.strip()]
            out.append((m.group(1), [tuple(x.strip() for x in p.split(":")) for p in params], m.group(3)))
    return out


def signature(name, params, ret):
    return f"fun {name}({', '.join(f'{n}: {t}' for n, t in params)})" + (f": {ret}" if ret else "")


def jvm(decls):
    body = "".join(f"    actual external {signature(*d)}\n" for d in decls)
    return (
        "package com.rm.acidulous.engine\n\n" + HEADER + "\n"
        "/** The engine through JNI: Java_com_rm_acidulous_engine_EngineNative_* in jni_bridge.cpp. */\n"
        "internal actual object EngineNative {\n"
        "    init {\n"
        "        System.loadLibrary(\"acidulous\")\n"
        "    }\n\n" + body + "}\n"
    )


def main():
    decls = calls()
    outputs = {JVM: jvm(decls)}
    if "--check" in sys.argv:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            for p in stale:
                print(f"  FAIL engine bridge: {p.relative_to(ROOT)} is not what EngineNative would produce")
            print("       run: python3 tools/gen_engine_bridge.py")
            sys.exit(1)
        print(f"  ok   engine bridge: {len(decls)} calls, in step")
        return
    for p, text in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"gen_engine_bridge: {len(decls)} calls")


main()
