#!/usr/bin/env python3
"""Turn manual/*.md into the manual the app carries.

**One source, two places it appears.** The manual is Markdown in `manual/`, so
it is read on the git and reviewed in a diff like everything else here, and the
app's Help window shows the same words. A manual that disagrees with the app is
worse than no manual, and two hand-kept copies disagree within a release - so
the app holds no second copy. This lifts the Markdown into
`model/Manual.kt`, the way gen_param_labels.py lifts the panels' own wording
into ParamLabels.kt, and for the same reason.

Not a Markdown renderer: the app has none and does not need one. The subset the
manual is written in is the subset a manual needs -

    # Title              the section, one per file
    > summary            the line under it in the contents
    ## Heading           a heading inside the section
    paragraph            run of lines, joined
    - bullet             a list item
    1. step              a numbered item
    `code` and **bold**  left in the text, drawn by the reader

Re-run after editing the manual:  python3 tools/gen_manual.py
Check it is in step (this is what all_tests.sh runs):
                                  python3 tools/gen_manual.py --check
"""
import pathlib
import re
import sys

SRC = pathlib.Path("manual")
OUT = pathlib.Path("app/src/main/java/com/rm/acidulous/model/Manual.kt")

HEADING, PARA, BULLET, STEP = 0, 1, 2, 3


def parse(path):
    """One file into (title, summary, blocks)."""
    title, summary, blocks = None, "", []
    para = []

    def flush():
        if para:
            blocks.append((PARA, " ".join(para)))
            para.clear()

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line.strip():
            flush()
            continue
        if line.startswith("# "):
            flush()
            title = line[2:].strip()
        elif line.startswith("> "):
            flush()
            summary = line[2:].strip()
        elif line.startswith("## "):
            flush()
            blocks.append((HEADING, line[3:].strip()))
        elif line.startswith("- "):
            flush()
            blocks.append((BULLET, line[2:].strip()))
        elif re.match(r"^\d+\. ", line):
            flush()
            blocks.append((STEP, line.split(". ", 1)[1].strip()))
        elif line.startswith("  ") and blocks and blocks[-1][0] in (BULLET, STEP) and not para:
            # A continuation line of the item above, indented.
            kind, text = blocks[-1]
            blocks[-1] = (kind, text + " " + line.strip())
        else:
            para.append(line.strip())
    flush()
    if title is None:
        sys.exit(f"gen_manual: {path} has no '# Title' line")
    return title, summary, blocks


def kotlin(sections):
    q = lambda s: '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'
    out = [
        "package com.rm.acidulous.model",
        "",
        "// Generated by tools/gen_manual.py from manual/. Do not edit by hand:",
        "// the Markdown in manual/ is the manual, and this is the same words in",
        "// the form the app can draw. Re-run the script after editing it.",
        "",
        "/** What a line of the manual is. Inline `code` and **bold** stay in the text. */",
        "enum class ManualKind { Heading, Para, Bullet, Step }",
        "",
        "class ManualBlock(val kind: ManualKind, val text: String)",
        "",
        "class ManualSection(val title: String, val summary: String, val blocks: List<ManualBlock>)",
        "",
        "object Manual {",
        "    val sections: List<ManualSection> = listOf(",
    ]
    kinds = {HEADING: "Heading", PARA: "Para", BULLET: "Bullet", STEP: "Step"}
    for title, summary, blocks in sections:
        out.append(f"        ManualSection({q(title)}, {q(summary)}, listOf(")
        for kind, text in blocks:
            out.append(f"            ManualBlock(ManualKind.{kinds[kind]}, {q(text)}),")
        out.append("        )),")
    out += ["    )", "}", ""]
    return "\n".join(out)


def main():
    files = sorted(p for p in SRC.glob("*.md") if p.name != "README.md")
    if not files:
        sys.exit("gen_manual: manual/ has no sections")
    sections = [parse(p) for p in files]
    text = kotlin(sections)
    words = sum(len(t.split()) for _, _, bs in sections for _, t in bs)
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != text:
            print(f"  FAIL manual: {OUT} is not what manual/ would produce")
            print("       run: python3 tools/gen_manual.py")
            sys.exit(1)
        print(f"  ok   manual: {len(sections)} sections, {words} words, in step")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"gen_manual: {len(sections)} sections, {words} words -> {OUT}")


main()
