#!/usr/bin/env python3
"""Android's key codes, as a Kotlin object the desktop build can use too.

Key bindings are saved as Android key codes, and the keyboard code compares
against android.view.KeyEvent's constants. Off Android there is no such
class, so this copies its KEYCODE_, META_ and ACTION_ constants - values and
names - out of the SDK's android.jar into ui/KeyCodes.kt. Android keeps
sending its own codes; the desktop maps its keys onto them.

Run: python3 tools/gen_keycodes.py   (needs javap and the SDK in ~/Android/Sdk)
"""
import pathlib, re, subprocess, sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT = ROOT / "shared/src/commonMain/kotlin/com/rm/acidulous/ui/KeyCodes.kt"
jars = sorted((pathlib.Path.home() / "Android/Sdk/platforms").glob("*/android.jar"))
if not jars:
    sys.exit("no android.jar under ~/Android/Sdk/platforms")
jar = jars[-1]
text = subprocess.run(["javap", "-constants", "-cp", str(jar), "android.view.KeyEvent"],
                      capture_output=True, text=True, check=True).stdout
consts = [(n, int(v)) for n, v in re.findall(r"public static final int ((?:KEYCODE|META|ACTION)_\w+) = (-?\d+);", text)]
keycodes = [(n, v) for n, v in consts if n.startswith("KEYCODE_")]
lines = [
    "package com.rm.acidulous.ui",
    "",
    "// GENERATED by tools/gen_keycodes.py from %s - do not edit." % jar.parent.name + "/android.jar",
    "",
    "/**",
    " * android.view.KeyEvent's constants, for code that also runs off Android.",
    " *",
    " * The same values, so key bindings saved on a phone mean the same keys here,",
    " * and the same names, so [keyCodeToString] says what Android's did.",
    " */",
    "object KeyCodes {",
]
lines += ["    const val %s = %d" % (n, v) for n, v in consts]
lines += [
    "",
    "    private val NAMES: Map<Int, String> = mapOf(",
]
seen = set()
for n, v in keycodes:
    if v in seen:
        continue
    seen.add(v)
    lines.append('        %d to "%s",' % (v, n))
lines += [
    "    )",
    "",
    "    /** KeyEvent.keyCodeToString: the constant's name, or the number for a code it has none for. */",
    "    fun keyCodeToString(code: Int): String = NAMES[code] ?: code.toString()",
    "}",
    "",
]
OUT.write_text("\n".join(lines))
print("%d constants, %d key names -> %s" % (len(consts), len(seen), OUT.relative_to(ROOT)))
