#!/usr/bin/env python3
"""Turn manual/*.md into the manual the app carries.

**One source, two places it appears.** The manual is Markdown in `manual/`, so
it is read on the git and reviewed in a diff like everything else here, and the
app's Help window shows the same words. A manual that disagrees with the app is
worse than no manual, and two hand-kept copies disagree within a release - so
the app holds no second copy. This lifts the Markdown into
`model/Manual.kt`, the way gen_param_labels.py lifts the panels' own wording
into ParamLabels.kt, and for the same reason.

Not a Markdown renderer: the app has none and does not need one. The subset the
manual is written in is the subset a manual needs -

    # Title              the section, one per file (and one per sub-page)
    > summary            the line under it in the contents
    ## Heading           a heading inside the section
    paragraph            run of lines, joined
    - bullet             a list item
    1. step              a numbered item
    `code` and **bold**  left in the text, drawn by the reader

Two things are written from it and neither is ever edited by hand: the app's
`model/Manual.kt`, and the contents list in `manual/README.md` - because a
contents page typed out beside the sections it lists is a second copy of every
title and every summary, which is the drift this whole script exists to stop.

Re-run after editing the manual:  python3 tools/gen_manual.py
Check both are in step (this is what all_tests.sh runs):
                                  python3 tools/gen_manual.py --check
"""
import pathlib
import re
import sys

SRC = pathlib.Path("manual")
OUT = pathlib.Path("app/src/main/java/com/rm/acidulous/model/Manual.kt")
INDEX = SRC / "README.md"
OPEN, CLOSE = "<!-- contents -->", "<!-- /contents -->"

HEADING, PARA, BULLET, STEP = 0, 1, 2, 3


def parse(path):
    """One file into (title, summary, blocks)."""
    title, summary, blocks = None, "", []
    para = []

    def flush():
        if para:
            blocks.append((PARA, " ".join(para)))
            para.clear()

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line.strip():
            flush()
            continue
        if line.startswith("# "):
            flush()
            title = line[2:].strip()
        elif line.startswith("> "):
            flush()
            summary = line[2:].strip()
        elif line.startswith("## "):
            flush()
            blocks.append((HEADING, line[3:].strip()))
        elif line.startswith("- "):
            flush()
            blocks.append((BULLET, line[2:].strip()))
        elif re.match(r"^\d+\. ", line):
            flush()
            blocks.append((STEP, line.split(". ", 1)[1].strip()))
        elif line.startswith("  ") and blocks and blocks[-1][0] in (BULLET, STEP) and not para:
            # A continuation line of the item above, indented.
            kind, text = blocks[-1]
            blocks[-1] = (kind, text + " " + line.strip())
        else:
            para.append(line.strip())
    flush()
    if title is None:
        sys.exit(f"gen_manual: {path} has no '# Title' line")
    return title, summary, blocks


def children_of(path):
    """The sub-pages of a section: `04-the-machines/` beside `04-the-machines.md`.

    A machine deserves more than a line and the machines page would be
    unreadable at twenty times that length, so a section may have pages of its
    own. Everything else is unchanged: they are the same Markdown, parsed by
    the same parser, and they appear in the same contents.
    """
    folder = path.with_suffix("")
    if not folder.is_dir():
        return []
    return [(p, parse(p)) for p in sorted(folder.glob("*.md"))]


def kotlin(sections):
    q = lambda s: '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'
    out = [
        "package com.rm.acidulous.model",
        "",
        "// Generated by tools/gen_manual.py from manual/. Do not edit by hand:",
        "// the Markdown in manual/ is the manual, and this is the same words in",
        "// the form the app can draw. Re-run the script after editing it.",
        "",
        "/** What a line of the manual is. Inline `code` and **bold** stay in the text. */",
        "enum class ManualKind { Heading, Para, Bullet, Step }",
        "",
        "class ManualBlock(val kind: ManualKind, val text: String)",
        "",
        "class ManualSection(",
        "    val title: String,",
        "    val summary: String,",
        "    val blocks: List<ManualBlock>,",
        "    /** Pages of this one's own: a machine is more than a line. */",
        "    val children: List<ManualSection> = emptyList(),",
        ")",
        "",
        "object Manual {",
        "    val sections: List<ManualSection> = listOf(",
    ]
    kinds = {HEADING: "Heading", PARA: "Para", BULLET: "Bullet", STEP: "Step"}

    def emit(title, summary, blocks, kids, pad):
        out.append(f"{pad}ManualSection({q(title)}, {q(summary)}, listOf(")
        for kind, text in blocks:
            out.append(f"{pad}    ManualBlock(ManualKind.{kinds[kind]}, {q(text)}),")
        if not kids:
            out.append(f"{pad})),")
            return
        out.append(f"{pad}), listOf(")
        for _, (t, s2, b2) in kids:
            emit(t, s2, b2, [], pad + "    ")
        out.append(f"{pad})),")

    for (title, summary, blocks), kids in sections:
        emit(title, summary, blocks, kids, "        ")
    out += ["    )", "}", ""]
    return "\n".join(out)


def contents(files, sections):
    """The numbered list, between the markers in manual/README.md."""
    rows = []
    for i, (path, ((title, summary, _), kids)) in enumerate(zip(files, sections), 1):
        rows.append(f"{i}. [{title}]({path.name}) - {summary[0].lower() + summary[1:]}")
        for kp, (kt, ks, _) in kids:
            here = f"{path.stem}/{kp.name}"
            rows.append(f"    - [{kt}]({here}) - {ks[0].lower() + ks[1:]}")
    return "\n".join([OPEN, ""] + rows + ["", CLOSE])


def indexed(files, sections):
    """manual/README.md with its contents list brought up to date."""
    text = INDEX.read_text(encoding="utf-8")
    a, b = text.find(OPEN), text.find(CLOSE)
    if a < 0 or b < 0:
        sys.exit(f"gen_manual: {INDEX} has no {OPEN} ... {CLOSE} to write into")
    return text[:a] + contents(files, sections) + text[b + len(CLOSE):]


def main():
    files = sorted(p for p in SRC.glob("*.md") if p.name != "README.md")
    if not files:
        sys.exit("gen_manual: manual/ has no sections")
    sections = [(parse(p), children_of(p)) for p in files]
    text = kotlin(sections)
    index = indexed(files, sections)
    words = sum(len(t.split()) for (_, _, bs), _ in sections for _, t in bs)
    pages = len(sections)
    for _, kids in sections:
        pages += len(kids)
        words += sum(len(t.split()) for _, (_, _, bs) in kids for _, t in bs)
    if "--check" in sys.argv:
        for path, want in ((OUT, text), (INDEX, index)):
            have = path.read_text(encoding="utf-8") if path.exists() else ""
            if have != want:
                print(f"  FAIL manual: {path} is not what manual/ would produce")
                print("       run: python3 tools/gen_manual.py")
                sys.exit(1)
        print(f"  ok   manual: {pages} pages, {words} words, in step")
        return
    OUT.write_text(text, encoding="utf-8")
    INDEX.write_text(index, encoding="utf-8")
    print(f"gen_manual: {pages} pages, {words} words -> {OUT} and {INDEX}")


main()
