#!/usr/bin/env python3
"""The engine's native calls, for every platform, from one list.

The list is EngineNative in commonMain - `internal expect object EngineNative`,
one `fun nativeX(...)` per call - and the C++ behind each call is
platform/android/jni_bridge.cpp's Java_com_rm_acidulous_engine_EngineNative_*.
From the list this writes the platforms' halves, which are never edited by hand:

- jvmShared (Android and the desktop): `actual external fun`, i.e. JNI.
- wasmJs (the browser): the same functions of jni_bridge.cpp, compiled to
  WebAssembly against platform/web/jni.h and called through the page's
  script, with arguments and results carried across as JNI objects.

Run after changing the list:   python3 tools/gen_engine_bridge.py
Check it is in step:           python3 tools/gen_engine_bridge.py --check
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = "shared/src/{}/kotlin/com/rm/acidulous/engine"
COMMON = ROOT / PKG.format("commonMain") / "EngineNative.kt"
JVM = ROOT / PKG.format("jvmShared") / "EngineNative.jvm.kt"
WASM = ROOT / PKG.format("wasmJsMain") / "EngineNative.wasmJs.kt"
SYMBOL = "Java_com_rm_acidulous_engine_EngineNative_"

# How a Kotlin type crosses to the bridge's JNI function in WebAssembly: the
# type the raw call takes, how a value goes in, and after the call, what is
# copied back into the caller's array.
OBJECT_IN = {
    "String": "Jni.string({})", "String?": "Jni.string({})",
    "FloatArray": "Jni.floats({})", "FloatArray?": "Jni.floats({})",
    "IntArray": "Jni.ints({})", "IntArray?": "Jni.ints({})",
    "LongArray": "Jni.longs({})", "LongArray?": "Jni.longs({})",
    "Array<String>": "Jni.strings({})",
}
DIRECT = {"Int", "Float", "Long", "Double"}
# How a result comes back: the raw call's type, and what makes the Kotlin value.
RESULT = {
    None: ("Unit", None),
    "Unit": ("Unit", None),
    "Boolean": ("Int", "{} != 0"),
    "Int": ("Int", "{}"), "Float": ("Float", "{}"), "Long": ("Long", "{}"), "Double": ("Double", "{}"),
    "String": ("Int", "Jni.readString({})"), "String?": ("Int", "Jni.readStringOrNull({})"),
    "FloatArray": ("Int", "Jni.readFloats({}) ?: FloatArray(0)"), "FloatArray?": ("Int", "Jni.readFloats({})"),
    "IntArray": ("Int", "Jni.readInts({}) ?: IntArray(0)"), "IntArray?": ("Int", "Jni.readInts({})"),
    "LongArray": ("Int", "Jni.readLongs({}) ?: LongArray(0)"), "LongArray?": ("Int", "Jni.readLongs({})"),
    "Array<String>": ("Int", "Jni.readStrings({})"),
}
HEADER = "// Generated by tools/gen_engine_bridge.py from EngineNative in commonMain. Do not edit.\n"

DECL = re.compile(r"^    fun (native\w+)\((.*)\)(?:: ([A-Za-z<>?]+))?$")


def calls():
    out = []
    for line in COMMON.read_text().splitlines():
        m = DECL.match(line)
        if m:
            params = [p.strip() for p in m.group(2).split(",") if p.strip()]
            out.append((m.group(1), [tuple(x.strip() for x in p.split(":")) for p in params], m.group(3)))
    return out


def signature(name, params, ret):
    return f"fun {name}({', '.join(f'{n}: {t}' for n, t in params)})" + (f": {ret}" if ret else "")


def jvm(decls):
    body = "".join(f"    actual external {signature(*d)}\n" for d in decls)
    return (
        "package com.rm.acidulous.engine\n\n" + HEADER + "\n"
        "/** The engine through JNI: Java_com_rm_acidulous_engine_EngineNative_* in jni_bridge.cpp. */\n"
        "internal actual object EngineNative {\n"
        "    init {\n"
        "        System.loadLibrary(\"acidulous\")\n"
        "    }\n\n" + body + "}\n"
    )


def wasm(decls):
    raw, actual = [], []
    for name, params, ret in decls:
        raw_params, args, prep, after = ["env: Int"], ["Jni.env"], [], []
        for pname, ptype in params:
            if ptype in DIRECT:
                raw_params.append(f"{pname}: {ptype}")
                args.append(pname)
            elif ptype == "Boolean":
                raw_params.append(f"{pname}: Int")
                args.append(f"if ({pname}) 1 else 0")
            elif ptype in OBJECT_IN:
                raw_params.append(f"{pname}: Int")
                prep.append(f"val j{pname} = {OBJECT_IN[ptype].format(pname)}")
                args.append(f"j{pname}")
                if "Array" in ptype and ptype != "Array<String>":
                    after.append(f"Jni.copyBack(j{pname}, {pname})")
            else:
                raise SystemExit(f"gen_engine_bridge: {name} takes a {ptype}, which has no way across")
        if ret not in RESULT:
            raise SystemExit(f"gen_engine_bridge: {name} returns a {ret}, which has no way back")
        rtype, convert = RESULT[ret]
        call_args = ", ".join(["env", "0"] + [p.split(":")[0] for p in raw_params[1:]])
        raw.append(f"private fun raw_{name}({', '.join(raw_params)}): {rtype} =\n"
                   f"    js(\"globalThis.acid._{SYMBOL}{name}({call_args})\")\n")
        body = [f"        {p}" for p in prep]
        call = f"raw_{name}({', '.join(args)})"
        if convert is None:
            body.append(f"        {call}")
            body += [f"        {a}" for a in after]
            body.append("        Jni.release()")
        else:
            # Locals no parameter is called: one is called `out`.
            body.append(f"        val raw_ = {call}")
            body += [f"        {a}" for a in after]
            body.append(f"        val result_ = {convert.format('raw_')}")
            body.append("        Jni.release()")
            body.append("        return result_")
        actual.append(f"    actual {signature(name, params, ret)} {{\n" + "\n".join(body) + "\n    }\n")
    return (
        "@file:Suppress(\"FunctionName\")\n\npackage com.rm.acidulous.engine\n\n" + HEADER + "\n"
        + "\n".join(raw) + "\n"
        "/** The engine through its bridge compiled to WebAssembly: see Jni and platform/web/jni.h. */\n"
        "internal actual object EngineNative {\n" + "\n".join(actual) + "}\n"
    )


def main():
    decls = calls()
    outputs = {JVM: jvm(decls), WASM: wasm(decls)}
    if "--check" in sys.argv:
        stale = [p for p, text in outputs.items() if not p.exists() or p.read_text() != text]
        if stale:
            for p in stale:
                print(f"  FAIL engine bridge: {p.relative_to(ROOT)} is not what EngineNative would produce")
            print("       run: python3 tools/gen_engine_bridge.py")
            sys.exit(1)
        print(f"  ok   engine bridge: {len(decls)} calls, in step")
        return
    for p, text in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
    print(f"gen_engine_bridge: {len(decls)} calls")


main()
