package com.rm.acidulous.ui

// GENERATED by tools/gen_keycodes.py from android-37.0 - do not edit./android.jar

/**
 * android.view.KeyEvent's constants, for code that also runs off Android.
 *
 * The same values, so key bindings saved on a phone mean the same keys here,
 * and the same names, so [keyCodeToString] says what Android's did.
 */
object KeyCodes {
    const val ACTION_DOWN = 0
    const val ACTION_MULTIPLE = 2
    const val ACTION_UP = 1
    const val KEYCODE_0 = 7
    const val KEYCODE_1 = 8
    const val KEYCODE_11 = 227
    const val KEYCODE_12 = 228
    const val KEYCODE_2 = 9
    const val KEYCODE_3 = 10
    const val KEYCODE_3D_MODE = 206
    const val KEYCODE_4 = 11
    const val KEYCODE_5 = 12
    const val KEYCODE_6 = 13
    const val KEYCODE_7 = 14
    const val KEYCODE_8 = 15
    const val KEYCODE_9 = 16
    const val KEYCODE_A = 29
    const val KEYCODE_ACCESSIBILITY = 338
    const val KEYCODE_ALL_APPS = 284
    const val KEYCODE_ALT_LEFT = 57
    const val KEYCODE_ALT_RIGHT = 58
    const val KEYCODE_APOSTROPHE = 75
    const val KEYCODE_APP_SWITCH = 187
    const val KEYCODE_ASSIST = 219
    const val KEYCODE_AT = 77
    const val KEYCODE_AVR_INPUT = 182
    const val KEYCODE_AVR_POWER = 181
    const val KEYCODE_B = 30
    const val KEYCODE_BACK = 4
    const val KEYCODE_BACKSLASH = 73
    const val KEYCODE_BOOKMARK = 174
    const val KEYCODE_BREAK = 121
    const val KEYCODE_BRIGHTNESS_DOWN = 220
    const val KEYCODE_BRIGHTNESS_UP = 221
    const val KEYCODE_BUTTON_1 = 188
    const val KEYCODE_BUTTON_10 = 197
    const val KEYCODE_BUTTON_11 = 198
    const val KEYCODE_BUTTON_12 = 199
    const val KEYCODE_BUTTON_13 = 200
    const val KEYCODE_BUTTON_14 = 201
    const val KEYCODE_BUTTON_15 = 202
    const val KEYCODE_BUTTON_16 = 203
    const val KEYCODE_BUTTON_2 = 189
    const val KEYCODE_BUTTON_3 = 190
    const val KEYCODE_BUTTON_4 = 191
    const val KEYCODE_BUTTON_5 = 192
    const val KEYCODE_BUTTON_6 = 193
    const val KEYCODE_BUTTON_7 = 194
    const val KEYCODE_BUTTON_8 = 195
    const val KEYCODE_BUTTON_9 = 196
    const val KEYCODE_BUTTON_A = 96
    const val KEYCODE_BUTTON_B = 97
    const val KEYCODE_BUTTON_C = 98
    const val KEYCODE_BUTTON_L1 = 102
    const val KEYCODE_BUTTON_L2 = 104
    const val KEYCODE_BUTTON_MODE = 110
    const val KEYCODE_BUTTON_R1 = 103
    const val KEYCODE_BUTTON_R2 = 105
    const val KEYCODE_BUTTON_SELECT = 109
    const val KEYCODE_BUTTON_START = 108
    const val KEYCODE_BUTTON_THUMBL = 106
    const val KEYCODE_BUTTON_THUMBR = 107
    const val KEYCODE_BUTTON_X = 99
    const val KEYCODE_BUTTON_Y = 100
    const val KEYCODE_BUTTON_Z = 101
    const val KEYCODE_C = 31
    const val KEYCODE_CALCULATOR = 210
    const val KEYCODE_CALENDAR = 208
    const val KEYCODE_CALL = 5
    const val KEYCODE_CAMERA = 27
    const val KEYCODE_CAPS_LOCK = 115
    const val KEYCODE_CAPTIONS = 175
    const val KEYCODE_CHANNEL_DOWN = 167
    const val KEYCODE_CHANNEL_UP = 166
    const val KEYCODE_CLEAR = 28
    const val KEYCODE_CLOSE = 321
    const val KEYCODE_COMMA = 55
    const val KEYCODE_CONTACTS = 207
    const val KEYCODE_CONTEXTUAL_INSERT = 340
    const val KEYCODE_CONTEXTUAL_SEARCH = 339
    const val KEYCODE_COPY = 278
    const val KEYCODE_CTRL_LEFT = 113
    const val KEYCODE_CTRL_RIGHT = 114
    const val KEYCODE_CUT = 277
    const val KEYCODE_D = 32
    const val KEYCODE_DEL = 67
    const val KEYCODE_DEMO_APP_1 = 301
    const val KEYCODE_DEMO_APP_2 = 302
    const val KEYCODE_DEMO_APP_3 = 303
    const val KEYCODE_DEMO_APP_4 = 304
    const val KEYCODE_DICTATE = 319
    const val KEYCODE_DO_NOT_DISTURB = 322
    const val KEYCODE_DPAD_CENTER = 23
    const val KEYCODE_DPAD_DOWN = 20
    const val KEYCODE_DPAD_DOWN_LEFT = 269
    const val KEYCODE_DPAD_DOWN_RIGHT = 271
    const val KEYCODE_DPAD_LEFT = 21
    const val KEYCODE_DPAD_RIGHT = 22
    const val KEYCODE_DPAD_UP = 19
    const val KEYCODE_DPAD_UP_LEFT = 268
    const val KEYCODE_DPAD_UP_RIGHT = 270
    const val KEYCODE_DVR = 173
    const val KEYCODE_E = 33
    const val KEYCODE_EISU = 212
    const val KEYCODE_EMOJI_PICKER = 317
    const val KEYCODE_ENDCALL = 6
    const val KEYCODE_ENTER = 66
    const val KEYCODE_ENVELOPE = 65
    const val KEYCODE_EQUALS = 70
    const val KEYCODE_ESCAPE = 111
    const val KEYCODE_EXPLORER = 64
    const val KEYCODE_F = 34
    const val KEYCODE_F1 = 131
    const val KEYCODE_F10 = 140
    const val KEYCODE_F11 = 141
    const val KEYCODE_F12 = 142
    const val KEYCODE_F13 = 326
    const val KEYCODE_F14 = 327
    const val KEYCODE_F15 = 328
    const val KEYCODE_F16 = 329
    const val KEYCODE_F17 = 330
    const val KEYCODE_F18 = 331
    const val KEYCODE_F19 = 332
    const val KEYCODE_F2 = 132
    const val KEYCODE_F20 = 333
    const val KEYCODE_F21 = 334
    const val KEYCODE_F22 = 335
    const val KEYCODE_F23 = 336
    const val KEYCODE_F24 = 337
    const val KEYCODE_F3 = 133
    const val KEYCODE_F4 = 134
    const val KEYCODE_F5 = 135
    const val KEYCODE_F6 = 136
    const val KEYCODE_F7 = 137
    const val KEYCODE_F8 = 138
    const val KEYCODE_F9 = 139
    const val KEYCODE_FEATURED_APP_1 = 297
    const val KEYCODE_FEATURED_APP_2 = 298
    const val KEYCODE_FEATURED_APP_3 = 299
    const val KEYCODE_FEATURED_APP_4 = 300
    const val KEYCODE_FOCUS = 80
    const val KEYCODE_FORWARD = 125
    const val KEYCODE_FORWARD_DEL = 112
    const val KEYCODE_FULLSCREEN = 325
    const val KEYCODE_FUNCTION = 119
    const val KEYCODE_G = 35
    const val KEYCODE_GRAVE = 68
    const val KEYCODE_GUIDE = 172
    const val KEYCODE_H = 36
    const val KEYCODE_HEADSETHOOK = 79
    const val KEYCODE_HELP = 259
    const val KEYCODE_HENKAN = 214
    const val KEYCODE_HOME = 3
    const val KEYCODE_I = 37
    const val KEYCODE_INFO = 165
    const val KEYCODE_INSERT = 124
    const val KEYCODE_J = 38
    const val KEYCODE_K = 39
    const val KEYCODE_KANA = 218
    const val KEYCODE_KATAKANA_HIRAGANA = 215
    const val KEYCODE_KEYBOARD_BACKLIGHT_DOWN = 305
    const val KEYCODE_KEYBOARD_BACKLIGHT_TOGGLE = 307
    const val KEYCODE_KEYBOARD_BACKLIGHT_UP = 306
    const val KEYCODE_L = 40
    const val KEYCODE_LANGUAGE_SWITCH = 204
    const val KEYCODE_LAST_CHANNEL = 229
    const val KEYCODE_LEFT_BRACKET = 71
    const val KEYCODE_LOCK = 324
    const val KEYCODE_M = 41
    const val KEYCODE_MACRO_1 = 313
    const val KEYCODE_MACRO_2 = 314
    const val KEYCODE_MACRO_3 = 315
    const val KEYCODE_MACRO_4 = 316
    const val KEYCODE_MANNER_MODE = 205
    const val KEYCODE_MEDIA_AUDIO_TRACK = 222
    const val KEYCODE_MEDIA_CLOSE = 128
    const val KEYCODE_MEDIA_EJECT = 129
    const val KEYCODE_MEDIA_FAST_FORWARD = 90
    const val KEYCODE_MEDIA_NEXT = 87
    const val KEYCODE_MEDIA_PAUSE = 127
    const val KEYCODE_MEDIA_PLAY = 126
    const val KEYCODE_MEDIA_PLAY_PAUSE = 85
    const val KEYCODE_MEDIA_PREVIOUS = 88
    const val KEYCODE_MEDIA_RECORD = 130
    const val KEYCODE_MEDIA_REWIND = 89
    const val KEYCODE_MEDIA_SKIP_BACKWARD = 273
    const val KEYCODE_MEDIA_SKIP_FORWARD = 272
    const val KEYCODE_MEDIA_STEP_BACKWARD = 275
    const val KEYCODE_MEDIA_STEP_FORWARD = 274
    const val KEYCODE_MEDIA_STOP = 86
    const val KEYCODE_MEDIA_TOP_MENU = 226
    const val KEYCODE_MENU = 82
    const val KEYCODE_META_LEFT = 117
    const val KEYCODE_META_RIGHT = 118
    const val KEYCODE_MINUS = 69
    const val KEYCODE_MOVE_END = 123
    const val KEYCODE_MOVE_HOME = 122
    const val KEYCODE_MUHENKAN = 213
    const val KEYCODE_MUSIC = 209
    const val KEYCODE_MUTE = 91
    const val KEYCODE_N = 42
    const val KEYCODE_NAVIGATE_IN = 262
    const val KEYCODE_NAVIGATE_NEXT = 261
    const val KEYCODE_NAVIGATE_OUT = 263
    const val KEYCODE_NAVIGATE_PREVIOUS = 260
    const val KEYCODE_NEW = 320
    const val KEYCODE_NOTIFICATION = 83
    const val KEYCODE_NUM = 78
    const val KEYCODE_NUMPAD_0 = 144
    const val KEYCODE_NUMPAD_1 = 145
    const val KEYCODE_NUMPAD_2 = 146
    const val KEYCODE_NUMPAD_3 = 147
    const val KEYCODE_NUMPAD_4 = 148
    const val KEYCODE_NUMPAD_5 = 149
    const val KEYCODE_NUMPAD_6 = 150
    const val KEYCODE_NUMPAD_7 = 151
    const val KEYCODE_NUMPAD_8 = 152
    const val KEYCODE_NUMPAD_9 = 153
    const val KEYCODE_NUMPAD_ADD = 157
    const val KEYCODE_NUMPAD_COMMA = 159
    const val KEYCODE_NUMPAD_DIVIDE = 154
    const val KEYCODE_NUMPAD_DOT = 158
    const val KEYCODE_NUMPAD_ENTER = 160
    const val KEYCODE_NUMPAD_EQUALS = 161
    const val KEYCODE_NUMPAD_LEFT_PAREN = 162
    const val KEYCODE_NUMPAD_MULTIPLY = 155
    const val KEYCODE_NUMPAD_RIGHT_PAREN = 163
    const val KEYCODE_NUMPAD_SUBTRACT = 156
    const val KEYCODE_NUM_LOCK = 143
    const val KEYCODE_O = 43
    const val KEYCODE_P = 44
    const val KEYCODE_PAGE_DOWN = 93
    const val KEYCODE_PAGE_UP = 92
    const val KEYCODE_PAIRING = 225
    const val KEYCODE_PASTE = 279
    const val KEYCODE_PERIOD = 56
    const val KEYCODE_PICTSYMBOLS = 94
    const val KEYCODE_PLUS = 81
    const val KEYCODE_POUND = 18
    const val KEYCODE_POWER = 26
    const val KEYCODE_PRINT = 323
    const val KEYCODE_PROFILE_SWITCH = 288
    const val KEYCODE_PROG_BLUE = 186
    const val KEYCODE_PROG_GREEN = 184
    const val KEYCODE_PROG_RED = 183
    const val KEYCODE_PROG_YELLOW = 185
    const val KEYCODE_Q = 45
    const val KEYCODE_R = 46
    const val KEYCODE_RECENT_APPS = 312
    const val KEYCODE_REFRESH = 285
    const val KEYCODE_RIGHT_BRACKET = 72
    const val KEYCODE_RO = 217
    const val KEYCODE_S = 47
    const val KEYCODE_SCREENSHOT = 318
    const val KEYCODE_SCROLL_LOCK = 116
    const val KEYCODE_SEARCH = 84
    const val KEYCODE_SEMICOLON = 74
    const val KEYCODE_SETTINGS = 176
    const val KEYCODE_SHIFT_LEFT = 59
    const val KEYCODE_SHIFT_RIGHT = 60
    const val KEYCODE_SLASH = 76
    const val KEYCODE_SLEEP = 223
    const val KEYCODE_SOFT_LEFT = 1
    const val KEYCODE_SOFT_RIGHT = 2
    const val KEYCODE_SOFT_SLEEP = 276
    const val KEYCODE_SPACE = 62
    const val KEYCODE_STAR = 17
    const val KEYCODE_STB_INPUT = 180
    const val KEYCODE_STB_POWER = 179
    const val KEYCODE_STEM_1 = 265
    const val KEYCODE_STEM_2 = 266
    const val KEYCODE_STEM_3 = 267
    const val KEYCODE_STEM_PRIMARY = 264
    const val KEYCODE_STYLUS_BUTTON_PRIMARY = 308
    const val KEYCODE_STYLUS_BUTTON_SECONDARY = 309
    const val KEYCODE_STYLUS_BUTTON_TAIL = 311
    const val KEYCODE_STYLUS_BUTTON_TERTIARY = 310
    const val KEYCODE_SWITCH_CHARSET = 95
    const val KEYCODE_SYM = 63
    const val KEYCODE_SYSRQ = 120
    const val KEYCODE_SYSTEM_NAVIGATION_DOWN = 281
    const val KEYCODE_SYSTEM_NAVIGATION_LEFT = 282
    const val KEYCODE_SYSTEM_NAVIGATION_RIGHT = 283
    const val KEYCODE_SYSTEM_NAVIGATION_UP = 280
    const val KEYCODE_T = 48
    const val KEYCODE_TAB = 61
    const val KEYCODE_THUMBS_DOWN = 287
    const val KEYCODE_THUMBS_UP = 286
    const val KEYCODE_TV = 170
    const val KEYCODE_TV_ANTENNA_CABLE = 242
    const val KEYCODE_TV_AUDIO_DESCRIPTION = 252
    const val KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN = 254
    const val KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP = 253
    const val KEYCODE_TV_CONTENTS_MENU = 256
    const val KEYCODE_TV_DATA_SERVICE = 230
    const val KEYCODE_TV_INPUT = 178
    const val KEYCODE_TV_INPUT_COMPONENT_1 = 249
    const val KEYCODE_TV_INPUT_COMPONENT_2 = 250
    const val KEYCODE_TV_INPUT_COMPOSITE_1 = 247
    const val KEYCODE_TV_INPUT_COMPOSITE_2 = 248
    const val KEYCODE_TV_INPUT_HDMI_1 = 243
    const val KEYCODE_TV_INPUT_HDMI_2 = 244
    const val KEYCODE_TV_INPUT_HDMI_3 = 245
    const val KEYCODE_TV_INPUT_HDMI_4 = 246
    const val KEYCODE_TV_INPUT_VGA_1 = 251
    const val KEYCODE_TV_MEDIA_CONTEXT_MENU = 257
    const val KEYCODE_TV_NETWORK = 241
    const val KEYCODE_TV_NUMBER_ENTRY = 234
    const val KEYCODE_TV_POWER = 177
    const val KEYCODE_TV_RADIO_SERVICE = 232
    const val KEYCODE_TV_SATELLITE = 237
    const val KEYCODE_TV_SATELLITE_BS = 238
    const val KEYCODE_TV_SATELLITE_CS = 239
    const val KEYCODE_TV_SATELLITE_SERVICE = 240
    const val KEYCODE_TV_TELETEXT = 233
    const val KEYCODE_TV_TERRESTRIAL_ANALOG = 235
    const val KEYCODE_TV_TERRESTRIAL_DIGITAL = 236
    const val KEYCODE_TV_TIMER_PROGRAMMING = 258
    const val KEYCODE_TV_ZOOM_MODE = 255
    const val KEYCODE_U = 49
    const val KEYCODE_UNKNOWN = 0
    const val KEYCODE_V = 50
    const val KEYCODE_VIDEO_APP_1 = 289
    const val KEYCODE_VIDEO_APP_2 = 290
    const val KEYCODE_VIDEO_APP_3 = 291
    const val KEYCODE_VIDEO_APP_4 = 292
    const val KEYCODE_VIDEO_APP_5 = 293
    const val KEYCODE_VIDEO_APP_6 = 294
    const val KEYCODE_VIDEO_APP_7 = 295
    const val KEYCODE_VIDEO_APP_8 = 296
    const val KEYCODE_VOICE_ASSIST = 231
    const val KEYCODE_VOLUME_DOWN = 25
    const val KEYCODE_VOLUME_MUTE = 164
    const val KEYCODE_VOLUME_UP = 24
    const val KEYCODE_W = 51
    const val KEYCODE_WAKEUP = 224
    const val KEYCODE_WINDOW = 171
    const val KEYCODE_X = 52
    const val KEYCODE_Y = 53
    const val KEYCODE_YEN = 216
    const val KEYCODE_Z = 54
    const val KEYCODE_ZENKAKU_HANKAKU = 211
    const val KEYCODE_ZOOM_IN = 168
    const val KEYCODE_ZOOM_OUT = 169
    const val META_ALT_LEFT_ON = 16
    const val META_ALT_MASK = 50
    const val META_ALT_ON = 2
    const val META_ALT_RIGHT_ON = 32
    const val META_CAPS_LOCK_ON = 1048576
    const val META_CTRL_LEFT_ON = 8192
    const val META_CTRL_MASK = 28672
    const val META_CTRL_ON = 4096
    const val META_CTRL_RIGHT_ON = 16384
    const val META_FUNCTION_ON = 8
    const val META_META_LEFT_ON = 131072
    const val META_META_MASK = 458752
    const val META_META_ON = 65536
    const val META_META_RIGHT_ON = 262144
    const val META_NUM_LOCK_ON = 2097152
    const val META_SCROLL_LOCK_ON = 4194304
    const val META_SHIFT_LEFT_ON = 64
    const val META_SHIFT_MASK = 193
    const val META_SHIFT_ON = 1
    const val META_SHIFT_RIGHT_ON = 128
    const val META_SYM_ON = 4

    private val NAMES: Map<Int, String> = mapOf(
        7 to "KEYCODE_0",
        8 to "KEYCODE_1",
        227 to "KEYCODE_11",
        228 to "KEYCODE_12",
        9 to "KEYCODE_2",
        10 to "KEYCODE_3",
        206 to "KEYCODE_3D_MODE",
        11 to "KEYCODE_4",
        12 to "KEYCODE_5",
        13 to "KEYCODE_6",
        14 to "KEYCODE_7",
        15 to "KEYCODE_8",
        16 to "KEYCODE_9",
        29 to "KEYCODE_A",
        338 to "KEYCODE_ACCESSIBILITY",
        284 to "KEYCODE_ALL_APPS",
        57 to "KEYCODE_ALT_LEFT",
        58 to "KEYCODE_ALT_RIGHT",
        75 to "KEYCODE_APOSTROPHE",
        187 to "KEYCODE_APP_SWITCH",
        219 to "KEYCODE_ASSIST",
        77 to "KEYCODE_AT",
        182 to "KEYCODE_AVR_INPUT",
        181 to "KEYCODE_AVR_POWER",
        30 to "KEYCODE_B",
        4 to "KEYCODE_BACK",
        73 to "KEYCODE_BACKSLASH",
        174 to "KEYCODE_BOOKMARK",
        121 to "KEYCODE_BREAK",
        220 to "KEYCODE_BRIGHTNESS_DOWN",
        221 to "KEYCODE_BRIGHTNESS_UP",
        188 to "KEYCODE_BUTTON_1",
        197 to "KEYCODE_BUTTON_10",
        198 to "KEYCODE_BUTTON_11",
        199 to "KEYCODE_BUTTON_12",
        200 to "KEYCODE_BUTTON_13",
        201 to "KEYCODE_BUTTON_14",
        202 to "KEYCODE_BUTTON_15",
        203 to "KEYCODE_BUTTON_16",
        189 to "KEYCODE_BUTTON_2",
        190 to "KEYCODE_BUTTON_3",
        191 to "KEYCODE_BUTTON_4",
        192 to "KEYCODE_BUTTON_5",
        193 to "KEYCODE_BUTTON_6",
        194 to "KEYCODE_BUTTON_7",
        195 to "KEYCODE_BUTTON_8",
        196 to "KEYCODE_BUTTON_9",
        96 to "KEYCODE_BUTTON_A",
        97 to "KEYCODE_BUTTON_B",
        98 to "KEYCODE_BUTTON_C",
        102 to "KEYCODE_BUTTON_L1",
        104 to "KEYCODE_BUTTON_L2",
        110 to "KEYCODE_BUTTON_MODE",
        103 to "KEYCODE_BUTTON_R1",
        105 to "KEYCODE_BUTTON_R2",
        109 to "KEYCODE_BUTTON_SELECT",
        108 to "KEYCODE_BUTTON_START",
        106 to "KEYCODE_BUTTON_THUMBL",
        107 to "KEYCODE_BUTTON_THUMBR",
        99 to "KEYCODE_BUTTON_X",
        100 to "KEYCODE_BUTTON_Y",
        101 to "KEYCODE_BUTTON_Z",
        31 to "KEYCODE_C",
        210 to "KEYCODE_CALCULATOR",
        208 to "KEYCODE_CALENDAR",
        5 to "KEYCODE_CALL",
        27 to "KEYCODE_CAMERA",
        115 to "KEYCODE_CAPS_LOCK",
        175 to "KEYCODE_CAPTIONS",
        167 to "KEYCODE_CHANNEL_DOWN",
        166 to "KEYCODE_CHANNEL_UP",
        28 to "KEYCODE_CLEAR",
        321 to "KEYCODE_CLOSE",
        55 to "KEYCODE_COMMA",
        207 to "KEYCODE_CONTACTS",
        340 to "KEYCODE_CONTEXTUAL_INSERT",
        339 to "KEYCODE_CONTEXTUAL_SEARCH",
        278 to "KEYCODE_COPY",
        113 to "KEYCODE_CTRL_LEFT",
        114 to "KEYCODE_CTRL_RIGHT",
        277 to "KEYCODE_CUT",
        32 to "KEYCODE_D",
        67 to "KEYCODE_DEL",
        301 to "KEYCODE_DEMO_APP_1",
        302 to "KEYCODE_DEMO_APP_2",
        303 to "KEYCODE_DEMO_APP_3",
        304 to "KEYCODE_DEMO_APP_4",
        319 to "KEYCODE_DICTATE",
        322 to "KEYCODE_DO_NOT_DISTURB",
        23 to "KEYCODE_DPAD_CENTER",
        20 to "KEYCODE_DPAD_DOWN",
        269 to "KEYCODE_DPAD_DOWN_LEFT",
        271 to "KEYCODE_DPAD_DOWN_RIGHT",
        21 to "KEYCODE_DPAD_LEFT",
        22 to "KEYCODE_DPAD_RIGHT",
        19 to "KEYCODE_DPAD_UP",
        268 to "KEYCODE_DPAD_UP_LEFT",
        270 to "KEYCODE_DPAD_UP_RIGHT",
        173 to "KEYCODE_DVR",
        33 to "KEYCODE_E",
        212 to "KEYCODE_EISU",
        317 to "KEYCODE_EMOJI_PICKER",
        6 to "KEYCODE_ENDCALL",
        66 to "KEYCODE_ENTER",
        65 to "KEYCODE_ENVELOPE",
        70 to "KEYCODE_EQUALS",
        111 to "KEYCODE_ESCAPE",
        64 to "KEYCODE_EXPLORER",
        34 to "KEYCODE_F",
        131 to "KEYCODE_F1",
        140 to "KEYCODE_F10",
        141 to "KEYCODE_F11",
        142 to "KEYCODE_F12",
        326 to "KEYCODE_F13",
        327 to "KEYCODE_F14",
        328 to "KEYCODE_F15",
        329 to "KEYCODE_F16",
        330 to "KEYCODE_F17",
        331 to "KEYCODE_F18",
        332 to "KEYCODE_F19",
        132 to "KEYCODE_F2",
        333 to "KEYCODE_F20",
        334 to "KEYCODE_F21",
        335 to "KEYCODE_F22",
        336 to "KEYCODE_F23",
        337 to "KEYCODE_F24",
        133 to "KEYCODE_F3",
        134 to "KEYCODE_F4",
        135 to "KEYCODE_F5",
        136 to "KEYCODE_F6",
        137 to "KEYCODE_F7",
        138 to "KEYCODE_F8",
        139 to "KEYCODE_F9",
        297 to "KEYCODE_FEATURED_APP_1",
        298 to "KEYCODE_FEATURED_APP_2",
        299 to "KEYCODE_FEATURED_APP_3",
        300 to "KEYCODE_FEATURED_APP_4",
        80 to "KEYCODE_FOCUS",
        125 to "KEYCODE_FORWARD",
        112 to "KEYCODE_FORWARD_DEL",
        325 to "KEYCODE_FULLSCREEN",
        119 to "KEYCODE_FUNCTION",
        35 to "KEYCODE_G",
        68 to "KEYCODE_GRAVE",
        172 to "KEYCODE_GUIDE",
        36 to "KEYCODE_H",
        79 to "KEYCODE_HEADSETHOOK",
        259 to "KEYCODE_HELP",
        214 to "KEYCODE_HENKAN",
        3 to "KEYCODE_HOME",
        37 to "KEYCODE_I",
        165 to "KEYCODE_INFO",
        124 to "KEYCODE_INSERT",
        38 to "KEYCODE_J",
        39 to "KEYCODE_K",
        218 to "KEYCODE_KANA",
        215 to "KEYCODE_KATAKANA_HIRAGANA",
        305 to "KEYCODE_KEYBOARD_BACKLIGHT_DOWN",
        307 to "KEYCODE_KEYBOARD_BACKLIGHT_TOGGLE",
        306 to "KEYCODE_KEYBOARD_BACKLIGHT_UP",
        40 to "KEYCODE_L",
        204 to "KEYCODE_LANGUAGE_SWITCH",
        229 to "KEYCODE_LAST_CHANNEL",
        71 to "KEYCODE_LEFT_BRACKET",
        324 to "KEYCODE_LOCK",
        41 to "KEYCODE_M",
        313 to "KEYCODE_MACRO_1",
        314 to "KEYCODE_MACRO_2",
        315 to "KEYCODE_MACRO_3",
        316 to "KEYCODE_MACRO_4",
        205 to "KEYCODE_MANNER_MODE",
        222 to "KEYCODE_MEDIA_AUDIO_TRACK",
        128 to "KEYCODE_MEDIA_CLOSE",
        129 to "KEYCODE_MEDIA_EJECT",
        90 to "KEYCODE_MEDIA_FAST_FORWARD",
        87 to "KEYCODE_MEDIA_NEXT",
        127 to "KEYCODE_MEDIA_PAUSE",
        126 to "KEYCODE_MEDIA_PLAY",
        85 to "KEYCODE_MEDIA_PLAY_PAUSE",
        88 to "KEYCODE_MEDIA_PREVIOUS",
        130 to "KEYCODE_MEDIA_RECORD",
        89 to "KEYCODE_MEDIA_REWIND",
        273 to "KEYCODE_MEDIA_SKIP_BACKWARD",
        272 to "KEYCODE_MEDIA_SKIP_FORWARD",
        275 to "KEYCODE_MEDIA_STEP_BACKWARD",
        274 to "KEYCODE_MEDIA_STEP_FORWARD",
        86 to "KEYCODE_MEDIA_STOP",
        226 to "KEYCODE_MEDIA_TOP_MENU",
        82 to "KEYCODE_MENU",
        117 to "KEYCODE_META_LEFT",
        118 to "KEYCODE_META_RIGHT",
        69 to "KEYCODE_MINUS",
        123 to "KEYCODE_MOVE_END",
        122 to "KEYCODE_MOVE_HOME",
        213 to "KEYCODE_MUHENKAN",
        209 to "KEYCODE_MUSIC",
        91 to "KEYCODE_MUTE",
        42 to "KEYCODE_N",
        262 to "KEYCODE_NAVIGATE_IN",
        261 to "KEYCODE_NAVIGATE_NEXT",
        263 to "KEYCODE_NAVIGATE_OUT",
        260 to "KEYCODE_NAVIGATE_PREVIOUS",
        320 to "KEYCODE_NEW",
        83 to "KEYCODE_NOTIFICATION",
        78 to "KEYCODE_NUM",
        144 to "KEYCODE_NUMPAD_0",
        145 to "KEYCODE_NUMPAD_1",
        146 to "KEYCODE_NUMPAD_2",
        147 to "KEYCODE_NUMPAD_3",
        148 to "KEYCODE_NUMPAD_4",
        149 to "KEYCODE_NUMPAD_5",
        150 to "KEYCODE_NUMPAD_6",
        151 to "KEYCODE_NUMPAD_7",
        152 to "KEYCODE_NUMPAD_8",
        153 to "KEYCODE_NUMPAD_9",
        157 to "KEYCODE_NUMPAD_ADD",
        159 to "KEYCODE_NUMPAD_COMMA",
        154 to "KEYCODE_NUMPAD_DIVIDE",
        158 to "KEYCODE_NUMPAD_DOT",
        160 to "KEYCODE_NUMPAD_ENTER",
        161 to "KEYCODE_NUMPAD_EQUALS",
        162 to "KEYCODE_NUMPAD_LEFT_PAREN",
        155 to "KEYCODE_NUMPAD_MULTIPLY",
        163 to "KEYCODE_NUMPAD_RIGHT_PAREN",
        156 to "KEYCODE_NUMPAD_SUBTRACT",
        143 to "KEYCODE_NUM_LOCK",
        43 to "KEYCODE_O",
        44 to "KEYCODE_P",
        93 to "KEYCODE_PAGE_DOWN",
        92 to "KEYCODE_PAGE_UP",
        225 to "KEYCODE_PAIRING",
        279 to "KEYCODE_PASTE",
        56 to "KEYCODE_PERIOD",
        94 to "KEYCODE_PICTSYMBOLS",
        81 to "KEYCODE_PLUS",
        18 to "KEYCODE_POUND",
        26 to "KEYCODE_POWER",
        323 to "KEYCODE_PRINT",
        288 to "KEYCODE_PROFILE_SWITCH",
        186 to "KEYCODE_PROG_BLUE",
        184 to "KEYCODE_PROG_GREEN",
        183 to "KEYCODE_PROG_RED",
        185 to "KEYCODE_PROG_YELLOW",
        45 to "KEYCODE_Q",
        46 to "KEYCODE_R",
        312 to "KEYCODE_RECENT_APPS",
        285 to "KEYCODE_REFRESH",
        72 to "KEYCODE_RIGHT_BRACKET",
        217 to "KEYCODE_RO",
        47 to "KEYCODE_S",
        318 to "KEYCODE_SCREENSHOT",
        116 to "KEYCODE_SCROLL_LOCK",
        84 to "KEYCODE_SEARCH",
        74 to "KEYCODE_SEMICOLON",
        176 to "KEYCODE_SETTINGS",
        59 to "KEYCODE_SHIFT_LEFT",
        60 to "KEYCODE_SHIFT_RIGHT",
        76 to "KEYCODE_SLASH",
        223 to "KEYCODE_SLEEP",
        1 to "KEYCODE_SOFT_LEFT",
        2 to "KEYCODE_SOFT_RIGHT",
        276 to "KEYCODE_SOFT_SLEEP",
        62 to "KEYCODE_SPACE",
        17 to "KEYCODE_STAR",
        180 to "KEYCODE_STB_INPUT",
        179 to "KEYCODE_STB_POWER",
        265 to "KEYCODE_STEM_1",
        266 to "KEYCODE_STEM_2",
        267 to "KEYCODE_STEM_3",
        264 to "KEYCODE_STEM_PRIMARY",
        308 to "KEYCODE_STYLUS_BUTTON_PRIMARY",
        309 to "KEYCODE_STYLUS_BUTTON_SECONDARY",
        311 to "KEYCODE_STYLUS_BUTTON_TAIL",
        310 to "KEYCODE_STYLUS_BUTTON_TERTIARY",
        95 to "KEYCODE_SWITCH_CHARSET",
        63 to "KEYCODE_SYM",
        120 to "KEYCODE_SYSRQ",
        281 to "KEYCODE_SYSTEM_NAVIGATION_DOWN",
        282 to "KEYCODE_SYSTEM_NAVIGATION_LEFT",
        283 to "KEYCODE_SYSTEM_NAVIGATION_RIGHT",
        280 to "KEYCODE_SYSTEM_NAVIGATION_UP",
        48 to "KEYCODE_T",
        61 to "KEYCODE_TAB",
        287 to "KEYCODE_THUMBS_DOWN",
        286 to "KEYCODE_THUMBS_UP",
        170 to "KEYCODE_TV",
        242 to "KEYCODE_TV_ANTENNA_CABLE",
        252 to "KEYCODE_TV_AUDIO_DESCRIPTION",
        254 to "KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN",
        253 to "KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP",
        256 to "KEYCODE_TV_CONTENTS_MENU",
        230 to "KEYCODE_TV_DATA_SERVICE",
        178 to "KEYCODE_TV_INPUT",
        249 to "KEYCODE_TV_INPUT_COMPONENT_1",
        250 to "KEYCODE_TV_INPUT_COMPONENT_2",
        247 to "KEYCODE_TV_INPUT_COMPOSITE_1",
        248 to "KEYCODE_TV_INPUT_COMPOSITE_2",
        243 to "KEYCODE_TV_INPUT_HDMI_1",
        244 to "KEYCODE_TV_INPUT_HDMI_2",
        245 to "KEYCODE_TV_INPUT_HDMI_3",
        246 to "KEYCODE_TV_INPUT_HDMI_4",
        251 to "KEYCODE_TV_INPUT_VGA_1",
        257 to "KEYCODE_TV_MEDIA_CONTEXT_MENU",
        241 to "KEYCODE_TV_NETWORK",
        234 to "KEYCODE_TV_NUMBER_ENTRY",
        177 to "KEYCODE_TV_POWER",
        232 to "KEYCODE_TV_RADIO_SERVICE",
        237 to "KEYCODE_TV_SATELLITE",
        238 to "KEYCODE_TV_SATELLITE_BS",
        239 to "KEYCODE_TV_SATELLITE_CS",
        240 to "KEYCODE_TV_SATELLITE_SERVICE",
        233 to "KEYCODE_TV_TELETEXT",
        235 to "KEYCODE_TV_TERRESTRIAL_ANALOG",
        236 to "KEYCODE_TV_TERRESTRIAL_DIGITAL",
        258 to "KEYCODE_TV_TIMER_PROGRAMMING",
        255 to "KEYCODE_TV_ZOOM_MODE",
        49 to "KEYCODE_U",
        0 to "KEYCODE_UNKNOWN",
        50 to "KEYCODE_V",
        289 to "KEYCODE_VIDEO_APP_1",
        290 to "KEYCODE_VIDEO_APP_2",
        291 to "KEYCODE_VIDEO_APP_3",
        292 to "KEYCODE_VIDEO_APP_4",
        293 to "KEYCODE_VIDEO_APP_5",
        294 to "KEYCODE_VIDEO_APP_6",
        295 to "KEYCODE_VIDEO_APP_7",
        296 to "KEYCODE_VIDEO_APP_8",
        231 to "KEYCODE_VOICE_ASSIST",
        25 to "KEYCODE_VOLUME_DOWN",
        164 to "KEYCODE_VOLUME_MUTE",
        24 to "KEYCODE_VOLUME_UP",
        51 to "KEYCODE_W",
        224 to "KEYCODE_WAKEUP",
        171 to "KEYCODE_WINDOW",
        52 to "KEYCODE_X",
        53 to "KEYCODE_Y",
        216 to "KEYCODE_YEN",
        54 to "KEYCODE_Z",
        211 to "KEYCODE_ZENKAKU_HANKAKU",
        168 to "KEYCODE_ZOOM_IN",
        169 to "KEYCODE_ZOOM_OUT",
    )

    /** KeyEvent.keyCodeToString: the constant's name, or the number for a code it has none for. */
    fun keyCodeToString(code: Int): String = NAMES[code] ?: code.toString()
}
