package com.rm.acidulous.ui

import androidx.compose.runtime.Composable
import com.rm.acidulous.res.AppStrings

/**
 * A panel's word in the phone's language.
 *
 * The panels are written in English - `PanelKnob(b, "f_res", "reso")` - and
 * the English is the key: [PANEL_WORDS], generated by tools/panel_words.py
 * from the panels themselves, says which string resource carries each word.
 * A word with a number in it ("op 3", "lane 2") is looked up as its template
 * ("op %d") and the number put back. Anything not in the table - a patch's
 * name, a word already translated - comes back as it went in.
 */
internal fun AppStrings.panelWord(english: String): String {
    PANEL_WORDS[english]?.let { return getString(it) }
    val numbers = NUMBER.findAll(english).map { it.value.toInt() }.toList()
    if (numbers.isNotEmpty()) {
        PANEL_WORDS[english.replace(NUMBER, "%d")]?.let { return getString(it, *numbers.toTypedArray()) }
    }
    return english
}

@Composable
internal fun panelWord(english: String): String = AppStrings.panelWord(english)

@Composable
internal fun panelWords(english: List<String>): List<String> {
    return english.map { AppStrings.panelWord(it) }
}

private val NUMBER = Regex("\\d+")
